### ISSUE TITLE
[NGSICartoDBSink] Add documentation

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1016]
This implies:

- [x] Creating `doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_cartodb_sink.md`.
- [x] Creating `doc/cygnus-common/backends_catalogue/cartodb_backend.md`.
- [x] Updating the main README for Cygnus and the README for cygnus-ngsi.
- [x] Updating fiware-iot-stack.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1022
