### ISSUE TITLE
[cygnus-ngsi, cygnus-common][releasing] Add admin port environment variable to Dockerfile

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1020]
This will allow for configuring it via the `entrypoint` shell script.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Apart from the admin port environment variable it's suitable to add a service port environment variable in order to get configurable values.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1027
