### ISSUE TITLE
[cygnus-ngsi][grouping rules] Remove support to old `matching_table` parameter

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1048]
Originally, `matching_table` was the parameter pointing to the grouping rules configuration file. Then, we decided to use `grouping_rules_file` and we deprecated `matching_table`. Now it is the time to definitely remove the old parameter.

This affects `NGSIGroupingInterceptor.java`.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1050
