### ISSUE TITLE
[cygnus-ngsi][grouping rules] Detect invalid configurations

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1049]
When a configured parameter is not OK, the grouping interceptor should become "invalid" (i.e. the `start()` method does not anything upon `invalidConfiguration == true`.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1051
