### ISSUE TITLE
Cygnus: Tool to subscribe Cygnus

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#11]
Moved from https://github.com/telefonicaid/fiware-livedemoapp/issues/11:

Configuring Orion-Cosmos integration currently needs a NGSI10 suscribeContext operation so ngsi2cosmos receives Orion notifications. Currently, this subscription has to be done "manually".

However, it could be great to provide a simple script tool for user, so such tools does the subscription on behalf the user.

**Comment by frbattid** [comment]
Closing, since this feature will be included as part of the REST API of Cygnus: https://github.com/telefonicaid/fiware-cygnus/issues/169
