### ISSUE TITLE
[doc] Add integration examples

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1132]
This will be a folder called `doc/<agent>/integration`.

For instance, an integration of Orion, Cygnus and Kafka would be under `doc/<agent-name>/integration/orion_cygnus_kafka.md`.

Additionally, the main README.md should add this line in the "Further documentation" section:

<i>
Nevertheless...
</i>
<i>
Of special interest are the per-agent *integration* examples under `doc/<agent>/integration`.
</i>
<i>
The per agent...
</i>

The same update must be done in doc/index.md (it is the equivalent of the README in readthedocs).

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1134
