### ISSUE TITLE
[cygnus-ngsi][Grouping Rules] Original service path within persisted data is replaced by grouped one

### ISSUE THREAD

**Issue by rianwouters** [telefonicaid/fiware-cygnus#1142]
example:

  "grouping_rules": [
    {
      "id": 1,
      "fields": [
          "entityType"
      ],
      "regex": "Room",
      "destination": "Rooms",
      "fiware_service_path": "/"
    }
}

given the entities already have an service path, it's not possible to keep to replicate the existing servicepath.

Suggestion: if the fiware_service_path field is missing or empty, the grouped-path will duplicate the existing one.

**Comment by frbattid** [comment]
I've tested it and works fine.

Grouping rules:

```
{
    "grouping_rules": [
        {
            "id": 1,
            "fields": [
                "entityType"
            ],
            "regex": "Room",
            "destination": "new_grouped_dest",
            "fiware_service_path": "/anysubservice"
        }
      ]
}
```

Logs showing the grouping rules are running and active:

```
time=2016-09-13T13:12:13.521UTC | lvl=INFO | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.interceptors.CygnusGroupingRules[53] : Grouping rules read: {    "grouping_rules": [        {            "id": 1,            "fields": [                "entityType"            ],            "regex": "Room",            "destination": "new_grouped_dest",            "fiware_service_path": "/anysubservice"        }      ]}
time=2016-09-13T13:12:13.539UTC | lvl=INFO | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.interceptors.CygnusGroupingRules[65] : Grouping rules syntax is OK
time=2016-09-13T13:12:13.540UTC | lvl=INFO | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.interceptors.CygnusGroupingRules[73] : Grouping rules loaded in memory
```

I'm sending a notification about an entity `Room1` of type `Room`, belonging to the FIWARE service `frbtest` and FIWARE servivce path `/anysubservice`. This logs shows the reception of the notification:

```
time=2016-09-13T13:13:00.477UTC | lvl=INFO | corr=682d8ee0-5f33-4df0-8cdf-5240522411de | trans=682d8ee0-5f33-4df0-8cdf-5240522411de | srv=frbtest | subsrv=/anysubservice | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[271] : Received data ({  "subscriptionId" : "51c0ac9ed714fb3b37d7d5a8",  "originator" : "localhost",  "contextResponses" : [    {      "contextElement" : {        "attributes" : [          {            "name" : "temperature",            "type" : "centigrade",            "value" : "26.5"          }        ],        "type" : "Room",        "isPattern" : "false",        "id" : "Room1"      },      "statusCode" : {        "code" : "200",        "reasonPhrase" : "OK"      }    }  ]})
```

Logs showing how the grouping rules are working: the destination has changed from default one (`room1_room`) to grouped one (`new_grouped_dest`) while the FIWARE service path remains the same (i.e. the grouped one is the same than the notified one):

```
time=2016-09-13T13:13:22.608UTC | lvl=INFO | corr=682d8ee0-5f33-4df0-8cdf-5240522411de | trans=682d8ee0-5f33-4df0-8cdf-5240522411de | srv=frbtest | subsrv=/anysubservice | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSICKANSink[420] : [ckan-sink] Persisting data at OrionCKANSink (orgName=frbtest, pkgName=frbtest_anysubservice, resName=new_grouped_dest, data={"recvTimeTs": "1473772380","recvTime": "2016-09-13T13:13:00.481Z","fiwareServicePath": "/anysubservice","entityId": "Room1","entityType": "Room","attrName": "temperature","attrType": "centigrade","attrValue": "26.5"})
time=2016-09-13T13:13:25.700UTC | lvl=INFO | corr=682d8ee0-5f33-4df0-8cdf-5240522411de | trans=682d8ee0-5f33-4df0-8cdf-5240522411de | srv=frbtest | subsrv=/anysubservice | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[429] : Finishing internal transaction (682d8ee0-5f33-4df0-8cdf-5240522411de)
```

Regarding your suggestion about missing fields, it must be said Cygnus parses the grouping rules, warning about any missing field and discarding the rule. For instance, if using the following grouping rules (the field `fiware_service_path` is missing):

```
{
    "grouping_rules": [
        {
            "id": 1,
            "fields": [
                "entityType"
            ],
            "regex": "Room",
            "destination": "new_grouped_dest"
        }
      ]
}
```

Then the following message is traced:

```
time=2016-09-13T13:22:33.009UTC | lvl=INFO | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.interceptors.CygnusGroupingRules[53] : Grouping rules read: {    "grouping_rules": [        {            "id": 1,            "fields": [                "entityType"            ],            "regex": "Room",            "destination": "new_grouped_dest"        }      ]}
time=2016-09-13T13:22:33.075UTC | lvl=INFO | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.interceptors.CygnusGroupingRules[65] : Grouping rules syntax is OK
time=2016-09-13T13:22:33.093UTC | lvl=WARN | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.interceptors.CygnusGroupingRules[71] : Grouping rules discarded due to missing or empty values
```

**Comment by rianwouters** [comment]
Hi Francesco,
thanks for your answer.
You also see that the grouped service path uses "/anysubservice", caused by "fiware_service_path": "/anysubservice"  in the grouping rules.
So suppose I have 10 entity types that I want to group by type similar as you do in your example,and they come in 10 different service paths.
How can I group them by destination with their original service path?
Rethinking this, it may not only be a problem of the Grouping interceptor, but also a problem of the specific sink.
For example, I believe the CKAN sink uses the concatenation of the service name + grouped service path as CKAN package name
AFAIKS that makes it impossible to create a package per service path without creating a rule for each entity type/service path combination.
100 in this example
do you agree?


Rian
Date: Tue, 13 Sep 2016 06:24:25 -0700

**Comment by frbattid** [comment]
This was fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/1286, when `getServicePathForData()` and `getServicePathForNaming()` were added to `NGSIEvent`.

Such a PR must be considered together with these other PRs: https://github.com/telefonicaid/fiware-cygnus/pull/1281, https://github.com/telefonicaid/fiware-cygnus/pull/1296, https://github.com/telefonicaid/fiware-cygnus/pull/1297, https://github.com/telefonicaid/fiware-cygnus/pull/1300 and https://github.com/telefonicaid/fiware-cygnus/pull/1301
