### ISSUE TITLE
feature files use step definitions 'verify if ...'

### ISSUE THREAD

**Issue by rianwouters** [telefonicaid/fiware-cygnus#1146]
for example 'verify if cygnus is installed correctly'
should e: 'cygnus is installed correctly'

**Comment by iariasleon** [comment]
@rianwouters, both texts are correct, the first defines the action of the step, in the second case, the action is assumed. Remember, it is Gherkin language. The steps should be written using **natural language - ideally by the non-technical business participants** in the software project. Feature files serve two purposes – documentation and automated tests.

**Comment by rianwouters** [comment]
It's not that important but I disagree ;-)
The fact that it is a test file already defines that it is a verification.
