### ISSUE TITLE
[cygnus-ngsi][NGSIMongoSink] Optionally save metadata when configured

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1156]
As requested by a FIWARE user: add a new parameter about saving or not the notified attribute metadata (currently, it is not saved at all by defaut).

**Comment by sabrine2020** [comment]
Hello,
any updates on this? any plan to integrate this feature in cygnus? Thanks!

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1416
