### ISSUE TITLE
[cygnus-ngsi][NGSIPostgreSQLSink] Add cache regarding already created elements

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1171]
Currently we have this `persistAggregation` method:

```
    private void persistAggregation(PostgreSQLAggregator aggregator) throws Exception {
        String typedFieldNames = aggregator.getTypedFieldNames();
        String fieldNames = aggregator.getFieldNames();
        String fieldValues = aggregator.getAggregation();
        String schemaName = aggregator.getSchemaName(enableLowercase);
        String tableName = aggregator.getTableName(enableLowercase);

        LOGGER.info("[" + this.getName() + "] Persisting data at OrionPostgreSQLSink. Schema ("
                + schemaName + "), Table (" + tableName + "), Fields (" + fieldNames + "), Values ("
                + fieldValues + ")");

        // creating the database and the table has only sense if working in row mode, in column node
        // everything must be provisioned in advance
        if (aggregator instanceof RowAggregator) {
            persistenceBackend.createSchema(schemaName);
            persistenceBackend.createTable(schemaName, tableName, typedFieldNames);
        } // if

        persistenceBackend.insertContextData(schemaName, tableName, fieldNames, fieldValues);
    } // persistAggregation
```

As can be seen, the schema and the table are always created (if they already exist, simply they are not created). Those operations, executed for every upsert, tend to consume a lot of CPU along time. They could be easily be avoided if a cache tell us the schema and/or the table are already created. Of course, when not found in the cache, the `createSchema` and `createTable` must be executed.

Please observe the same table name may exist within two or more schemas. Thus, the cache must be some kind of hash map linking a schema name with a list of tables within it.

Catching could also be enabled/disabled by means of a parameter:

    cygnus-ngsi.sinks.<sink-name>.cache = true | false

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1186

**Comment by frbattid** [comment]
Bugs fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/1197
