### ISSUE TITLE
[cygnus-ngsi][docker] Add NGSIHDFSSink configuration

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1172]
It is about updating the default `agent.conf` file with default configuration for HDFS.

The documentation must be updated in order to describe how to give specific values to the certain default values such as `hdfs_host`, `hdfs_username`, etc. (this should be the same than the MySQL example, already given in the documentation).

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1236
