### ISSUE TITLE
[cygnus-ngsi][docker] Add NGSICKANSink configuration

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1193]
It is about updating the default `agent.conf` file with default configuration for CKAN.

The documentation must be updated in order to describe how to give specific values to the certain default values such as `ckan_host`, `api_key`, etc. (this should be the same than the MySQL example ¡, already given in the documentation).

**Comment by pcoello25** [comment]
In docker configuration there are a step where the branch is changed to `master`. The new structure of the repo disallow that step because `develop` doesn't exist: 
```
Already on branch 'master'
```
It will be modified in another related issue about changes in docker.

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1205
