### ISSUE TITLE
[cygnus-ngsi][docker] Update default agent.conf with latest parameters

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1194]
Parameters such as `enable_encoding` or `enable_name_mappings` (among others) have been added to sinks configuration. Thus, the default `agent.con` file used in cygnus-ngsi docker must be updated.

It fact, if not configured they are going to take default values. Nevertheless, I would like these default values appear explicitily in the configuration, for completeness purposes.

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1196
