### ISSUE TITLE
[cygnus-ngsi][docker] Fix "Automated build stuck by file lock denied from seccomp" error

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-cygnus#1208]
[cygnus] Automated build stuck by file lock denied from seccomp

**Comment by cesarjorgemartinez** [comment]
We have to forget the version of java 1.6.0 and begin to use 1.7.0

**Comment by frbattid** [comment]
The fix must be applied both to master and release/1.4.0 branches.

**Comment by cesarjorgemartinez** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/1224

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1224 (master branch)
