### ISSUE TITLE
[cygnus-common] Add traces regarding which .jar files have been loaded

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1210]
The piece of code where to put this kind of tracing is `CygnusApplication`.

It is about adding a line like the following one for each external library used in cygnus-common:

```
URL myClassURL = PoolingClientConnectionManager.class.getProtectionDomain().getCodeSource().getLocation();
LOGGER.debug("Loading httpclient from " + myClassURL.toExternalForm());
```

The idea is to locate a class that must be loaded from a certain library and use it for retrieving the .jar file where such library is included.

The traces level will be `DEBUG`.

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1262
