### ISSUE TITLE
[doc][cygnus-common] Add path creations and permissions

### ISSUE THREAD

**Issue by pcoello25** [telefonicaid/fiware-cygnus#1212]
Following `installation_and_administration_guide/install_from_sources.md` i've found some improvements that must be specificied: 
* In section ' installing `cygnus-common`' the following line:
```
$ APACHE_MAVEN_HOME/bin/mvn clean compile exec:exec assembly:single
```
must be replaced with the correct path:
```
$ APACHE_FLUME_HOME/bin/mvn clean compile exec:exec assembly:single
```
* It must be specified the creation of the path /var/log/cygnus
* Besides, permissions to these paths are important. We must include the `chown` process for the user `cygnus` and the path previously stated.

**Comment by frbattid** [comment]
Just remember the step about adding the `cygnus` user :)

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1218
