### ISSUE TITLE
[cygnus-common][API,GUI] Add IPv6 support

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1261]
Currently, the host part in the binding of both API and GUI endpoints is hardcoded to `0.0.0.0`. This should be configurable by using a command line option. For instance, if `-6` option is passed, then the API and the GUI bind their ports to `::0`; if such an option is not passed, then the API and the GUI bind their ports to `0.0.0.0`.

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1276
