### ISSUE TITLE
[cygnus-ngsi][NGSIHDFSSink] Error about missing OAuth2 token should be WARNING instead ERROR

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1330]
```
time=2016-11-30T15:27:48.693Z | lvl=ERROR | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=configure | msg=com.telefonica.iot.cygnus.sinks.NGSIHDFSSink[284] : [hdfs-sink] No OAuth2 token provided. Cygnus can continue, but HDFS sink may not properly work if WebHDFS service is protected with such an authentication and authorization mechanism!
```

**Comment by frbattid** [comment]
Implemented in PR time=2016-12-01T07:56:15.902UTC | lvl=WARN | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=configure | msg=com.telefonica.iot.cygnus.sinks.NGSIHDFSSink[284] : [hdfs-sink] No OAuth2 token provided. Cygnus can continue, but HDFS sink may not properly work if WebHDFS service is protected with such an authentication and authorization mechanism!
