### ISSUE TITLE
[cygnus][style] FI-WARE -> FIWARE in license headers

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#1369]
Some files (at least cygnus-common/src/main/java/com/telefonica/iot/cygnus/management/NameMappingsHandlers.java ) use the following in license headers:

```
* This file is part of fiware-cygnus (FI-WARE project).
```

It should be changed to 

```
* This file is part of fiware-cygnus (FIWARE project).
```

Probably it would impact in many files, but with the typical "Replace all in files" in conventional IDEs it should be easy to do.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1375
