### ISSUE TITLE
[cygnus-ngsi][NGSISink] File channels are not working

### ISSUE THREAD

**Issue by taliaga** [telefonicaid/fiware-cygnus#1419]
I'm trying to setup a simple cygnus-ngsi scenario with a FileChannel, using the latest docker image of cygnus and testing with the notification.sh script presented in the [Quick Start guide](http://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/quick_start_guide/index.html). 

I can confirm the env setup is fine because using the same config file, but with a MemoryChannel, I can see the notification persisted in MySQL. Regarding cygnus env variables, I'm just redefining the MYSQL host,user,pass variables. All the rest are the defaults defined in the official Dockerfile.

The agent configuration I'm using can be seen [here.](https://gist.githubusercontent.com/taliaga/26ebe4b540befa32f24a8f847de4c72b/raw/a0226f4f33fd739b9e8e9ad1b7b2d84c84219a0a/cygnus_agent.conf) And based on [this doc](https://flume.apache.org/FlumeUserGuide.html#file-channel) (I couldn't find any example in cygnus) I thought that, at least regarding the channel configuration, it'd be enough, wouldn't it?

Relevant extract from console with DEBUG logging:

    time=2017-03-23T13:01:34.768Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[367] : [NGSIRestHandler] NGSI events put in the channel, ids=1014408273
    time=2017-03-23T13:01:34.769Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=intercept | msg=com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor[84] : [gi] Event intercepted, id=1014408273
    time=2017-03-23T13:01:34.770Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=intercept | msg=com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor[117] : [gi] Adding flume event header (notified-entity: Room1_Room)
    time=2017-03-23T13:01:34.770Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=intercept | msg=com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor[120] : [gi] Adding flume event header (grouped-entity: Room1_Room)
    time=2017-03-23T13:01:34.770Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=intercept | msg=com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor[123] : [gi] Adding flume event header (grouped-servicepath: /)
    time=2017-03-23T13:01:34.771Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=intercept | msg=com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor[127] : [gi] Event put in the channel, id=1014408273
    time=2017-03-23T13:01:34.799Z | lvl=DEBUG | corr=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | trans=4b32a8d0-b9fc-45b8-95e8-7d00eafda4b4 | srv=default | subsrv=/ | comp=cygnus-ngsi | op=preallocate | msg=org.apache.flume.channel.file.LogFile$Writer[344] : Preallocating at position 0
    time=2017-03-23T13:01:37.086Z | lvl=ERROR | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=run | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
    java.lang.ClassCastException: org.apache.flume.channel.file.FlumeEvent cannot be cast to com.telefonica.iot.cygnus.interceptors.NGSIEvent
	at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:489)
	at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:368)
	at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
	at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
	at java.lang.Thread.run(Thread.java:745)

After that, I get multiple times a message like below, though it looks like a consequence of the ClassCastException above:

    time=2017-03-23T13:39:24.651Z | lvl=ERROR | corr= | trans= | srv= | subsrv= | comp=cygnus-ngsi | op=run | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
    java.lang.IllegalStateException: begin() called when transaction is OPEN!
	at com.google.common.base.Preconditions.checkState(Preconditions.java:145)
	at org.apache.flume.channel.BasicTransactionSemantics.begin(BasicTransactionSemantics.java:131)
	at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:476)
	at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:368)
	at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
	at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
	at java.lang.Thread.run(Thread.java:745)

Just in case, tried with a different sink (the test sink), but I got the same problem.
 
May I be missing something earlier in the configuration?
Thanks,

**Comment by frbattid** [comment]
I suspect this is because `NGSIEvent` does not implement the `Writable` interface, which is indeed implemented by file channel's specific `org.apache.flume.channel.file.FlumeEvent`. Thus, casting does not work. Memory channel does not show this problem since it works with any `org.apache.flume.Event`.

I'll do some tests in order to know if this has an easy solution or not (i.e. implementing methods from `Writable` interface, or something else is required).

**Comment by taliaga** [comment]
Thanks, that'll be helpful!

**Comment by frbattid** [comment]
Finally, `NGSIEvent` cannot implement `org.apache.flume.channel.file.Writable` interface since it is private and thus, it is not available in Flume API.

The solution will be to modify `NGSISink` (base processing class for all sinks) in order to check if the event taken from the channel (its type is `Event`, the base class for all event classess) can be directly casted to `NGSIEvent` (this is because the channel is based in memory, and thus the event was originally created by the source as a `NGSIEvent`); or if the `NGSIEvent` has to be re-created from raw bytes (this is because the `NGSIEvent` originally created at the source has been serialized in a file and it has "lost" its type, only headers and body can be retrieved).

Such a solution requires the raw bytes added to the event body contain both the original notified context element and the mapped context element. Since the mapped context element is calculated by `NGSINameMappingsInterceptor`, the interception method has to be modified in order to append the mapped context element bytes to the body.

**Comment by frbattid** [comment]
@taliaga , PR https://github.com/telefonicaid/fiware-cygnus/pull/1432 fix this issue. Maybe you could test it before it is merged by @fgalan :)

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/1432

**Comment by taliaga** [comment]
Thanks @frbattid!

I tested it locally and that seems to have fixed the problem. I can see logs like below:

    cygnus-common_1  | time=2017-04-20T12:51:29.043Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[490] : Batch accumulation time reached, the batch will be processed as it is
    cygnus-common_1  | time=2017-04-20T12:51:29.049Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[529] : Re-creating NGSI event from raw bytes in file channel, original context element: {"id":"Room1","type":"Room","isPattern":"false","attributes":[{"name":"temperature","type":"float","value":"26.5","metadatas":[]}]}, mapped context element: null
    cygnus-common_1  | time=2017-04-20T12:51:29.051Z | lvl=DEBUG | corr=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | trans=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | srv=default | subsrv=/ | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[554] : Batch completed
    cygnus-common_1  | time=2017-04-20T12:51:29.051Z | lvl=DEBUG | corr=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | trans=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | srv=default | subsrv=/ | comp=cygnus-ngsi | op=persistBatch | msg=com.telefonica.iot.cygnus.sinks.NGSITestSink[76] : [test-sink] Processing sub-batch regarding the default_/_Room1_Room destination
    cygnus-common_1  | time=2017-04-20T12:51:29.053Z | lvl=INFO | corr=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | trans=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | srv=default | subsrv=/ | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSITestSink[181] : [test-sink] Persisting data at NGSITestSink. Data (Processing event={Processing headers={timestamp=1492692686249,fiware-correlator=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d,fiware-service=default,grouped-servicepath=/,fiware-servicepath=/,transaction-id=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d,grouped-entity=Room1_Room,notified-entity=Room1_Room}, Processing context element={id=Room1, type=Room}, Processing attribute={name=temperature, type=float, value="26.5", metadata=[]}})
    cygnus-common_1  | time=2017-04-20T12:51:29.054Z | lvl=INFO | corr=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | trans=c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d | srv=default | subsrv=/ | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[590] : Finishing internal transaction (c71b0fa6-8b6f-4df2-bdf5-a74c76f2447d)

Regarding the fork, that's no needed, note that with git you can do something quick like:
    git fetch https://github.com/frbattid/fiware-cygnus.git bug/1419_add_support_for_file_channels
    git checkout -b localtest FETCH_HEAD

Thanks!
