### ISSUE TITLE
[cygnus-ngsi][NGSIDynamoDBSink] Southeast regions are bad coded

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#1448]
As described in [this](https://stackoverflow.com/questions/44962501/fiware-cygnus-configuration-to-postgresql-dynamodb-and-ckan) stackoverflow issue, the southeast regions are bad coded.

In more details, instead of using `APSOUTHEAST1` and `APSOUTHEAST2`, `APSHOUTEAST1` and `APSHOUTEAST2` have been coded.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1499
