### ISSUE TITLE
[cygnus-ngsi][NGSINameMappingsInterceptor] Allow regular expression replacement for EntityIds

### ISSUE THREAD

**Issue by dmartinezgomez** [telefonicaid/fiware-cygnus#1456]
The current behavior is that only RegEx Matching is allowed with a constant replacement. 
It will be nice to allow the use of reular expressions also in replacement.

E.g.  
        **Entities like**: _"Air_0001","Air_0002","Air_0003","Air_0004",..._
	**should be mapped like**: _"AirQualityObserved0001",..._
			
```javascript
{
  "serviceMappings": [{
    "originalService": "service",
    "newService": "new_service",
    "servicePathMappings": [{
      "originalServicePath": "/subservice",
      "newServicePath": "/new_subservice",
      "entityMappings": [{
        "originalEntityType": "entity_type",
        "originalEntityId": "(Air_)([0-9]*)",
        "newEntityId": "AirQualityObserved$2",
        "attributeMappings": []
      }]
    }]
  }]
}
```

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-cygnus/pull/1457
