### ISSUE TITLE
Readthedocs documentation not updated

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1460]
The documentation in http://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/quick_start_guide/index.html is not updated.

At least, configuration file is not correct for latests version.

**Comment by jason-fox** [comment]
@fgalan - I believe this has now been fixed by #1497 - could you check and close this if necessary.

**Comment by fgalan** [comment]
Yes, it seems so. Closing.
