### ISSUE TITLE
"Destination" feature in Name Mappings

### ISSUE THREAD

**Issue by HilariousGil** [telefonicaid/fiware-cygnus#1461]
### Current Behaviour

I have been using the [Grouping Rules](http://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/installation_and_administration_guide/grouping_rules/index.html) for helping persisting data in CKAN and be able to select which resource I want my data to be in without changing the actual data itself using the "destination" field.

I see now that this is deprecated and eventually will be removed, and I would like to know if there is a was to keep this functionality of redirecting the destination of the data without changing the data itself. 

I looked into the of the [Name Mappings](http://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/installation_and_administration_guide/name_mappings/index.html) and it seems like there is a chance to manipulate the fields Fiware-Service and Fiware-Service-Path, but then they will be inserted as the new values and not the original ones.

### Desired Behaviour

Using the Name Mapping be able to send a record with data {"entityID":"aaa", entityType":"bbb"} to a different resource other than one named "aaa_bbb".

Is this anything that is planned or is this functionality already in place and I just missed something?

Thanks

**Comment by frbattid** [comment]
You can do the trick by playing a bit with the values of `newEntityId` and `newEntityType`. For instance, if you want your entities to be saved in a single resource named `my_new_and_single_resource` then set `newEntityName` to `my_new_and` and `newEntityType` to `single_resource`. Since entity ID and type are always concatenated, then you'll have the desired name at the end.

**Comment by HilariousGil** [comment]
Thanks for the quick reply @frbattid .
Yes, you would be the desired resource name. 
But the data that would be stored there, would contain the `newEntityName `and `newEntityType` values intead of the original ones. 
My question was if there was a way to keep the original values on the actual stored data but be able to manipulate the destination.
Which is what I currently achieve with the Grouping Rules.

**Comment by frbattid** [comment]
> Yes, you would have the desired resource name, but the data stored there, would contain the newEntityNameand newEntityType values intead of the original ones.
My question was if there was a way to keep the original values on the actual stored data but be able to manipulate the destination.

NameMappings only change the original IDs, types, names, etc. for resource naming purposes. The original data is maintained within the resource.

**Comment by HilariousGil** [comment]
Thank you very much @frbattid .
I was assuming that the data stored would include the new values.
