### ISSUE TITLE
Kafka topics are always converted to lowercase

### ISSUE THREAD

**Issue by dmabtrg** [telefonicaid/fiware-cygnus#1468]
Hi,

The `enable_lowercase` option for `NGSIKafkaSink` seems to be ignored.  Either explicitly setting it to `false`:
``` text
cygnus-ngsi.sinks.kafka-sink.enable_lowercase = false
```
or not setting it at all so that the default value is used (as noted in the [documentation](https://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/flume_extensions_catalogue/ngsi_kafka_sink/index.html#section2.1)) yields the same result: the topic is always converted to lowercase.  Looking at the code, it seems this option is not used for this backend.

Is this the intended behaviour?  If so, then the [documentation](https://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/flume_extensions_catalogue/ngsi_kafka_sink/index.html#section2.1) needs to be updated, else I think this is a bug.

Thanks.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1477
