### ISSUE TITLE
[cygnus-ngsi][KeystoneUtils] Create new Auth functionality

### ISSUE THREAD

**Issue by pmo-sdr** [telefonicaid/fiware-cygnus#1471]
Create **KeystoneUtils** covering Keystone Auth capabilities.

The idea is to implement the folowing functionalities:

- Token based Authentication

- Allow both, service and servicePath level authentications

- Avoid recurrent auth logins using token cache

- Manage token expiration

**Comment by AlvaroVega** [comment]
I'm not sure if keystone could be a backend of cygnus: May be your intention ins create a backed for ContextBroker which needs keystone auth. In that case you should create a contesbrokerbackend and these features are just utilities for that new backend, but not a new backend.

**Comment by dmartinezgomez** [comment]
May I was missunderstanding, but I can´t see the difference between this backend and httpbackend, both are "utilitie backends" that can be reused in future functionalities. The idea was to mantain Cygnus modular.

**Comment by AlvaroVega** [comment]
I believe that the idea is a cygnus backend is provide support for a new sink:
https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/backends_catalogue/introduction.md

I see the point in a new sink that invokes an HTTP when a new data arrives to cygnus, but I don't see the point to create a new sink which get a token when a new data a arrives to cygnus.

**Comment by fgalan** [comment]
Does PR https://github.com/telefonicaid/fiware-cygnus/pull/1472 completes this issue? Is there any pending @pmo-sdr and @AlvaroVega or should it be closed?

**Comment by fgalan** [comment]
+ @dmartinezgomez

**Comment by pmo-sdr** [comment]
Issue compelted.
