### ISSUE TITLE
HIVE persistence. Endpoint not loaded from config file

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1476]
the following config param should be used to set the HIVE ip:

cygnusagent.sinks.hdfs-sink-hdfs.hive_host = 10.0.0.2

However, cygnus always uses the localhost ip address. This is the log file

time=2018-04-27T09:03:59.019Z | lvl=ERROR | corr=e7529d5a-49f9-11e8-a1b4-fa163e734aab | trans=e50ec5a2-312e-404b-8317-db1a4580b142 | srv=sc_vlci | subsrv=/MedioAmbiente | op=doCreateTable | comp=Cygnus | msg=com.telefonica.iot.cygnus.backends.hive.HiveBackendImpl[105] : Runtime error (The Hive table cannot be created. Hive query='create external table if not exists ...'. Details=Could not open connection to jdbc:hive2://localhost:10000/default: java.net.ConnectException: Connection refused (Connection refused))
time=2018-04-27T09:03:59.019Z | lvl=WARN | corr=e7529d5a-49f9-11e8-a1b4-fa163e734aab | trans=e50ec5a2-312e-404b-8317-db1a4580b142 | srv=sc_vlci | subsrv=/MedioAmbiente | op=provisionHiveTable | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSIHDFSSink[1167] : The HiveQL external table could not be created, but Cygnus can continue working... Check your Hive/Shark installation

**Comment by AlvaroVega** [comment]
According with template: https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/conf/agent_ngsi.conf.template#L109
```
cygnusagent.sinks.hdfs-sink.hive.host = 10.0.0.2
```
not hdfs-sink-hdfs

**Comment by AlvaroVega** [comment]
Maybe is due to way of get hive.XXX args:
```
context.getString("hive.host", "localhost")
```

**Comment by AlvaroVega** [comment]
You should try with ```hive.host``` instead of ```hive_host```

**Comment by AlvaroVega** [comment]
There are some references here (ansible):
https://pdihub.hi.inet/ep/iot_ansible/blob/ddf514926140f5202be3d787ae3dbebdfcc01817/group_vars/all/hadoop.yml#L21
that also use ```hive_host``` instead of ```hive.port```.
Probably are the source of this issue.

**Comment by manucarrace** [comment]
Fixed
