### ISSUE TITLE
DOCKER: Enable sinks and channels depending on ENV vars

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1482]
Current behavior: some sinks and channels were activated even if no proper configuration was provided (mongo, sth, mysql, ckan, hdfs).
Desired behavior: only sinks in ENV vars will be enabled in cygnus agent configuration

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1481
