### ISSUE TITLE
[doc] Link to the cygnus-common docker installation guidelines page is not valid

### ISSUE THREAD

**Issue by omerozdemiratos** [telefonicaid/fiware-cygnus#1511]
The [install cygnus-common via docker instructions page link](https://github.com/telefonicaid/fiware-cygnus/tree/master/docker/cygnus-common) page is not working.

**Comment by vjain641** [comment]
[This](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/installation_and_administration_guide/install_with_docker.md) seems to be the correct link.

**Comment by fgalan** [comment]
It seems it is working and shows:

![imagen](https://user-images.githubusercontent.com/1534240/44775090-0e0c2380-ab75-11e8-97a3-6e122919b5dd.png)

So, I'm afraid I don't understand in which sense it is not working...

**Comment by fgalan** [comment]
Ah ok... I missed that commit :)

Thus, I understand this issue can be closed (tell me if I'm wrong).
