### ISSUE TITLE
[cygnus-ngsi][feature][NGSIElasticsearchSink] create NGSIElasticsearchSink

### ISSUE THREAD

**Issue by nmatsui** [telefonicaid/fiware-cygnus#1516]
I want to use cygnus-ngsi with [Elasticsearch](https://www.elastic.co/products/elasticsearch). So I wrote conceptual implementations like below:

* `com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink`
* `com.telefonica.iot.cygnus.backends.elasticsearch.ElasticsearchBackend`
* `com.telefonica.iot.cygnus.backends.elasticsearch.ElasticsearchBackendImpl`

What do you think about "ElasticsearchSink"? If you are interested in, I will write tests and documents and contribute this.

**Comment by nmatsui** [comment]
https://github.com/tech-sketch/fiware-cygnus/tree/feature/1516_create_elasticsearchsink

**Comment by fgalan** [comment]
So you mean you have extended Cygnus with a new sink to persist data in Elasticsearch. Is my interpretation correct, please?

(Just to check if I'm understanding correctly the scope of the contribution... thx! :)

**Comment by fgalan** [comment]
Implemented in PR #1523
