### ISSUE TITLE
[cygnus-common][feature][CommonUtils] getTimeInstant accepts ISO8601 with offset

### ISSUE THREAD

**Issue by nmatsui** [telefonicaid/fiware-cygnus#1517]
At this time, CommonUtils#getTimeInstant can accept the 3 patterns like below:

* unixtime (Long integer)
* ISO8601 of UTC (yyyy-MM-dd'T'HH:mm:ss'Z' or yyyy-MM-dd'T'HH:mm:ss.SSS'Z')
* SQL timestamp (yyyy-MM-dd HH:mm:ss or yyyy-MM-dd HH:mm:ss.SSS)

But I want to handle ISO8601 with offset like below:

* 2018-01-02T03:04:05+09:00

So I modified CommonUtils#getTimeInstant to be able to accept ISO8601 with offset.
Please check my Pull Request and please accept it if you can.

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1518
