### ISSUE TITLE
Docker installation issues with agent.conf

### ISSUE THREAD

**Issue by IgorDespot** [telefonicaid/fiware-cygnus#1519]
Hi all,

I have questions regarding docker installation of fiware-cygnus:
1. What docker image should i use, i found at least 3 of them(not sure if this affect installation)
2. I have agent.conf on my host, and i was not able to map it to container. So it could be me but is this location where i should map agent.conf? 
I had no problems to map my own grouping_rules.conf but agent.conf i was not able to do it, i run docker images/containers many times never had issue like this.

> /opt/apache-flume/conf/agent.conf

This is main reason of my problems because file inside of docker-container simply wont change, even if i try to change it manual moment i restart container it return to original state.
3. Do i need to configure cygnu_instance.conf, very confusing for me is fact that in it mention agent.conf but on different location, is that location i should map my agent.conf or not.

> CONFIG_FOLDER=/usr/cygnus/conf
>CONFIG_FILE=/usr/cygnus/conf/agent.conf

These are main questions/issues i have, if some was able to install cygnus with docker and with personal agent.conf or know where i should look and send me in some direction would help a lot.

Thanks.

**Comment by fgalan** [comment]
Given it is more about doubts and configuration (rather than issues on the component) maybe it is better to post your questions using https://stackoverflow.com/questions. Please, use "fiware-cygnus" label.

Once done, please add the link in this issue as a comment, then close the issue. Thanks!

**Comment by IgorDespot** [comment]
Hey fgalan, thanks for replaying as always. 
Here is question on [stack](https://stackoverflow.com/questions/52420611/fiware-cygnus-docker-installation).
Also before i open question regarding specific issues, if some want it can check it out [here](https://stackoverflow.com/questions/52314455/cannot-map-agent-conf-using-cygnus-docker-installation?noredirect=1#comment91717333_52314455).
