### ISSUE TITLE
[cygnus-ngsi][NGSINameMappingsInterceptor] Update NGSINameMappingsInterceptor so that it doesn't take the first configuration in the namemapping

### ISSUE THREAD

**Issue by pmo-sdr** [telefonicaid/fiware-cygnus#1535]
We think that the namemapping need a little changed. Because we need to send two type entity of same servicePath and diferent type entity to two different servicePath.

At the moment, the  configuration of namemapping takes the first servicepath namemapping configuration which checks only service and servicePath. And the both entity send to the first configuration. And it doesn't check other configuration.

We think that it need to change, so that the namemapping checks sevice, subervice and (type of entity and id entity) of EntityMapping.

**Comment by fgalan** [comment]
Fixed by PR #1536

**Comment by pmo-sdr** [comment]
Done
