### ISSUE TITLE
[Name mappings] NewEntityId duplicated when no NewEntityType is specified

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1547]
Having the following name_mapping file:

{
  "serviceMappings": [
    {
      "originalService": "city012",
      "newService": "sc_city012",
      "servicePathMappings": [
        {
          "originalServicePath": "/electricidad",
          "newServicePath": "/externalIndicator",
          "entityMappings": [
            {
              "originalEntityType": "luminaria",
              "newEntityType": "",
              "originalEntityId": ".*",
              "newEntityId": "a",
              "attributeMappings": []
            }
          ]
        }
      ]
    }
  ]
}

Cygnus (mysql) is writing to table "sc_city012.externalIndicator_aa". It should be "sc_city012.externalIndicator_a".

The intention of this configuration is to have the same table name for every entity of the same type (e.g. luminaria)

**Comment by dmartinezgomez** [comment]
Hello @manucarrace,

It seems to be a problem with your regex expression. 
you need:
```
"originalEntityId": "^.*",
```
instead of:
```
"originalEntityId": ".*",
```
Regex replacement works as expected, you can test it in https://regex101.com/

Regards.

**Comment by dmartinezgomez** [comment]
> The intention of this configuration is to have the same table name for every entity of the same type (e.g. luminaria)

Sorry, I didn't read this part.

You don't need to use "mapping tricks" to achieve this.  If you are using a Mysql sink, take a look to **data_model** property in your agent configuration file.

```
<cygnusAgent>.sinks.mysql-sink-mysql.table_type = table-by-destination
<cygnusAgent>.sinks.mysql-sink-mysql.data_model = dm-by-service-path

```

**Comment by AlvaroVega** [comment]
In that case, for your purpose, you should use a name mapping like this:
```
{
  "serviceMappings": [{
         "originalService": "city012",
         "newService": "sc_city012",
         "servicePathMappings": [{
                   "originalServicePath": "/electricidad",
                   "newServicePath": "/newexternalindicator",
                   "entityMappings": [{
                          "originalEntityType": "luminaria",
                          "newEntityType": "luminaria",
                          "originalEntityId": ".+",
                          "newEntityId": "a",
                          "attributeMappings": []
                     }
                    ]
             }, 
               ]
           }
          ]
}
```
