### ISSUE TITLE
Wrong mirror webhook config.

### ISSUE THREAD

**Issue by caa06d9c** [telefonicaid/fiware-cygnus#1560]
Please, change the mirror webhook config as described [here](https://fiware-requirements.readthedocs.io/en/latest/repo_webhook/index.html)

**Comment by fgalan** [comment]
Update so now it is:

![imagen](https://user-images.githubusercontent.com/1534240/49788360-6f719000-fd29-11e8-9c3e-b94d20f676cc.png)

Please check if now it is working fine and close the issue in that case. Thx!

**Comment by caa06d9c** [comment]
It works. Thanks!
