### ISSUE TITLE
[MUST] Install Section missing

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/fiware-cygnus#1576]
Installation instructions are missing from the main `README`

- There is no Install entry in the ToC. 
- There is no link within the main `README` to guide users to the installation
- Alternatively there are no simple instructions within the `README` itself

- MUST requirement from the TSC

**Comment by Chandradeep-NEC** [comment]
@jason
Please assign this issue to us.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1700
