### ISSUE TITLE
How to use parameters data_expiration and collections_size

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1586]
A thorough investigation on theses parameters should be done. Several questions have been raised:

- Do these parameters apply to already created collections?
- Why STHSink has only data_expiration param and no collections_size param?
- Do these parameters apply to every collection?
- Can be the truncation parameters specific for each collection/subservice?

**Comment by AlvaroVega** [comment]
```
Why STHSink has only data_expiration param and no collections_size param?
```
Boot data_expiration and collection_size are used in mongo_sink:
- https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L119
- https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMongoSink.java#L418

**Comment by AlvaroVega** [comment]
```
Do these parameters apply to already created collections?
```
It seem's that each agregation tries to create and ensure that values:
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMongoSink.java#L404
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L102

**Comment by manucarrace** [comment]
Noted and understood
