### ISSUE TITLE
Howto configure Cygnus Log4J to log files rotated using gzip

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-cygnus#1592]
Howto configure Cygnus Log4J to log files rotated using gzip

**Comment by cesarjorgemartinez** [comment]
This may require upgrade the log4j version?:
http://logging.apache.org/log4j/2.x/manual/appenders.html#RollingFileAppender

**Comment by fgalan** [comment]
Currently (https://github.com/telefonicaid/fiware-cygnus/search?l=Maven+POM&q=log4j) Cygnus is using log4j version 1.2.17. According to the link @cesarjorgemartinez provides:

> A RollingFileAppender requires a TriggeringPolicy and a RolloverStrategy. The triggering policy determines if a rollover should be performed while the RolloverStrategy defines how the rollover should be done. If no RolloverStrategy is configured, RollingFileAppender will use the DefaultRolloverStrategy. Since log4j-2.5, a custom delete action can be configured in the DefaultRolloverStrategy to run at rollover. Since 2.8 if no file name is configured then DirectWriteRolloverStrategy will be used instead of DefaultRolloverStrategy. Since log4j-2.9, a custom POSIX file attribute view action can be configured in the DefaultRolloverStrategy to run at rollover, if not defined, inherited POSIX file attribute view from the RollingFileAppender will be applied. 

Thus, we could try upgrading to 2.9.

However, it seems to be a big change between 1.x and 2.x. Not sure if the current way of configuring log4j (based in a key=values properties text file) will work (the link shows fragments in XML).

**Comment by fgalan** [comment]
PR #1593 is a naïve attemp of upgrading this... but it seems it is not so easy as we though :(

> [ERROR] Failed to execute goal on project cygnus-ngsi: Could not resolve dependencies for project com.telefonica.iot:cygnus-ngsi:jar:1.10.0_SNAPSHOT: The following artifacts could not be resolved: log4j:log4j:jar:2.11.2, com.telefonica.iot:cygnus-common:jar:1.10.0_SNAPSHOT: Failure to find log4j:log4j:jar:2.11.2 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

This reference provides additional documentation on how to migrate: https://logging.apache.org/log4j/2.x/manual/migration.html. Code changes are needed.

**Comment by fgalan** [comment]
PR #2212
