### ISSUE TITLE
[cygnus-common][MySQLBackend] Missed to Close connections on errors.

### ISSUE THREAD

**Issue by pmo-sdr** [telefonicaid/fiware-cygnus#1597]
MySQL operations miss to close connection and statement objects when an error occurs.

https://github.com/telefonicaid/fiware-cygnus/blob/c726d2d5f7903fb862c2e800c600eab4aba76dc0/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mysql/MySQLBackendImpl.java#L155-L163

Resultset objects also have to be clossed.

https://github.com/telefonicaid/fiware-cygnus/blob/c726d2d5f7903fb862c2e800c600eab4aba76dc0/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mysql/MySQLBackendImpl.java#L189

**Comment by fgalan** [comment]
I undertand this issue is fixed by https://github.com/telefonicaid/fiware-cygnus/pull/1600. Should this issue be closed after merging that PR?

**Comment by manucarrace** [comment]
Sure this issue has been fixed? Does it need a finally statement?

**Comment by fgalan** [comment]
> Sure this issue has been fixed? Does it need a finally statement?

I understand you mean a `finally` statement in the code in the PR #1600 

(Maybe obvious, but just to clarify ;)
