### ISSUE TITLE
[cygnus-common][MySQLBackend] Implement Connection Pooling

### ISSUE THREAD

**Issue by pmo-sdr** [telefonicaid/fiware-cygnus#1598]
MySQL Backend should implement connection pooling techniques to reduce connection creation time and also to improve resource usage.

Related Issues to be resolved along with this new feature:
- [cygnus-common][MySQLBackend] Missed to Close connections on errors.#1597 
- Data not persisted after "Communications link failure The last packet sent successfully to the server was 0 milliseconds ago" #1584

**Comment by fgalan** [comment]
I undertand this issue is fixed by https://github.com/telefonicaid/fiware-cygnus/pull/1600. Should this issue be closed after merging that PR?
