### ISSUE TITLE
"Random" Error: Thread found not alive, exiting Cygnus

### ISSUE THREAD

**Issue by pmo-sdr** [telefonicaid/fiware-cygnus#1616]
Cygnus closes itself in a random manner.

Error: 
```
time=2019-04-01T08:15:57.899Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnusagent | op=run | msg=com.telefonica.iot.cygnus.nodes.CygnusApplication$YAFS[471] : Thread found not alive, exiting Cygnus. ID=27, name=qtp586434923-27
```
Looks like CygnusApplication's **run()** method, fail to filter Jetty thread when validating.
It looks for "@qtp" thread names but names like "qtp586434923-27" arrived.

https://github.com/telefonicaid/fiware-cygnus/blob/dab19e3029f8c8f2a0a3f7c88e84f120150abd7b/cygnus-common/src/main/java/com/telefonica/iot/cygnus/nodes/CygnusApplication.java#L465-L475

A quick fix would be:
```
!t.getName().contains("qtp")
```
perhaps startsWith instead of contains.

Would this change of thread names be related to recent Apache Flume update?

**Comment by fgalan** [comment]
> Would this change of thread names be related to recent Apache Flume update?

We haven't traced that but it could be.

I'd suggest to apply the fix in a PR, merge it and check e2e regression. Could you manage with the PR @pmo-sdr , pls? Thanks!

**Comment by pmo-sdr** [comment]
We are running tests right now.. but in fact that it is quite "random" for us, (because we are not familiar with Jetty's guts) it will take a while confirming the fix.

Then we will manage the PR.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1623

**Comment by pmo-sdr** [comment]
:thumbsup:
