### ISSUE TITLE
Check PostgisSink location in row mode

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1626]
Check if PostGISsink in row mode location values should be inserted in a other field, not in current value:
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java#L408

**Comment by fgalan** [comment]
Fixed by PR #1628
