### ISSUE TITLE
501 response is returned for a non valid API management request

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1630]
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/management/ManagementInterface.java#L164

 curl -i -X GET http://localhost:5080/vkk
HTTP/1.1 501 Not Implemented
Content-Type: text/html; charset=utf-8
Content-Length: 25
Server: Jetty(6.1.26)

GET /vkk not implemented

**Comment by Chandradeep-NEC** [comment]
@AlvaroVega 
As per my understanding, response code 501 returns from API, if  HTTP server does not support the requested functionality. In above case invalid API i.e. "vkk" should not support the functionality as it is not the correct behaviour.
So the response code 501 seems correct in this scenario.

Please confirm our understanding or could you please elaborate more in detail.

**Comment by fgalan** [comment]
In general, a REST server should response with 404 Not Found when a client try to access to a URL that it doesn't exist. Thus, this issue is about changing 501 to 404 in those cases.

**Comment by Chandradeep-NEC** [comment]
@fgalan  Thanks for your response.
 If no one is working on it then please assign this issue to me.

**Comment by Chandradeep-NEC** [comment]
@fgalan
If we modify the code from 501 to  404 Not Found then please confirm the what error message string should be printed:
As per existing behaviour, "{URI name} not implemented" is printed. as described in issue description the string is "GET /vkk not implemented".
Would the error string be same or it should also be changed as "GET /vkk not found"

**Comment by Chandradeep-NEC** [comment]
@fgalan @AlvaroVega 
Please provide respone of the query.

**Comment by AlvaroVega** [comment]
@Chandradeep-NEC  It's fine to me your purposal.

**Comment by Chandradeep-NEC** [comment]
> @Chandradeep-NEC It's fine to me your purposal.

Thanks for your response.

Case 1: "GET /vkk not found".
Case 2: "GET /vkk not implemented".
Please confirm which one is accepted by you case 1 or case 2 ?

**Comment by AlvaroVega** [comment]
case 1  "GET /vkk not found"  witch match with 404 meaning.

**Comment by fgalan** [comment]
Implemented by PR #1694 

Should we close this issue? Or is anything pending?

**Comment by Chandradeep-NEC** [comment]
> Implemented by PR #1694
> 
> Should we close this issue? Or is anything pending?

There is no pending work from our side. It's OK to close the issue.
