### ISSUE TITLE
[Feature] Add indexes management for STH collections

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1637]
When creating STH collections through cygnus it is necessary to add the relevant indexes to the collection (both raw and aggregated)

For aggregated:
```
{ "_id.entityId": 1, "_id.entityType": 1, "_id.attrName": 1, "_id.resolution": 1, "_id.origin": 1 }
```

For raw:
```
{entityId: 1, entityType: 1, attrName: 1, recvTime: 1} o {entityId: 1, entityType: 1, attrName: 1, recvTime: -1}
```

**Comment by fgalan** [comment]
A similar one has been added to Orch backlog at https://github.com/telefonicaid/orchestrator/issues/192#issuecomment-491250215

Thus, should we understand that the STH indexes creation functionality will be *both* in Cygnus and Orch? Fine with it, just to confirm this is the common understanding of this matter.

**Comment by AlvaroVega** [comment]
Currently STH sink is provisioning indexes when `dataExpiration` over `_id.origin` and `recvTime`. I guess we want that new indexes even if no dataExpiration is provided, wouldn't we?

**Comment by fgalan** [comment]
> Currently STH sink is provisioning indexes when dataExpiration over _id.origin and recvTime. I guess we want that new indexes even if no dataExpiration is provided, wouldn't we?

This is also my interpretation.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/1638
