### ISSUE TITLE
internal transaction as correlator id in logs

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1642]
Sometimes correlator id is set to internal transaction, maybe due to a mistake?
```
time=2019-05-16T13:36:44.401Z | lvl=INFO | corr=900e01dd-c936-4270-a25a-3ea9fca14cc7 | trans=275acf84-36c7-465f-8e77-4d8f9f0c3bac | srv=smartcity | subsrv=/ | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[589] : Finishing internal transaction (900e01dd-c936-4270-a25a-3ea9fca14cc7)
time=2
```

**Comment by fgalan** [comment]
I think is "legal" to set the value of trans= with the value of corr=. I mean, the rule is that corr= is the same e2e and trans= is local to the transacation. However, AFAIK, nothing precludes the use the same UUID (although a bit confusing).
