### ISSUE TITLE
Support for ckan types

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1647]
cygnus is transforming numbers to strings when inserting into CKAN. The following is an example:

CB notification:
{"subscriptionId":"5ce6afda44adf32d0ab481d9","originator":"localhost","contextResponses":[{"contextElement":{"type":"devicejson","isPattern":"false","id":"ent1","attributes":[{"name":"TimeInstant","type":"DateTime","value":"2019-05-21T10:07:25.00Z"},{"name":"temperature","type":"string","value":"80"},{"name":"humidity","type":"Number","value":31}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]}

Note that "humidity" is a number value.

Cygnus-cakn insertion:
{ "resource_id": "c528a7dd-9351-4a52-910f-30a9f2e3fd8e", "records": [ {"recvTime": "2019-05-23T16:33:06.857Z","fiwareServicePath": "/xxx","entityId": "ent1","entityType": "devicejson","TimeInstant": "2019-05-21T10:07:25.00Z","temperature": "80","humidity": "31"} ], "method": "insert", "force": "true" }

Note that "humidity" has change to a string.

**Comment by AlvaroVega** [comment]
But records is inserted in CKAN in JSON format.
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/ckan/CKANBackendImpl.java#L168
How can cygnus tell to CKAN that records in JSON format has special type?

**Comment by manucarrace** [comment]
Fixed in https://github.com/telefonicaid/fiware-cygnus/pull/1721.

Close issue
