### ISSUE TITLE
Cygnus is creating STH collection indexes on every insertion 

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1649]
When a new notification is sent to STH cygnus, it tries to create the relevant collection in mongo. If the collection exists, it throws an exception and it shows a trace such:
"Collection already exists, nothing to create".

This exception is thrown on every notification sent to STH.

Apart form that, if the "data_expiration" parameter is set, cygnus creates the relevan index. It doesn't care if the index exist or not, it tries to create the index on every notifications sent to sth cygnus. If the createIndex operation fails (the index already exists) it throws an exception and the data is not inserted.

This could lead us to several possible solutions:
1. Don't throw an exception when the createIndex operation fail, just log it and continue
2. Override the already created index with the new value configured in the data_expiration config parameter.
3. Do not create the index if the collection exists.

Apart form that it would be nice to make a check if the collection exists instead of thorwing an exception.

**Comment by AlvaroVega** [comment]
IMHO the more safe and backward fix is 1.
That's it: https://github.com/telefonicaid/fiware-cygnus/pull/1650
