### ISSUE TITLE
Postgis sink doesn't take into account type in inserted information (it always uses string)

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#1661]
It seems that Cygnus always insert data in Postgis as strings, no matter the data comes as other type in the notification sent by CB.

Link to the relevant part of the code, provided by @lammoth: https://github.com/telefonicaid/fiware-cygnus/blob/f6c6ccdf73da8aecf3274c5d98caaf80eca49917/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java#L512

Cygnus Postgis sink should take into account the JSON type of the attributes and metadata in notifcations in order to insert the data in the same format.

We have detected this is Postgis sink but maybe it happens in other ones (MySQL? Postgresql?). In that case, it would be great to solve all the possible cases (although the one for Postgis should be priorized).

**Comment by AlvaroVega** [comment]
This also happens in PosgreSQL sink, since Postgis in derived from PostgreSQL

**Comment by fgalan** [comment]
Dates should be also taken into account. In this case, JSON type is string in the notification, but they can be detected checking the attribute type (which in this case is `"DateTime"`).

**Comment by AlvaroVega** [comment]
it seems MySQL sink has also problems with datetimes: https://github.com/telefonicaid/fiware-cygnus/issues/1646

**Comment by AlvaroVega** [comment]
This is a Postgis filled by cygnus in row mode:
![Screenshot from 2019-06-10 16-18-18](https://user-images.githubusercontent.com/983422/59201762-6b6ce080-8b9b-11e9-8f95-15e772c496e8.png)

**Comment by AlvaroVega** [comment]
iot-cygnus                  | time=2019-06-11T11:25:50.241Z | lvl=DEBUG | corr=24d8ffe5-0f86-4b05-9d83-6d6d766e2a59 | trans=2900e5c3-9a70-4105-ac71-faf247a45344 | srv=smartcity | subsrv=/ | comp=cygnus-ngsi | op=insertContextData | msg=com.telefonica.iot.cygnus.backends.postgresql.PostgreSQLBackendImpl[192] : Executing SQL query **'INSERT INTO smartcity.thing3_disp42a_thing3 (recvTimeTs,recvTime,fiwareServicePath,entityId,entityType,attrName,attrType,attrValue,attrMd) VALUES ('1560252349869','2019-06-11T11:25:49.869Z','/','thing3:disp42a','thing3','temperature','Number','11','[]'),('1560252349869','2019-06-11T11:25:49.869Z','/','thing3:disp42a','thing3','TimeInstant','DateTime','2019-06-11T11:25:49.00Z','[]')'**

**Comment by fgalan** [comment]
Just to know (I'm not an expert in Postgis), what `'1560252349869'` implies? That the value is inserted as a string (looking to`'thing3:disp42a'` that is a string for sure and it is also using single quotes) or as a number?

**Comment by fgalan** [comment]
> @fgalan Could you provide a screenshot about a column mode?

Not sure of to address it... Maybe the question is for @lammoth ?

**Comment by lammoth** [comment]
@AlvaroVega the INSERT does not have any problem but all data are inserted as strings, the error related with the insert was resolved with my FIX but this FIX only resolved a problem with the strings closures, it's needed to INSERT the data with a proper type

**Comment by AlvaroVega** [comment]
@lammoth how do you INSERT data with a proper type? Could you provide me an example?

**Comment by lammoth** [comment]
[Here](https://www.postgresql.org/docs/9.2/sql-insert.html) you can see multiple examples, the query must be sent as a string, but some attributes (like numbers, geometry, etc) not

**Comment by fgalan** [comment]
Fixed by PR #1663
