### ISSUE TITLE
[cygnus-ngsi][feature][NGSIArcgisSink] create NGSIArcgisSink

### ISSUE THREAD

**Issue by pmo-sdr** [telefonicaid/fiware-cygnus#1672]
This is a sink in charge of creating Arcgis's object from NGSI.
The sink receives notifications from the Orion and creates an Arcgis Feature. This Arcgis object is formed by the fields of the Orion entities. 

The sink will use the servicepath as the name for the layer, but you must create the layer first.

**Comment by fgalan** [comment]
If you have that sink available, it would be great if you could contribute to Cygnus code with it :)

Maybe the following PRs (which shows an analogous contribution with a new sink) can be useful in terms of what it is needed to add (appart from coce itself):

https://github.com/telefonicaid/fiware-cygnus/pull/1523
https://github.com/telefonicaid/fiware-cygnus/pull/1670

Thanks!

**Comment by fgalan** [comment]
Implementation done in PR #1683 

However, we keep this issue opened as a couple of the question raised in that PR shoud be answered answered with regards to ArcgisUtils-0.0.1-SNAPSHOT.jar:

> * What kind of license has that jar file?
> * Is is uploaded to some maven repository? [I guess no but better to get it confirmed]
> * Where is the source code corresponding to that file?

**Comment by pmo-sdr** [comment]
In order to avoid licence problems with Arcgis SDK jar file, and to solve some issues conecting to Arcgis Portals, full sink remake was done.

We are using no dependencies to connect Argis now, just REST API calls, so licence problems was solved.

Development are pretty advanced, E2E test pending. (CB-Cygnus-Arcgis)

https://github.com/Stdri/fiware-cygnus/tree/ArcgisRest

**Comment by pmo-sdr** [comment]
Note that this sink allows insert/update action. Configuration method sitill under revision. #1806

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/1860

**Comment by fgalan** [comment]
> 
> 
> Implementation done in PR #1683
> 
> However, we keep this issue opened as a couple of the question raised in that PR shoud be answered answered with regards to ArcgisUtils-0.0.1-SNAPSHOT.jar:
> 
> > * What kind of license has that jar file?
> > * Is is uploaded to some maven repository? [I guess no but better to get it confirmed]
> > * Where is the source code corresponding to that file?

PR https://github.com/telefonicaid/fiware-cygnus/pull/1979 (derived from @pmo-sdr 's PR #1860) solved this pending issue, changing the driver based approach (using a jar) to REST API integration.

Thus I understand this issue hasn't anything pending and it can be closed.

Thanks for the contribution!
