### ISSUE TITLE
Docker: transform multiagent mode into multisink in a single agent

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1675]
Currently in multiagent is using one agent for sink.
· agent_mysql.conf
  cygnus-ngsi.sources = http-source
  cygnus-ngsi.sinks = mysql-sink 
  cygnus-ngsi.channels = mysql-channel 
  cygnus-ngsi.sources.http-source.channels = mysql-channel
  cygnus-ngsi.sources.http-source.port = 5050
· agent_mongo.conf
  cygnus-ngsi.sources = http-source
  cygnus-ngsi.sinks = mongo-sink 
  cygnus-ngsi.channels = mongo-channel 
  cygnus-ngsi.sources.http-source.channels = mongo-channel
  cygnus-ngsi.sources.http-source.port = 5051
 
The desired behaviour is to have one single agent conf with several sinks: 
· agent.conf
  cygnus-ngsi.sources = http-source-mysql http-source-mongo
  cygnus-ngsi.sinks = mysql-sink mongo-sink
  cygnus-ngsi.channels = mysql-channel  mongo-channel 
  cygnus-ngsi.sources.http-source-mysql.channels = mysql-channel 
  cygnus-ngsi.sources.http-source-mysql.port = 5050
  cygnus-ngsi.sources.http-source-mongo.channels = mongo-channel 
  cygnus-ngsi.sources.http-source-mysql.port = 5051

I guess this change will reduce usage or resources (from N java process -> 1 java process)

**Comment by fgalan** [comment]
Currently, we have one agent per process per sink. I mean something like this (port number maybe are not the official ones I'm using the number only to illustrate)

* Process 1, port 5050, sink MySQL
* Process 2, port 5051, sink CKAN
* Process 3, port 5052, sink HDFS 
...

I think the idea is keeping the same association (i.e. port 5050 for MySQL, port 5051 for CKAN, port 5052 per HDFS) so from a functional point of view the behavior for end systems in the same but having only one Java process.

**Comment by AlvaroVega** [comment]
Yes, it will keep current port association to sink like you said.

**Comment by AlvaroVega** [comment]
implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1678

**Comment by fgalan** [comment]
Can be closed now that PR #1678 has been merged?
