### ISSUE TITLE
Agent.conf file does not override to flume conf directory (docker)

### ISSUE THREAD

**Issue by gorkagal1983** [telefonicaid/fiware-cygnus#1693]
If we want to build a docker image of cygnus-ngsi agent with a custom agent.conf, it does not copy this file to the flume directory. In cygnus-entrypoint.sh file it appears this part of code:

```
if [ "${CYGNUS_MULTIAGENT,,}" == "false" ]; then
    # and check if SKIP ALL env var
    if [ "${CYGNUS_SKIP_CONF_GENERATION,,}" == "false" ]; then
        cp -p /opt/fiware-cygnus/docker/cygnus-ngsi/multisink_agent.conf
        ${FLUME_HOME}/conf/${AGENT_CONF_FILE}
    fi
fi
```
It seems that wants to copy the multisink_agent.conf file instead of agent.conf file...
Shouldn't be this code in order to copy the agent.conf file that we want to modify? 

```
if [ "${CYGNUS_MULTIAGENT,,}" == "false" ]; then
    # and check if SKIP ALL env var
    if [ "${CYGNUS_SKIP_CONF_GENERATION,,}" == "false" ]; then
        cp -p /opt/fiware-cygnus/docker/cygnus-ngsi/agent.conf 
       ${FLUME_HOME}/conf/${AGENT_CONF_FILE}
    fi
fi
```

Maybe I'm wrong but I do not see the way to override in flume conf directory the agent.conf file....

Thanks.

**Comment by AlvaroVega** [comment]
If you want override agent.conf file, then you should set follow env vars:
CYGNUS_MUTIAGENT=false 
CYGNUS_SKIP_CONF_GENERATION=true

**Comment by AlvaroVega** [comment]
@gorkagal1983 Did you check it?

**Comment by fgalan** [comment]
As far as I understand (@AlvaroVega know this pretty better than me :) if you use  CYGNUS_SKIP_CONF_GENERATION=true then you can use a custom agent.conf file but that file (supposedly existing in your hosts) should be "mapped" to the default Flume path:

Something like this in the `volumes` section in your docker-compose.yml configuration:

```
- /path/in/you/host/agent.conf:/opt/apache-flume/conf/agent.conf:ro
```

**Comment by gorkagal1983** [comment]
Yes...this is what I wanted to avoid @fgalan , to create a volume. Thing is that If I remember well (tell me if not), in previous versions in the cygnus-entrypoint.sh file that custom agent.conf file was automatically copied without creating any volume....this is why I asked it, but it's OK, thanks!

**Comment by fgalan** [comment]
As far as I know, the way in which cygnus-entrypoint.sh worked in past versions (in the current one if you set CYGNUS_SKIP_CONF_GENERATION=false) is to autogenerate the conf file, based on an existing template, but "patching" is depending of the several values of the CYGNUS_XXX variables, as described in https://fiware-cygnus.readthedocs.io/en/master/cygnus-ngsi/installation_and_administration_guide/install_with_docker/index.html.

**Comment by AlvaroVega** [comment]
Shall we close this issue ?

**Comment by gorkagal1983** [comment]
From my part, yes..everything is clear.Enviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: Alvaro Vega <notifications@github.com> Fecha: 4/11/19  16:22  (GMT+01:00) Para: telefonicaid/fiware-cygnus <fiware-cygnus@noreply.github.com> Cc: gorkagal1983 <gorkagal@gmail.com>, Mention <mention@noreply.github.com> Asunto: Re: [telefonicaid/fiware-cygnus] Agent.conf file does not override to flume conf directory (docker) (#1693) Shall we close this issue ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telefonicaid/fiware-cygnus/issues/1693?email_source=notifications\u0026email_token=AD7U65ZAVVZFZW3M3IBYG63QSA42XA5CNFSM4H54VCW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC7TXQI#issuecomment-549403585",
"url": "https://github.com/telefonicaid/fiware-cygnus/issues/1693?email_source=notifications\u0026email_token=AD7U65ZAVVZFZW3M3IBYG63QSA42XA5CNFSM4H54VCW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC7TXQI#issuecomment-549403585",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
