### ISSUE TITLE
Changing cygnus port does not work

### ISSUE THREAD

**Issue by abrahamSecmotic** [telefonicaid/fiware-cygnus#1698]
Hi,

I am trying to change the cygnus port with the environment variable "CYGNUS_SERVICE_PORT=5070".

But it is being deployed with port 5050, the environment variable is 5070, but the agent.conf file does not change.

Docker-compose part:
```javascript
 cygnus:
    image: fiware/cygnus-ngsi:1.14.0
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
      - orion
    expose:
      - "5070"
    ports:
      - "5070:5070"
    environment:
      - CYGNUS_SERVICE_PORT=5070
      ....
```

**Comment by AlvaroVega** [comment]
As you can see at:
https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/installation_and_administration_guide/install_with_docker.md#using-a-specific-configuration
cygnus container is using several ports to provide service, not just one:

sink | port | admin_port
-- | -- | --
mysql | 5050 | 5080
mongo | 5051 | 5081
ckan | 5052 | 5082
hdfs | 5053 | 5083
postgresql | 5054 | 5084
cartodb | 5055 | 5085
orion | 5056 | 5086
postgis | 5057 | 5087
elasticsearch | 5058 | 5088

But its true that CYGNUS_SERVICE_PORT has no effect, and maybe should have it.

**Comment by AlvaroVega** [comment]
I guess this port value
https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L141
should be handled by CYGNUS_SERVICE_PORT

**Comment by Madhu-NEC** [comment]
Hi @fgalan , @AlvaroVega 

As described [here](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/installation_and_administration_guide/install_with_docker.md#using-a-specific-configuration), there should be separate variables to configure changed ports with each sink.
For example CYGNUS_MYSQL_PORT to configure at https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L139 , CYGNUS_MONGO_PORT to configure at https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L205 and so on.

There are two cases for agent configuration:
1. CYGNUS_MULTIAGENT=false 
In above case, this [line ](https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L205) will never get executed as CYGNUS_MULTIAGENT is disabled. So the configured port will not be seen in agent.conf . As per my analysis, if the [statement ](https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L205)is moved outside of [if block](https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L202) then this issue will be fixed.
2. CYGNUS_MULTIAGENT=true
In this case, the configured port will work as specified in docker-compose if we confiure separate variables for each sink.

**Please confirm my understanding.**

**Comment by AlvaroVega** [comment]
CYGNUS_MYSQL_PORT,  CYGNUS_MONGO_PORT and so on could not be used to set cygnus service port, because currently are used to define mongo, mysql default ports, not sink.  I think current env var CYGNUS_SERVICE_PORT and probably others like (CYGNUS_MYSQL_SERVICE_PORT, CYGNUS_MONGO, etc) should be added and used instead of fixed ports like 5050,5051, etc in that entrypoint script. And as you said that statement https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/cygnus-entrypoint.sh#L205 should be moved outside of  if block

**Comment by fgalan** [comment]
I understand that after merging PR #1755, this issue can be closed. Please, tell me otherwise if I'm wrong.

**Comment by Chandradeep-NEC** [comment]
@fgalan  @AlvaroVega  @abrahamSecmotic 
I request you to please assign this issue to @Madhu-NEC  as she has raised the PR which is now merged

Thanks :)

**Comment by fgalan** [comment]
Done!
