### ISSUE TITLE
Disable metadata insertion

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1706]
Dealing with metadata in databases could be annoying. You have to create every single metadata columns related to an attribute.

This feature could be useful when inserting data in an already existing mysql/postgresql schema.

It could be nice to have it at sink level as a new parameter (disable_metadata or similar)

**Comment by manucarrace** [comment]
The solution could be implemented at sink level or at interceptor level (name_mapping)

**Comment by fgalan** [comment]
> The solution could be implemented at sink level or at interceptor level (name_mapping)

I understand that by name_mapping you mean to configure it on the JSON of the name_mapping, isn't it?

A third option would be in the configuration of the source, for instance:

```
cygnusagent.sources.http-source.metadata = false
```

or

```
cygnusagent.sources.http-source.interceptors.metadata = false
```

**Comment by manucarrace** [comment]
This feature is specially interesting at HDFS sink, csv format, where matadata need a especific folder out of the csv file. To be analized with #1591

**Comment by AlvaroVega** [comment]
Should we close this issue ?

**Comment by fgalan** [comment]
> Should we close this issue ?

I think the refernce to this issue in PR #1804 was due to a mistake, see https://github.com/telefonicaid/fiware-cygnus/pull/1804#discussion_r371230895. In that case, maybe this issue is still valid so it should be kept opened.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-cygnus/pull/1810
