### ISSUE TITLE
error java.lang.NoClassDefFoundError: es/santander/smartcity/arcgisutils/Arcgis

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1741]
When arcgis sink is instanciated:

iot-cygnus | time=2019-09-24T13:57:06.791Z | lvl=INFO | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=create | msg=org.apache.flume.sink.DefaultSinkFactory[42] : Creating instance of sink: arcgis-sink, type: com.telefonica.iot.cygnus.sinks.NGSIArcGisSink
iot-cygnus | time=2019-09-24T13:57:06.824Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=run | msg=org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable[150] : Failed to start agent because dependencies were not found in classpath. Error follows.
iot-cygnus | java.lang.NoClassDefFoundError: es/santander/smartcity/arcgisutils/Arcgis
iot-cygnus | at java.lang.Class.forName0(Native Method)
iot-cygnus | at java.lang.Class.forName(Class.java:264)
iot-cygnus | at org.apache.flume.sink.DefaultSinkFactory.getClass(DefaultSinkFactory.java:68)
iot-cygnus | at org.apache.flume.sink.DefaultSinkFactory.create(DefaultSinkFactory.java:43)
iot-cygnus | at org.apache.flume.node.AbstractConfigurationProvider.loadSinks(AbstractConfigurationProvider.java:450)
iot-cygnus | at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:106)
iot-cygnus | at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:145)
iot-cygnus | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
iot-cygnus | at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
iot-cygnus | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
iot-cygnus | at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
iot-cygnus | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
iot-cygnus | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
iot-cygnus | at java.lang.Thread.run(Thread.java:748)
iot-cygnus | Caused by: java.lang.ClassNotFoundException: es.santander.smartcity.arcgisutils.Arcgis
iot-cygnus | at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
iot-cygnus | at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
iot-cygnus | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
iot-cygnus | at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
iot-cygnus | ... 14 more
iot-cygnus | time=2019-09-24T13:57:07.196Z | lvl=INFO | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=main | msg=com.telefonica.iot.cygnus.nodes.CygnusApplication[320] : Waiting for valid Flume components references...

**Comment by AlvaroVega** [comment]
Config used:


# Arcgis http-source

cygnus-ngsi.sources.http-source-arcgis.type = org.apache.flume.source.http.HTTPSource
cygnus-ngsi.sources.http-source-arcgis.channels = arcgis-channel
cygnus-ngsi.sources.http-source-arcgis.port = 5059
cygnus-ngsi.sources.http-source-arcgis.handler = com.telefonica.iot.cygnus.handlers.NGSIRestHandler
cygnus-ngsi.sources.http-source-arcgis.handler.notification_target = /notify
cygnus-ngsi.sources.http-source-arcgis.handler.default_service = default
cygnus-ngsi.sources.http-source-arcgis.handler.default_service_path = /
cygnus-ngsi.sources.http-source-arcgis.interceptors = ts nmi
cygnus-ngsi.sources.http-source-arcgis.interceptors.ts.type = timestamp
cygnus-ngsi.sources.http-source-arcgis.interceptors.gi.type = com.telefonica.iot.cygnus.interceptors.NGSIGroupingInterceptor$Builder
cygnus-ngsi.sources.http-source-arcgis.interceptors.gi.grouping_rules_conf_file = /opt/apache-flume/conf/grouping_rules.conf
cygnus-ngsi.sources.http-source-arcgis.interceptors.nmi.type = com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor$Builder
cygnus-ngsi.sources.http-source-arcgis.interceptors.nmi.name_mappings_conf_file = /opt/apache-flume/conf/name_mappings_arcgis.conf


# NGSIArcGisSink configuration
cygnus-ngsi.sinks.arcgis-sink.type = com.telefonica.iot.cygnus.sinks.NGSIArcGisSink
cygnus-ngsi.sinks.arcgis-sink.channel = arcgis-channel
cygnus-ngsi.sinks.arcgis-sink.arcgis_url = https://<host>/<id>/ArcGIS/rest/services/
cygnus-ngsi.sinks.arcgis-sink.arcgis_username =
cygnus-ngsi.sinks.arcgis-sink.arcgis_password =
cygnus-ngsi.sinks.arcgis-sink.enable_encoding = false
cygnus-ngsi.sinks.arcgis-sink.enable_grouping = false
cygnus-ngsi.sinks.arcgis-sink.enable_name_mapping = true
cygnus-ngsi.sinks.arcgis-sink.enable_lowercase = false
cygnus-ngsi.sinks.arcgis-sink.data_model = dm-by-entity
cygnus-ngsi.sinks.arcgis-sink.batch_size = 10
cygnus-ngsi.sinks.arcgis-sink.batch_timeout = 30
cygnus-ngsi.sinks.arcgis-sink.batch_ttl = 10

**Comment by fgalan** [comment]
@pmo-sdr what do you think? Any feedback on this, please? Thanks!

**Comment by AlvaroVega** [comment]
docker container has the following jar:
./opt/fiware-cygnus/cygnus-ngsi/src/main/resources/ArcgisUtils-0.0.1-SNAPSHOT.jar

**Comment by AlvaroVega** [comment]
possible fix https://github.com/telefonicaid/fiware-cygnus/pull/1778 ?

**Comment by fgalan** [comment]
PR #1778 has been merged. Should this issue be closed?
