### ISSUE TITLE
How to avoid slash in collection name

### ISSUE THREAD

**Issue by raiuli** [telefonicaid/fiware-cygnus#1754]
When data is sent from orion borker to cygnus, Cygnus creates the collection name with "/" is it possible to use any other separator. As for example, the entity name is room01 and entity type is room. Then the collection name becomes sth_/_room01_room. If it is possible how can I change the configuration? because I cannot use mongodump to creat backup of it.

**Comment by fgalan** [comment]
I think this would be a good question for StackOverflow (https://stackoverflow.com) rather than and issue. Could you create it there (basically, copy-pasting you text), please? Please add the "fiware-cygnus" label.

After posting the question in SOF, include a link to it from this issue. Then, close the issue.

Thanks!

**Comment by raiuli** [comment]
Hi Fermin,
Thanks for the reply.

I have already have posted in stackoverflow. But no answer..
https://stackoverflow.com/questions/58622794/fiware-cygnus-mongodb-storing-collection-name-with-how-to-use-other-separator

Best regards,
Raihan Ul Islam
PhD Student, Mobile and Pervasive Computing
Division: Computer Science
Department: Department of Computer Science, Electrical and Space Engineering
Email: raihan.ul.islam@ltu.se<mailto:raihan.ul.islam@ltu.se>
Luleå University of Technology
SE-931 87 Skellefteå, Sweden
Phone: +46 (0)910 585734

När du skickar e-post till Luleå tekniska universitet (LTU) innebär detta att LTU kommer att behandla dina personuppgifter. Du kan läsa mer om hur LTU behandlar personuppgifter här<https://www.ltu.se/about/Behandling-av-personuppgifter-GDPR>.

Sending email to Luleå university of technology (LTU) will result in LTU processing your personal data. You can read more about LTU’s processing of personal data here<https://www.ltu.se/about/Behandling-av-personuppgifter-GDPR?l=en>.
