### ISSUE TITLE
Make cygnus to accept NGSIv2 notifications

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1757]

**Comment by fgalan** [comment]
I think this issue is a duplicate of https://github.com/telefonicaid/fiware-cygnus/issues/953. I'd suggest to close it and focus discussion in the older (as it contasins more information and some implementation hints).

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/fiware-cygnus/issues/953 is currently in pinned issues :)
