### ISSUE TITLE
Error in cygnus when no interceptor is defined in agent.conf

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1763]
In the event that no interceptor is defined in agent.conf file, cygnus start logging a lot of lines forever.

It would be nice to investigate if it's possible to raise an error and stop the process.

**Comment by Kajal-NEC** [comment]
@manucarrace
When I do not define any interceptors in agent.conf file, I did't received any error log.
But when I give wrong file path for `cygnus-ngsi.sources.http-source-postgresql.interceptors.nmi.name_mappings_conf_file` , that time I am getting some error logs forever as shown below:

`time=2023-02-14T09:02:02.704Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[244] : [nmi] Runtime error (/opt/apache-flume/conf/name_mappings.conf (No such file or directory))
time=2023-02-14T09:02:32.707Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[244] : [nmi] Runtime error (/opt/apache-flume/conf/name_mappings.conf (No such file or directory))
time=2023-02-14T09:03:02.709Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[244] : [nmi] Runtime error (/opt/apache-flume/conf/name_mappings.conf (No such file or directory))
time=2023-02-14T09:03:32.711Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[244] : [nmi] Runtime error (/opt/apache-flume/conf/name_mappings.conf (No such file or directory))
time=2023-02-14T09:04:02.712Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[244] : [nmi] Runtime error (/opt/apache-flume/conf/name_mappings.conf (No such file or directory))
time=2023-02-14T09:04:32.715Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[244] : [nmi] Runtime error (/opt/apache-flume/conf/name_mappings.conf (No such file or directory))
`

**Query:**
Is this same error you have mentioned for this issue?

**Comment by Cee3097** [comment]
They entered a generic auto url into md. Cannot reach site via internet.
Will try later to answer your question when I see if my app will make it
online. I'm busy with public obligations today concerning jobs and
property. I wouldn't have used email but you asked a question and i felt
obliged infinity

**Comment by Kajal-NEC** [comment]
Gentle reminder!!
Please provide your opinion on this query.

**Comment by mapedraza** [comment]
@Kajal-NEC Thank for your willingness to contribute to this issue. Please could you provide the `agent.conf` file  and the output log for each scenario you tested?

**Comment by cesarjorgemartinez** [comment]
This scenario is correct.
If you not provide at least one interceptor the informations must be lost (can be show one log warning).
If you provide one but not correct, the error must be shown, but is a big logic error to stop the process because you can use multiple other sinks and cause indeseable side effects in other sinks.
