### ISSUE TITLE
Need of change of logging level for MySQL inserts (the log with the details of the data to be persisted)

### ISSUE THREAD

**Issue by smartcitydevops** [telefonicaid/fiware-cygnus#1768]
For insertion errors in Cygnus MySQL logs, such as:

time=2019-11-27T16:44:23.526Z | lvl=ERROR | corr=2849fd36-1135-11ea-80b5-fa163e83ea20 | trans=d4810c75-3f68-42c8-acfd-bfd2b4ee49d3 | srv=xxxxxx | subsrv=/yyy | op=processNewBatches | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSISink[562] : BadContextData (SQLException). Data insertion error (Incorrect decimal value: '' for column 'latitude' at row 2). Stack trace: [com.telefonica.iot.cygnus.backends.mysql.MySQLBackendImpl.insertContextData(MySQLBackendImpl.java:186), com.telefonica.iot.cygnus.sinks.NGSIMySQLSink.persistAggregation(NGSIMySQLSink.java:678), com.telefonica.iot.cygnus.sinks.NGSIMySQLSink.persistBatch(NGSIMySQLSink.java:242), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:559), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:371), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147), java.lang.Thread.run(Thread.java:748)]

This log is written with lvl=ERROR, but the related log:

time=2019-11-27T17:53:42.997Z | lvl=INFO | corr=d9e9ce8c-113e-11ea-8aaf-fa163e83ea20 | trans=92603751-4138-4cfc-8762-0b338ef03d2d | srv=xxxxxxx| subsrv=/yyyy | op=persistAggregation | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSIMySQLSink[664] : [mysql-sink-mysql] Persisting data at NGSIMySQLSink. Database (ffffff), Table (kkkkk), Fields ((---------------------------------)), Values (('2019-11-27 17:53:39.833','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','60','[]','2019-11-27 15:25:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:39.839','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','60','[]','2019-11-27 14:45:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:40.200','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','59','[]','2019-11-27 14:05:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:40.210','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','58','[]','2019-11-27 13:25:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:40.214','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','56','[]','2019-11-27 13:05:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:40.515','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','53','[]','2019-11-27 12:25:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:40.521','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','51','[]','2019-11-27 11:45:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:41.275','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','49','[]','2019-11-27 11:05:46','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:41.280','/moba','MOBA_187','MOBA','48','[]','ENV3200','[]','47','[]','2019-11-27 10:25:16','[]','40.6426','[]','-3.17913','[]'),('2019-11-27 17:53:42.993','/moba','MOBA_1953','MOBA','1814','[]','PAP3200','[]','-1','[]','2019-11-27 05:34:00','[]','','','-3.12591','[]'))

is written with lvl=INFO. So, if we raise the log level error to ERROR level, we lost the information of the data that causes the problem. We need that the "insert" log , that is, the log with the details of the data to be persisted will be shown for ERROR condition, not just the first log

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1772. Should this issue be closed or is anything else pending?

**Comment by manucarrace** [comment]
This problem has been addressed in commit d04526af68d97f600c1e36c7f8fbcc67e3ac0fab for the https://github.com/telefonicaid/fiware-cygnus/pull/1784.

Basically, the ERROR trace has been extended to include the SQL insert sentence.
