### ISSUE TITLE
Change of log level for certain logs in Cygnus HDFS

### ISSUE THREAD

**Issue by smartcitydevops** [telefonicaid/fiware-cygnus#1769]
Please note that we are finding some log messages with lvl=INFO but with a worrying message. For example:

time=2019-11-28T15:12:57.356Z | lvl=INFO | corr=8bbae4c2-11f1-11ea-83ca-fa163e83ea20 | trans=3670d10c-36d2-4098-b4b1-127fcd8e633f | srv=XXXX | subsrv=/YYYY | op=persistMDAggregations | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSIHDFSSink[1117] : [hdfs-sink-hdfs] There was some problem with the current endpoint, trying other one. Details: CygnusPersistenceError. The /df/safd/T248669_NoiseLevelObservedxfffflocationxffffgeo:point directory could not be created in HDFS. Server response: 400 Bad Request.

time=2019-11-28T15:12:26.847Z | lvl=INFO | corr=7ca3db88-11f1-11ea-ad6b-fa163e83ea20 | trans=01958adc-6689-4803-ae01-89081d37f43b | srv=XXXX | subsrv=/KKK  | op=persistMDAggregations | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSIHDFSSink[1117] : [hdfs-sink-hdfs] There was some problem with the current endpoint, trying other one. Details: CygnusPersistenceError. /df/sadf/LaboratorioMunicipal__2605_e3t_LS40xffffpower_activexfffffloat/LaboratorioMunicipal__2605_e3t_LS40xffffpower_activexfffffloat.txt file exists in HDFS, but could not write the data. Server response: 500 Internal Server Error.

Please raise the level of logging of these kind of messages including a "Server response:" and an error message

**Comment by IvanHdzC** [comment]
> [hdfs-sink-hdfs] **There was some problem with the current endpoint, trying other one. Details: CygnusPersistenceError.** /df/sadf/LaboratorioMunicipal__2605_e3t_LS40xffffpower_activexfffffloat/LaboratorioMunicipal__2605_e3t_LS40xffffpower_activexfffffloat.txt file exists in HDFS, but could not write the data. **Server response: 500 Internal Server Error**.

On each one of the examples provided there is already a "Server response" and an "error message". Can you be a little more specific about what you would like to see on logs @smartcitydevops?

**Comment by fgalan** [comment]
Fixed by PR #1774. Should be the issue closed (once that PR gets merged) or is anything else pending?
