### ISSUE TITLE
wrong array persistence in sink

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1779]
There is some problems trying to persist an array, like:
```
{"name":"category","type":"List","value":["process"] }
```
i.e. with postgresql/postgis:

time=2019-12-18T11:12:15.628Z | lvl=ERROR | corr=3eff4b96-2187-11ea-9c4c-fa163e0e6feb | trans=885bc7aa-0223-48c5-8d80-bc18bd080550 | srv=sc_vlci | subsrv=/wifi | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[562] : BadContextData (SQLException). Data insertion error (**ERROR: malformed array literal: "["process"]"
  Detail: "[" must introduce explicitly-specified array dimensions.**
  Position: 342). Stack trace: [com.telefonica.iot.cygnus.backends.postgresql.PostgreSQLBackendImpl.insertContextData(PostgreSQLBackendImpl.java:197), com.telefonica.iot.cygnus.sinks.NGSIPostgisSink.persistAggregation(NGSIPostgisSink.java:587), com.telefonica.iot.cygnus.sinks.NGSIPostgisSink.persistBatch(NGSIPostgisSink.java:275), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:559), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:371), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:67), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145), java.lang.Thread.run(Thread.java:748)]
time=2019-12-18T11:12:15.631Z | lvl=INFO | corr=3eff4b96-2187-11ea-9c4c-fa163e0e6feb | trans=885bc7aa-0223-48c5-8d80-bc18bd080550 | srv=sc_vlci | subsrv=/wifi | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSIPostgisSink[574] : [postgis-sink] Persisting data at NGSIPostgisSink. Schema (sc_vlci), Table (wifi_newusers), Fields ((recvTime,fiwareServicePath,entityId,entityType,category,category_md,calculationFrequency,calculationFrequency_md,dataProvider,dataProvider_md,dlNumberOfNewCitizens,dlNumberOfNewCitizens_md,dlNumberOfNewCitizensSource,dlNumberOfNewCitizensSource_md,dlNumberOfNewCitizensUpdatedAt,dlNumberOfNewCitizensUpdatedAt_md,dlNumberOfNewUser,dlNumberOfNewUser_md,dlNumberOfNewUsersSource,dlNumberOfNewUsersSource_md,dlNumberOfNewUsersUpdatedAt,dlNumberOfNewUsersUpdatedAt_md,dlNumberOfNewWorkers,dlNumberOfNewWorkers_md,dlNumberOfNewWorkersSource,dlNumberOfNewWorkersSource_md,dlNumberOfNewWorkersUpdatedAt,dlNumberOfNewWorkersUpdatedAt_md,name,name_md,organization,organization_md,process,process_md,source,source_md)), Values (('2019-12-18T11:12:15.93Z','/wifi','OCI.DL.001','KeyPerformanceIndicatorURBO','["process"]','[]','daily','[]','URL eWAS','[]','14','[]','eWas. Fichero: alta_usuarios','[]','2019-11-26','[]','14','[]','eWas. Ficheros: alta_usuarios y f_ alta_usuarios','[]','2019-11-26','[]','0','[]','eWas. Fichero: f_alta_usuarios','[]','2019-11-26','[]','Número de usuarios dados de alta en Wifi Valencia y AVC','[]','OCI','[]','WIFI','[]','eWAS','[]'))
time=2019-12-18T11:12:15.633Z | lvl=ERROR | corr=3eff4b96-2187-11ea-9c4c-fa163e0e6feb | trans=885bc7aa-0223-48c5-8d80-bc18bd080550 | srv=sc_vlci | subsrv=/wifi | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[562] : **BadContextData (SQLException). Data insertion error (ERROR: malformed array literal: "["process"]"**

**Comment by mrutid** [comment]
The problem seems to be the type of the database field:

`category text[]`

Surely `'["process"]'` will fit nicely as a JSON in a text filed.

The necessity of support for native postgres arrays will be discussed.

**Comment by AlvaroVega** [comment]
postgresql support native json since 9.2 version https://www.postgresql.org/docs/9.4/datatype-json.html
