### ISSUE TITLE
remove string conversion when insert  in some sinks (postgresql, postgis)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1780]
Currently sinks are inserting attribute values in SQL adding string marks `' `, but this solution only has sense for string values.

The proposed method should check if attribute value is:
- Location: should be check attribute type and adapt location to implementation sink
- Datetime: should be check attribute type and adapt location to implementation sink
- JSON: should be check attribute value (i.e. trying to parse to json) but should be inserted into a string `" {'key':'value'}"`
- Null: should be checked if value is null or not exists
- String: should be check attribute value is a string (i.e. starts with `"`" or tryng parse to string)
Otherwise (number, an so on ) is like value is received by ngsi sink from ngsivent

Affected Sinks:
- MySQL https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMySQLSink.java
- PostgreSQL https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgreSQLSink.java
- PostGIS https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java

This new way of insert should be configurable by sink with a new flag, and then we should preserve previous implementation (previous attempts were done under `attrNativeTypes` flag).

A complete battery tests (ngsi events) should be provided also (by @manucarrace)

**Comment by fgalan** [comment]
> This new way of insert should be configurable by sink with a new flag, and then we should preserve previous implementation (previous attempts were done under nativeAttributes flag).

Maybe DB migration scripts (.sql scripts?) could be developed in the context of this task, so existing DBs usign "the old way" could be automatically migrated to new one.

**Comment by manucarrace** [comment]
The subscription to be received would have the following fields:

- Bool value
- Numeric value
- Date value (type --> DateTime)
- Geographic value (type --> geo:json, geo:point)
- Json value
- String value



{
  "subscriptionId": "5d6fcaea304a983349138ba7",
  "originator": "localhost",
  "contextResponses": [
    {
      "contextElement": {
        "type": "myType",
        "isPattern": "false",
        "id": "myEntity2",
        "attributes": [
          {
            "name": "attrBool",
            "type": "foo",
            "value": false
          },
          {
            "name": "attrNum",
            "type": "foo",
            "value": 34
          },
          {
            "name": "attrDate",
            "type": "DateTime",
            "value": "2016-09-21T01:23:00.00Z"
          },
          {
            "name": "attrLocation",
            "type": "geo:json",
            "value": {
              "type": "Point",
              "coordinates": [
                -0.036177,
                39.986159
              ]
            }
          },
          {
            "name": "attrJson",
            "type": "foo",
            "value": [
              {
                "name": "R",
                "value": "0.00000"
              },
              {
                "name": "S",
                "value": "0.00000"
              },
              {
                "name": "T",
                "value": "0.00000"
              }
            ]
          },
          {
            "name": "attrText",
            "type": "foo",
            "value": "texto"
          }
        ]
      },
      "statusCode": {
        "code": "200",
        "reasonPhrase": "OK"
      }
    }
  ]
}

**Comment by manucarrace** [comment]
For PostgreSQL and PostGIS

**String values** --> Don´t need a specific processing, just insert values between ''. Should be the default behavour. PostgreSQL type should be "text".
**Numeric Values** --> Need to be inserted without ''. PostgreSQL compatible types should be "double precision", "real", "numeric" and "decimal".
**Bool values** --> Need to be inserted as TRUE or FALSE. Native json values (true|false) are also supported from version 9.4. Anyway uppercase values should be used (SQL standard values). PostgreSQL type should be "boolean".
**Json values** --> Don't need a specific processing, just insert value between ''. They should be treated as strings. PostgreSQL compatible types are "text" and "json".
**Date values** -->  Don't need a specific processing, just insert value between ''. PostgresSQL compatible types are "timestamp without timezone", "timestamp" and "timestamp with timezone". PostgreSQL is ISO8601 compliant. It is recommended to use "timestamp without timezone" and store datetimes in UTC.

**Comment by manucarrace** [comment]
Issue only applies to column mode. In row mode, it is assumed that column types are "text" and no specific processing is needed. Every value is casted to text.

**Comment by IvanHdzC** [comment]
The scope for this issue only considers Postgres and Postgis, this because it's necessary to make some code cleanning for MySQL Sink before this task can be done on it.

**Comment by IvanHdzC** [comment]
> For PostgreSQL and PostGIS
> 
> **String values** --> Don´t need a specific processing, just insert values between ''. Should be the default behavour. PostgreSQL type should be "text".
> **Numeric Values** --> Need to be inserted without ''. PostgreSQL compatible types should be "double precision", "real", "numeric" and "decimal".
> **Bool values** --> Need to be inserted as TRUE or FALSE. Native json values (true|false) are also supported from version 9.4. Anyway uppercase values should be used (SQL standard values). PostgreSQL type should be "boolean".
> **Json values** --> Don't need a specific processing, just insert value between ''. They should be treated as strings. PostgreSQL compatible types are "text" and "json".
> **Date values** --> Don't need a specific processing, just insert value between ''. PostgresSQL compatible types are "timestamp without timezone", "timestamp" and "timestamp with timezone". PostgreSQL is ISO8601 compliant. It is recommended to use "timestamp without timezone" and store datetimes in UTC.

As a reference, this info is extended on the following [Google spreadsheet. ](https://docs.google.com/spreadsheets/d/1or29bO2ftvYtjzFYDunQ_8PQMFAetXBXgtyUGlH29jw/edit?ts=5e0de306#gid=0).

**Comment by manucarrace** [comment]
"timestamp without timezone" makes me wonder if we should translate every date to UTC ...

**Comment by manucarrace** [comment]
Special cases:

**value ''** --> It will be treated as an empty string
**null value** --> Should be converted to NULL. NULL should be valid for any column type

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-cygnus/pull/1784

**Comment by IvanHdzC** [comment]
additional tasks to consider mentioned on PR #1784 

- [ ] One aditional remark. It should be nice to have an aditional flag in config like "NullValuesForMissingAttributes". This flag is needed to enable backward compatibility for those clients that used to insert "" for missing attributes in batches.

- [ ] we should deal with the problem of missing attributes in batch insertions. Missing attributes should be included as NULL

**Comment by fgalan** [comment]
Looking above I see DISMISS and DONE in the pending tasks. Thus, should this issue be closed? Or is there anything else pending?

**Comment by manucarrace** [comment]
Can be closed. NULL values are inserted automatically by database in case the field is not included in the INSERT statement.
