### ISSUE TITLE
Encode csv separator character in attribute value

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1785]
If the csv separator character is found in an attribute value, it should be encoded

**Comment by IvanHdzC** [comment]
[According to wikipedia](https://en.wikipedia.org/wiki/Comma-separated_values) the correct way to encode commas on csv is to quote the complete value like this.

1997,Ford,E350,"Super, luxurious truck"

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-cygnus/pull/1799

**Comment by manucarrace** [comment]
Eventually, nothing but adding a recomendation to use ; as separator has been done.

Encode the separator seems to be a non-consistent solution since cygnus may deal with json compound values.
On the other hand, the use of " " for values with comma, it is not properly interpreted by Hive parser.
