### ISSUE TITLE
Extend aggregation method for every sink

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1787]
Currently, only MySQL sink deals with missing attributes in batch insertions. It completes the missing fields with NULL. (WIP PostGIS and PostgreSQL)

This behaveour is the desired behaviour for every sink. At least, it has to be asessed if this is the desired behaviour for:

- CKANSink
- HDFSSink
- STHSink
- MongoSink

Moreover, if it is confirmed that this behaviour is valid for every sink, it would be interesting to make a refactor in order to include the aggregation method in the NGSISink class.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-cygnus/pull/1798
