### ISSUE TITLE
Store Cyngus ERROR into native persistence, orion, snippet service...

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1791]
Purpose: a final client could access by himself to that information (without devops team).
Useful to reduce support questions in integrations (80%) 

First of all: handler for all sinks to catch error

Possible places to store cygnus errors:
- Native sink persistence (i.e. special table)
- Context Broker: using service/subservice from notification event
- Internet service snippet manager

**Comment by mrutid** [comment]
Several options maybe available/configurable. Some independent from the Sink, some Sink dependent.

Independent options maybe seamless available to all sinks. Specific option could be implemented per sink.

**Comment by IvanHdzC** [comment]
This task has special focus on SQL sinks, this has to be handled by sink implementation.

**Comment by fgalan** [comment]
Implemented in PR #1823
