### ISSUE TITLE
New data model for CKAN

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#1792]
We want to extend the CKAN sink in order to comply with the following:
Every entity will correspond with a dataset and resource as per the following scherma:
 
subservice -----> Organization
Entity -----> Dataset
Entity -----> Resource

**Comment by fgalan** [comment]
> Entity -----> Dataset
> Entity -----> Resource

Is this correct? Or maybe it's a typo and the first one refers to EntityType (i.e. EntityType ---> Dataset)?

**Comment by fgalan** [comment]
Implemented in PR #1850
