### ISSUE TITLE
Split HDFS files by hour/day/month/year

### ISSUE THREAD

**Issue by IvanHdzC** [telefonicaid/fiware-cygnus#1830]
When there are a lot of requests to a same file in HDFS the files where data is written can get really big. This makes the application slower and makes harder file processing.

In order to process the all the info without having large files, it's necessary to split files by hour/day/month/year. This can be achieved by adding a new flag into the agent.conf like the following

`cygnusagent.sinks.hdfs-sink-hdfs.file_split_periodicity= `

The possible values would be:

`
hourly
daily
monthly
yearly
`
This will add the value corresponding the flag to the file name when processing requests.

For instance.

`file_split_periodicity = hourly`

When a requests arrives at **10:59 am on 11/03/2020** and it will be added to a file **service.csv**

It will try to append all data on the request to the file **service_1011032020.csv**

if a new requests arrives at **11:00 am on 11/03/2020**

It will be appended to the file **service_1111032020.csv**

At all cases if the file doesn't exists, it must be created.

**Comment by manucarrace** [comment]
If new flag is not present no split will be done (in order to assure retro-compatibility).

Also, it would be possible to set the value to "none" which is equivalent to not having the flag.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-cygnus/pull/1834
