### ISSUE TITLE
[cygnus-ngsi][bug][ElasticsearchBackendImpl] Japanese characters are garbled

### ISSUE THREAD

**Issue by nmatsui** [telefonicaid/fiware-cygnus#1839]
When I stored some Japanese characters to Elasticsearch by using `ElasticsearchBackendImpl`,  the characters were garbled as "??????????".

This is because when a `org.apache.http.entity.StringEntity` is newed without specifying Charset, the given characters will be encoded by using default Charset like ISO-8859-1.

**Comment by fgalan** [comment]
Fixed by PR #1841
