### ISSUE TITLE
[cygnus-ngsi][bug][NGSIMongoSink] Persistence Error raised with valid Collection but detected as null

### ISSUE THREAD

**Issue by srrspace** [telefonicaid/fiware-cygnus#1845]
When data try to be stored at NGSIMongoSink an error is raised even if the collection exist and is valid.

It seems that the collection name in the aggregator is not initialized correctly in the persistBatch(NGSIBatch batch) function.

In the cygnus v1.13.0 and v1.18.0_SNAPSHOT at date 03/03/2020 before the generic aggregation implementation (refactoring task) there was no error raised but the data was stored to mongodb as string instead of Documents (BSON document).

As I understood that in the current master Cygnus repository with the refactoring task the collection storage issues was corrected (i.e. Documents instead of strings) I installed this current version in my Cygnus instance.

I installed the current Cygnus (master) and tested with my data sent (BTW of the iotagent-json with 2 kind of sensor data with their corresponding Fiware-Service and Fiware-ServicePath) to Cygnus via Orion CB (NGSI v2).

Cygnus receive the data correctly but when it try to store the data (persistBatch(...)), it detect that the collection is null but really this collection name is correct.

Below this is an extract of the Cygnus log with the error:

(This error happens in my 2 kind of data for different service domains, here this is related to bicycle mobility the other is about RFID reader sensor)

24 Mar 2020 13:23:06,055 INFO  [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:324)  - [NGSIRestHandler] Received data ({"subscriptionId":"5e5d0eb8174a2b987fcdfc86","originator":"localhost","contextResponses":[{"contextElement":{"type":"BicyclePresenceObserved","isPattern":"false","id":"urn:ngsi-ld:BicyclePresenceObserved:eindhoven:bicycle:1000","attributes":[{"name":"bicyclePresence","type":"StructuredValue","value":{"eventId":"818002","eventTime":"2020-03-24T13:23:06.006+01:00","zoneId":"1","eventState":"Begin","eventIdBegin":""}},{"name":"location","type":"geo:json","value":{"type":"Point","coordinates":[5.503225756,51.432526826,0]}}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]})
24 Mar 2020 13:23:06,099 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:350)  - [NGSIRestHandler] Parsed NotifyContextRequest on legacy NGSI: {"subscriptionId":"5e5d0eb8174a2b987fcdfc86","originator":"localhost","contextResponses":[{"contextElement":{"id":"urn:ngsi-ld:BicyclePresenceObserved:eindhoven:bicycle:1000","type":"BicyclePresenceObserved","isPattern":"false","attributes":[{"name":"bicyclePresence","type":"StructuredValue","value":{"eventId":"818002","eventTime":"2020-03-24T13:23:06.006+01:00","zoneId":"1","eventState":"Begin","eventIdBegin":""},"metadatas":[]},{"name":"location","type":"geo:json","value":{"type":"Point","coordinates":[5.503225756,51.432526826,0]},"metadatas":[]}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]}
24 Mar 2020 13:23:06,099 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:376)  - [NGSIRestHandler] NGSI event created for ContextElementResponse: {"contextElement":{"id":"urn:ngsi-ld:BicyclePresenceObserved:eindhoven:bicycle:1000","type":"BicyclePresenceObserved","isPattern":"false","attributes":[{"name":"bicyclePresence","type":"StructuredValue","value":{"eventId":"818002","eventTime":"2020-03-24T13:23:06.006+01:00","zoneId":"1","eventState":"Begin","eventIdBegin":""},"metadatas":[]},{"name":"location","type":"geo:json","value":{"type":"Point","coordinates":[5.503225756,51.432526826,0]},"metadatas":[]}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}
24 Mar 2020 13:23:06,100 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:381)  - [NGSIRestHandler] Header added to NGSI event (fiware-service: bicycle_mobility)
24 Mar 2020 13:23:06,100 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:384)  - [NGSIRestHandler] Header added to NGSI event (fiware-servicepath: /Synchronicity/BicycleMobility/Eindhoven)
24 Mar 2020 13:23:06,100 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:387)  - [NGSIRestHandler] Header added to NGSI event (fiware-correlator: 98ab6aca-6dd2-11ea-b609-0242ac120003)
24 Mar 2020 13:23:06,100 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:390)  - [NGSIRestHandler] Header added to NGSI event (transaction-id: 1ec2813d-b1f3-4d07-9d6c-9dcfc954bb2c)
24 Mar 2020 13:23:06,101 DEBUG [1636229858@qtp-1974426263-0] (com.telefonica.iot.cygnus.handlers.NGSIRestHandler.getEvents:420)  - [NGSIRestHandler] NGSI events put in the channel, ids=2092998677
24 Mar 2020 13:23:31,625 DEBUG [conf-file-poller-0] (org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run:126)  - Checking file:/home/cygnus/APACHE_FLUME_HOME/conf/agent_1.conf for changes
24 Mar 2020 13:23:32,143 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches:496)  - Batch accumulation time reached, the batch will be processed as it is
24 Mar 2020 13:23:32,143 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches:559)  - Batch completed
**24 Mar 2020 13:23:32,144 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistBatch:123)  - [mongo-sink] Processing sub-batch regarding the bicycle_mobility_/Synchronicity/BicycleMobility/Eindhoven destination**
24 Mar 2020 13:23:32,146 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.aggregation.NGSIGenericColumnAggregator.aggregate:82)  - [NGSIUtils.GenericColumnAggregator] Processing context element (id=urn:ngsi-ld:BicyclePresenceObserved:eindhoven:bicycle:1000, type=BicyclePresenceObserved)
24 Mar 2020 13:23:32,147 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.aggregation.NGSIGenericColumnAggregator.aggregate:101)  - [NGSIUtils.GenericColumnAggregator] Processing context attribute (name=bicyclePresence, type=StructuredValue)
24 Mar 2020 13:23:32,147 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.aggregation.NGSIGenericColumnAggregator.aggregate:101)  - [NGSIUtils.GenericColumnAggregator] Processing context attribute (name=location, type=geo:json)
**24 Mar 2020 13:23:32,215 INFO  [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistAggregation:220)  - [mongo-sink] Persisting data at NGSIMongoSink. Database: sth_bicycle_mobility, Collection: null**, Data: [Document{{recvTime=2020-03-24 13:23:06.101, entityId=urn:ngsi-ld:BicyclePresenceObserved:eindhoven:bicycle:1000, entityType=BicyclePresenceObserved, bicyclePresence=Document{{eventId=818002, eventTime=2020-03-24T13:23:06.006+01:00, zoneId=1, eventState=Begin, eventIdBegin=}}, location=Document{{type=Point, coordinates=[5.503225756, 51.432526826, 0]}}}}]
24 Mar 2020 13:23:32,215 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.backends.mongo.MongoBackendImpl.createDatabase:85)  - Creating Mongo database=sth_bicycle_mobility
24 Mar 2020 13:23:32,460 INFO  [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.mongodb.diagnostics.logging.SLF4JLogger.info:71)  - Cluster created with settings {hosts=[127.0.0.1:27017], mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
24 Mar 2020 13:23:32,461 INFO  [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.mongodb.diagnostics.logging.SLF4JLogger.info:71)  - Adding discovered server 127.0.0.1:27017 to client view of cluster
24 Mar 2020 13:23:32,490 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.mongodb.diagnostics.logging.SLF4JLogger.debug:56)  - Updating cluster description to  {type=UNKNOWN, servers=[{address=127.0.0.1:27017, type=UNKNOWN, state=CONNECTING}]
**24 Mar 2020 13:23:32,505 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.backends.mongo.MongoBackendImpl.createCollection:165)  - Creating Mongo collection=null at database=sth_bicycle_mobility**
**24 Mar 2020 13:23:32,510 ERROR [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches:573)  - CygnusPersistenceError. -, collectionName can not be null**. Stack trace: [com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistAggregation(NGSIMongoSink.java:228), com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistBatch(NGSIMongoSink.java:146), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:563), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:371), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147), java.lang.Thread.run(Thread.java:748)]
24 Mar 2020 13:23:32,510 INFO  [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.NGSISink.doRollback:636)  - Rollbacking (98ab6aca-6dd2-11ea-b609-0242ac120003), 10 retries will be done

After many tests I analyzed the code and detected that in the file NGSIMongoSink.java (cygnus-ngsi - com.telefonica.iot.cygnus.sinks) it seems that in the persistBatch(...) function there is an error.
Instead to use aggregator.setCollectionName(...) you used aggregator.setTableName(...) (line 138, col 13).

    void persistBatch(NGSIBatch batch) throws CygnusBadConfiguration, CygnusPersistenceError {
        ...
        ...

        while (batch.hasNext()) {
            ...
            ...
            ...
            // get an aggregator for this destination and initialize it
            NGSIGenericAggregator aggregator = getAggregator(rowAttrPersistence);
            ...
            ...
            aggregator.setTableName(buildCollectionName(aggregator.getServicePathForNaming(), aggregator.getEntityForNaming(), aggregator.getAttribute()));
            aggregator.initialize(events.get(0));
            ...
            ...
        } // for
    } // persistBatch

Then I replaced the bad call aggregator.setTableName(...) by aggregator.setCollectionName(buildCollectionName(aggregator.getServicePathForNaming(), aggregator.getEntityForNaming(), aggregator.getAttribute()));

    void persistBatch(NGSIBatch batch) throws CygnusBadConfiguration, CygnusPersistenceError {
        ...
        ...

        while (batch.hasNext()) {
            ...
            ...
            ...
            // get an aggregator for this destination and initialize it
            NGSIGenericAggregator aggregator = getAggregator(rowAttrPersistence);
            ...
            ...
            aggregator.setCollectionName(buildCollectionName(aggregator.getServicePathForNaming(), aggregator.getEntityForNaming(), aggregator.getAttribute()));
            aggregator.initialize(events.get(0));
            ...
            ...
        } // for
    } // persistBatch

I generated the cygnus-ngsi JAR and installed it in my cygnus instance (/home/cygnus/APACHE_FLUME_HOME/plugins.d/cygnus/lib).

Now it seems to work fine. There is no error raised, the collection is correct and the corresponding data collection are store as Document in the mongo database (checked using mongo client) and now I can make find() queries on attributes and objects (StructuredValue and arrays)

See below an extract of the log after this correction where the data are now correctly stored without errors and in the correct format (Document).

Attached file: [extract-cygnus-log-after_correction.txt](https://github.com/telefonicaid/fiware-cygnus/files/4376723/extract-cygnus-log-after_correction.txt)

Notice that there is a Trace Dump of the Mongo Exception during trying to create the collection due because the collection already exist and this is not a real error.

I suppose that this just to see that the collection already exist and there no need to create it.

**Comment by srrspace** [comment]
I have a question, I am wonder, if now the data are stored as object in the Cygnus mongodb database.

Could there be an impact on the other components connected to Cygnus like STH_Comet or CKAN or others?

I am not sure how these components (STH_Comet or CKAN) are connected to Cygnus and how they get the data from Cygnus.

If these components get the data through the database instead of using notification mechanisms,  where the notified data are in NGSI v2 format (in this case there should be no problems), but there could be issues with these components that could expect this data as String instead of objects (Documents) and not know how to interpret them correctly or not having the queries correctly against these documents stored.

What do you think about this question and possible impact or issues on STH_Comet and/or CKAN?

Makes sense or not?

**Comment by IvanHdzC** [comment]
That's actually a great question @srrspace.

You see, the goal for the generic aggregation task was to simplify and unify the process of managing data inside each sink once data is taken from the flume channel. 

The process of how data is stored into the persistance manager is attended by each sink itself. So de Document format is used only by mongo sink, there is no issue regarding to this with CKAN or any other sink. 

Now. With the generic aggregation task, there was some optimization (like document managing for mongo) for each sink. In CKAN sink the data now is managed as JsonObjects (gson) so the json output can be built without Strings. So there shouldn`t be any issue regarding mongo Documents on this sink.

STH was out of the scope for this task, so it is working as usual.

About the issue you mentioned, We'll soon correct it.

Hope this answers your question.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/1846 should solve the issue.

@srrspace could you test it (in master) and check it, please? In positive case, please close the issue. In negative case, please provide extra feedback that allow us to improve the fix. Thanks!

**Comment by srrspace** [comment]
I tested this PR based on master and all works fine, no error appear and the data are store as documents.
I confirm this PR solve the issue and can be closed.
I will do it myself

Thanks!!
