### ISSUE TITLE
connect to SQL Server (like MySQL, PostgreSQL) by using SSL or TLS

### ISSUE THREAD

**Issue by nmatsui** [telefonicaid/fiware-cygnus#1867]
When I want to use secure MySQL or secure PostgreSQL, I have to add some additional parameter(s) to JDBC url of Cygnus like below:
* jdbc:mysql://mysql.example.com:3306/fiwareservice<b>?useSSL=true&requireSSL=false</b>
* jdbc:postgresql://postgres.example.com:5432/postgres<b>?sslmode=require</b>

But the current Implement ([SQLBackendImpl](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/sql/SQLBackendImpl.java)) has no ability to set additional parameter(s) to JDBC url.

So I update [SQLBackendImpl](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/sql/SQLBackendImpl.java) and [NGSIMySQLSink](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMySQLSink.java), [NGSIPostgreSQLSink](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgreSQLSink.java) and [NGSIPostgisSink](https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java) to be able to accept additional jdbc parameter(s).

**Comment by fgalan** [comment]
Fixed in PR #1868
