### ISSUE TITLE
Clean the code to work for CKAN 2.2 without the "2.0 patch"

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#188]
Currently the code does an extra operations to be compatible with CKAN 2.0. That operation adds ineficiency in the case of only using 2.2 (as is the requirement for IoTPlatform).

Thus, eventually, we should clean the code to remove that.

**Effort: 1 man day**

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/500
