### ISSUE TITLE
docker log into stdout 

### ISSUE THREAD

**Issue by IvanHdzC** [telefonicaid/fiware-cygnus#1886]
Currently Cygnus logs into a file which outputs through a tail. It should log directly to stdout.

**Comment by AlvaroVega** [comment]
In case of cynus keep log into files is very usefull to allow third parties debug

**Comment by AlvaroVega** [comment]
close by https://github.com/telefonicaid/fiware-cygnus/issues/1962 and  https://github.com/telefonicaid/fiware-cygnus/pull/1989
