### ISSUE TITLE
OrionSTHSink

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#19]
Implement another sink for MongoDB and test it along with the Cosmos sink, e.g. run the program with 2 sinks activated and check that when a notifyContextRequest arrives it is persisted in both places, check if Flume can implement "all or nothing" semantics (i.e. if one of the sinks is offline, for instance the connection to MongoDB is broken, then the notifyContextRequest is not persisted in Cosmos), etc.

**Comment by frbattid** [comment]
I've changed the name of this issue to "OrionSTHSink" since it is clear that a sink for the Short-Term Historic of Orion CB has to be created; independently of the underlying technology used for that (Mongo, LevelDB, InfluxDB, Open TSDB, flat files... who knows :)).

**Comment by fgalan** [comment]
However, if the technology to implement STH is **not** MongoDB, an issue about "OrionMongoSink" will still making sense (not sure if this one remaned back or a different new one). Have been the STCH technology chosen?

**Comment by frbattid** [comment]
It has not been chosen, really. But the idea behind the original "orion2mongo sink" was to suppert the STH,thus I though it was better to rename it... Nevertheless, I agree maybe in the future a OrionMongoSink issue is necessary if we want to mimic the behaviour of OrionHDFSSink in a Mongo-based fashion... well, I do not know what to do now :)

**Comment by gtorodelvalle** [comment]
Hi guys! This is the document we have been working on regarding the storing of the STH aggregated data in MongoDB: https://docs.google.com/document/d/1XUNT9IfRaFosP8Twlnw83CXiLNzuukcxglg-bCvH6QI
It will be used as the base for the implementation of this issue.

**Comment by gtorodelvalle** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/377 ;)
