### ISSUE TITLE
Post in JSON format to CKAN

### ISSUE THREAD

**Issue by RobertoGallegoDelgado** [telefonicaid/fiware-cygnus#1903]
Cygnus is currently capable of publishing Context Broker content automatically only in CSV format on a CKAN portal.

We require the automatic posting of Context Broker information also in JSON format to a CKAN portal.

**Comment by manucarrace** [comment]
Cygnus uses CKAN standard API and there is no way to specify the representation format in CKAN. Representation of data is done at CKAN. It depends on ckan plugins and extensions.
