### ISSUE TITLE
Cygnus error while persisting on MySQL

### ISSUE THREAD

**Issue by IvanHdzC** [telefonicaid/fiware-cygnus#1907]
Cygnus is throwing this error when trying to persist on MySQL.

CygnusRuntimeError (SQLException). MYSQL Objects closing error (Already closed.). Stack trace: [com.telefonica.iot.cygnus.backends.sql.SQLBackendImpl.closeSQLObjects(SQLBackendImpl.java:436), com.telefonica.iot.cygnus.backends.sql.SQLBackendImpl.insertContextData(SQLBackendImpl.java:217), com.telefonica.iot.cygnus.sinks.NGSIMySQLSink.persistAggregation(NGSIMySQLSink.java:372), com.telefonica.iot.cygnus.sinks.NGSIMySQLSink.persistBatch(NGSIMySQLSink.java:284), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:569), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:371), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147), java.lang.Thread.run(Thread.java:748)]

**Comment by fgalan** [comment]
PR #1908 

Should this issue be closed?
