### ISSUE TITLE
Log (info) about NameMapping applied

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1937]
Si hay NM hay que decir el resultado del NM matcheado 
        si matchea 
           (si se puede con que ha mapeado)
        si no hay machea
          (ver si sale la traza o no)
       
     
     Si NO hay NM que no diga nada de new body
        ( o no hay fichero, decir que no hay NM)

most of changes will be done at https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/interceptors/NGSINameMappingsInterceptor.java

**Comment by fgalan** [comment]
Fixed by PR #1961. Should this issue be closed?
