### ISSUE TITLE
Log about element batched

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1938]
How log a new batch (and all or their elements):

Discuss and select better option:
- new Id for batch (will be also a new transactionid)
- list of correlator_id or each element

Take into account:
 https://github.com/telefonicaid/fiware-cygnus/issues/1770
 https://github.com/telefonicaid/fiware-cygnus/pull/1800

**Comment by fgalan** [comment]
A third one, combining both:

* new id for batch (in coorid= field) + a list of correlator_id of each element (within msg=)

**Comment by AlvaroVega** [comment]
this issue depends on works of https://github.com/telefonicaid/fiware-cygnus/issues/1936

**Comment by AlvaroVega** [comment]
related PR https://github.com/telefonicaid/fiware-cygnus/pull/1970#event-3926819776

**Comment by fgalan** [comment]
> 
> 
> related PR [#1970 (comment)](https://github.com/telefonicaid/fiware-cygnus/pull/1970#event-3926819776)

Does the PR fully solve the issue? Or is there something pending?
