### ISSUE TITLE
Log about persisted data

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1939]
Log "persisting data" -> must be DEBUG including SQL text used
  This happens before data is persisted.
  - SQL text should be ready for cut & paste in SQL console

A New log about "Persisted data using following SQL " must be produced when "finish internal transaction" in INFO, when data was persisted.
  - SQL text should be ready for cut & paste in SQL console

**Comment by AlvaroVega** [comment]
Partially done in https://github.com/telefonicaid/fiware-cygnus/pull/1942

**Comment by fgalan** [comment]
Finished by PR #1958? Should the issue be closed?
