### ISSUE TITLE
Cygnus-Postgis

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/fiware-cygnus#1966]
Hello
I have tried to use a Cygnus with PostGis Sink.
When I have edited the configuration file, I cannot set the database name in postgis sink.

How can I configure the database name in agent.conf file?

I have assumed that the postgis sink use the default database named postgres and I have created a Schema and table like I want to save.

the error is below: 
````
(ERROR: relation "dbtest.tabletest" does not exist
  Position: 13)
``````
I have read every documentation in this repo and I have not found something about Postgis configuration.

**Comment by fgalan** [comment]
The issue has been closed. I understand you finally solved it. Nice :)

However, it would be great if you could provide a comment on how you solved it. That could be valuable information for users in a similar situation.
