### ISSUE TITLE
Error inserting an element of batch is causing lost of all batch 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1967]
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISink.java#L570

**Comment by AlvaroVega** [comment]
Analize if upsert + batch is only inserting first event, but no rest of them

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/1970
