### ISSUE TITLE
Optimize index creation logic

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#1975]
For STH-based sinks, Cygnus attemps to create indexes in every insertion. This can be optimized in the following way:

* Cygnus keeps a memory data structure with all the indexes created so far (let's call it "indexes list"). At startup time, the indexes list is empty
* Whenever Cygnus attemps to create an index, first it checks if the index is already in the indexes list.
    * If yes, it does nothing
    * If no, it creates the index in Mongo and adds it to the indexes list
* Priodically, after some time, the indexes list is flushed. This is a caution measure in the case some index is droped in the DB out of band (i.e. a manual removal of the index on the mongo shell). This time can be configured, including the values for "not use" (i.e. not use a index list and works as now) and "never" (i.e. the index list is never flushed)

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/fiware-cygnus/issues/1974

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/fiware-cygnus/blob/888d745f685c8880c6416ed18a1e0f75ff9dd458/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L121

**Comment by AlvaroVega** [comment]
In all cases  createIndex is called into createCollection.

After some improvements like https://github.com/telefonicaid/fiware-cygnus/pull/2031/ createCollection is only called once time, just when createIndex should be performed.

**Comment by fgalan** [comment]
Do you mean this issue is already solved in the code and could be closed? Or is there anything pending?

**Comment by AlvaroVega** [comment]
we can close it

**Comment by fgalan** [comment]
I've added to the CNR in PR https://github.com/telefonicaid/fiware-cygnus/pull/2050 (hoping in the righ tline :)
