### ISSUE TITLE
Add Cygnus-LD to automated builds

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/fiware-cygnus#1976]
This functionality was Identified as missing in #1963, however as part of the review it was decided to split the Docker Hub automated build part out of from the original PR. This issue acts as a placeholder to ensure ~the  `post-build` and~ `build` bash scripts are added in a more appropriate place within the Telefonica infrastructure.

#### `build`

```bash
cd ../../
docker image build --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
	--label "org.opencontainers.image.created"=$(date +%Y-%m-%d) \
	--label "org.opencontainers.image.revision"=$SOURCE_COMMIT \
	--label "org.opencontainers.image.version"=$DOCKER_TAG \
	-f docker/cygnus-ngsi-ld/Dockerfile \
	-t $IMAGE_NAME-ld \
	.
```

#### `post-build`

```bash
docker image push $IMAGE_NAME-ld 
```

**Jason:**
> @IvanHdzC - I agree docker/cygnus-ngsi/hooks/build and docker/cygnus-ngsi/hooks/post-push may need moving
> elsewhere, but since I have no visibility of your Docker Hub infrastructure I can't work out where. The point is that the 
> Cygnus-LD needs building somehow.
> 
> Maybe just replace this change on your own PR and close this? I'll leave the branch up for now.

**Ivan:**

> Ok, @jason-fox could you please remove both post-build and new build from your branch/PR so we can accept and merge > the labels changes please?
>
> After that we can build the new image.

**Comment by fgalan** [comment]
Cygnus-LD is build automatically in dockerhub repository https://hub.docker.com/r/telefonicaiot/fiware-cygnus-ld. We haven't needed any extra hook file to achieve that.

In understand that the same can be done by any other dockerhub organization (e.g. fiware/) just pointing to the github.com Cygnus repository, without any extra hook file. Thus, this issue could be now closed. What do you think?

**Comment by jason-fox** [comment]
Yes the image is building, but without the build hooks some of the `org.opencontainers.*` metadata `LABELS` are **still missing**.

e.g:

```console
docker pull telefonicaiot/fiware-cygnus-ld 
docker inspect telefonicaiot/fiware-cygnus-ld
```

```json
"Labels": {
    "maintainer": "Cygnus Team. Telefónica I+D",
    "org.label-schema.build-date": "20181204",
    "org.label-schema.license": "GPLv2",
    "org.label-schema.name": "CentOS Base Image",
    "org.label-schema.schema-version": "1.0",
    "org.label-schema.vendor": "CentOS",
    "org.opencontainers.image.authors": "iot_support@tid.es",
    "org.opencontainers.image.description": "A connector in charge of persisting context linked data sources into other third-party databases and storage systems, creating a historical view of the context",
    "org.opencontainers.image.documentation": "https://fiware-cygnus.rtfd.io/",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.source": "https://github.com/telefonicaid/fiware-cygnus",
    "org.opencontainers.image.title": "Cygnus-LD Data Persistence",
    "org.opencontainers.image.vendor": "Telefónica Investigación y Desarrollo, S.A.U"
  }
```

Now the `org.label-schema` are coming from the base image, but `org.opencontainers.image.version` and `org.opencontainers.image.created` are missing.


Compare this with an IoT Agent where ` "org.opencontainers.image.created": "2020-10-20",` and `"org.opencontainers.image.version": "latest"` are present:

```console
docker pull fiware/iotagent-ul
docker inspect fiware/iotagent-ul
```

```json
"Labels": {
    "maintainer": "FIWARE IoTAgent Team. Telefónica I+D",
    "org.nodejs.version": "10.22.1",
    "org.opencontainers.image.authors": "iot_support@tid.es",
    "org.opencontainers.image.created": "2020-10-20",
    "org.opencontainers.image.description": "An Internet of Things Agent for the Ultralight 2.0 protocol (with AMQP, HTTP and MQTT transports). This IoT Agent is designed to be a bridge between Ultralight and the NGSI interface of a context broker.",
    "org.opencontainers.image.documentation": "https://fiware-iotagent-ul.rtfd.io/",
    "org.opencontainers.image.licenses": "AGPL-3.0-only",
    "org.opencontainers.image.revision": "d0698fad9a0880edcbdf2cc23ba775d81c3f51c1",
    "org.opencontainers.image.source": "https://github.com/telefonicaid/iotagent-ul",
    "org.opencontainers.image.title": "IoT Agent for the Ultralight 2.0 protocol",
    "org.opencontainers.image.vendor": "Telefónica Investigación y Desarrollo, S.A.U",
    "org.opencontainers.image.version": "latest"
  }
```

**Comment by fgalan** [comment]
Thanks for the clarification!

So, makes sense for this issue to stay while the pending LABELs are completed. Maybe the author of the NGIS-LD contribution to Cygnus could take care of it. What do you think @anmunoz  ?

**Comment by anmunoz** [comment]
Yes, it sounds feasible

**Comment by fgalan** [comment]
After closing #1998, should this issue (#1976) be closed? Or is anything pending on it?
