### ISSUE TITLE
Ckan attr_metadata_store cant be configure via env vars

### ISSUE THREAD

**Issue by JuanCarlosSecmotic** [telefonicaid/fiware-cygnus#1991]
I need to set _"cygnus-ngsi.sinks.ckan-sink.attr_metadata_store = false"_  via environment variables, but can't find a way to do it.

it's posible? 

thanks

**Comment by fgalan** [comment]
This is more a question about functionality than a issue/bug in the software. Thus, it would be better to use https://www.stackoverflow.com for this. Could you post it there, please? Use the "fiware-cygnus" label.

Once published in SOF, add the link to this issue. Then, close the issue.

Thanks!

**Comment by JuanCarlosSecmotic** [comment]
https://stackoverflow.com/questions/65850361/ckan-attr-metadata-store-cant-be-configure-via-env-vars
