### ISSUE TITLE
Disable hostname validation for arcgis 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#1992]
https://github.com/telefonicaid/fiware-cygnus/blob/dddb13e3b5206e225acfb7aeb3b033e7acd315df/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/arcgis/restutils/RestApi.java#L173-L174

**Comment by AlvaroVega** [comment]
https://nakov.com/blog/2009/07/16/disable-certificate-validation-in-java-ssl-connections/

**Comment by fgalan** [comment]
Having merged PR https://github.com/telefonicaid/fiware-cygnus/pull/1993, should this issue be closed?

**Comment by cesarjorgemartinez** [comment]
Yes, but for a print an adviced, in one site at documentation, better specify that with this issue, always connect to ArcGIS host using insecure form

**Comment by fgalan** [comment]
> Yes, but for print an adviced, in one site at documentation, better specify that with this issue, always connect to ArcGIS host using insecure form

Thus, let's keep this issue opened while documentation is adjusted that way.

**Comment by mrutid** [comment]
Shall we close the issue then?

**Comment by fgalan** [comment]
> 
> 
> Shall we close the issue then?

Agree. Closing.

@cesarjorgemartinez if you think something else is missing, please tell us, so we can reopen it (or create a new issue focused on what is missing)
