### ISSUE TITLE
sink postgis/postgres bad destination using DM_BY_ENTITY_DATABASE and several clients

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2004]
time=2021-03-22T07:51:42.687Z | lvl=ERROR | corr=713732c4-8ae3-11eb-96f0-fa163e83ea20; cbnotif=1 | trans=e88d632d-9a1f-4963-9e82-31eb41c67f3c | srv=<serv1> | subsrv=/<subserv1> | op=processNewBatches | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSISink[610] : BadContextData (SQLException). POSTGRESQL Data insertion error. Query: insert into `sensor_any_noiselevelobserved` (recvTime,fiwareServicePath,entityId,entityType,LAeq,LAeq_md,dateObserved,dateObserved_md,name,name_md,location,location_md,source,source_md) values ('2021-03-22 07:51:40.913','/sonometros','T248670','NoiseLevelObserved','061.4','[]','2021-03-22T07:51:18Z','[]','Sensor2 ','[]',ST_SetSRID(ST_MakePoint(-0.38288599999999406::double precision , 32.4613005::double precision ), 4326),'[]','CESVA','[]') (ERROR: relation "<serv2>.sensor_any_noiselevelobserved" does not exist

Probably wrong destination is selected:
https://github.com/telefonicaid/fiware-cygnus/blob/269af1d412db8220dce26def52e4e2c004308e49/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/sql/SQLBackendImpl.java#L943

postgresql/postgis is using  destination for schemaname and dbname, but both should be spltited and propagated from https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java#L432

Logs should print all dbname, schema, tablename
https://github.com/telefonicaid/fiware-cygnus/blob/master/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java#L442

PostgreSQL databases naming, schemas, tablename conventions
https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_postgresql_sink.md#postgresql-databases-naming-conventions

**Comment by fgalan** [comment]
Having merged PR #2007, should this issue be closed?
