### ISSUE TITLE
Wrong insertion policy at MongoSink

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/fiware-cygnus#2019]
Wrong insertion policy at MongoSink at 
https://github.com/telefonicaid/fiware-cygnus/blob/24e235bf1511e413145e7bc2f96ab213cbc0eb92/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMongoSink.java#L246

```try {
            backend.createDatabase(dbName);
            backend.createCollection(dbName, collectionName, collectionsSize, maxDocuments, dataExpiration);
            backend.insertContextDataRaw(dbName, collectionName, aggregation);
        } catch (Exception e) {
            throw new CygnusPersistenceError("-, " + e.getMessage());
        } // try catch
```

Seems we are "creating" DataBase and Collection on every agg insertion. Weird.

Try to insert and then create a DataBase and Collection in case of error seems more accurate.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2031
