### ISSUE TITLE
MongoSink. Cast to Date NGSI DateTime attributes in colum mode.

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/fiware-cygnus#2020]
it is mandatory to insert into Mongo as ISO DATES the DateStrings values from DateTime attributes in the NGSI-event.

MongoCollection.insertMany seems to be able to manage properly Java Date Objects.

**Comment by AlvaroVega** [comment]
Maybe related: 
https://github.com/telefonicaid/fiware-cygnus/commit/43278a76707e973296e842ba35c05bec052fe82e
https://github.com/telefonicaid/fiware-cygnus/commit/4b393abbad1668ae597931bf79411c7df816c1db

**Comment by AlvaroVega** [comment]
![midato](https://user-images.githubusercontent.com/983422/117408057-b02c5e00-af0f-11eb-8830-0d1743931d92.png)

midato was inserted as DateTime

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2021

Although maybe we should have this issue opened for a while to do some testing with the new version...

**Comment by cesarjorgemartinez** [comment]
This bug is resolved in release 2.9.0? Because not see closed...
