### ISSUE TITLE
improves error with a bad url in mongo-sink 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2046]
cygnus-ngsi.sinks.sth-sink.mongo_hosts = iot-mongo 

instead of 

cygnus-ngsi.sinks.sth-sink.mongo_hosts = iot-mongo:27017

time=2021-05-24T10:34:13.567Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=createDatabase | msg=com.telefonica.iot.cygnus.backends.mongo.MongoBackendImpl[91] : Creating Mongo database=sth_smartcity
time=2021-05-24T10:34:13.568Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processRollbackedBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[418] : CygnusPersistenceError. -, 1. Stack trace: [com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistAggregation(NGSIMongoSink.java:292), com.telefonica.iot.cygnus.sinks.NGSIMongoSink.persistBatch(NGSIMongoSink.java:149), com.telefonica.iot.cygnus.sinks.NGSISink.processRollbackedBatches(NGSISink.java:402), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:375), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:67), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145), java.lang.Thread.run(Thread.java:748)]

**Comment by AlvaroVega** [comment]
lhttps://github.com/telefonicaid/fiware-cygnus/blob/10f5751002d85ace0bf050af2379dc280c48ec71/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/mongo/MongoBackendImpl.java#L551-L554

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/2047
