### ISSUE TITLE
Cygnus seems to be mixing data from different devices when generates aggregates through STH_Commet sink.

### ISSUE THREAD

**Issue by sergiorb** [telefonicaid/fiware-cygnus#2048]
I've been testing `cygnus:2.7.0`, `orion:2.5.0` with `fiware/iotagent-ul:latest` and seems to happen this. I've set up a repository to reproduce the behavior [https://github.com/sergiorb/cygnus-issue-8f7f9e95359f](https://github.com/sergiorb/cygnus-issue-8f7f9e95359f).

- Aggregates generation stops for first device when second device emulator starts.
- Values of both emulators go to the aggregates of the second device.

Would you have a look at it?

Thanks in advance.

**Comment by AlvaroVega** [comment]
Thanks for your report. I'm going to take a look.

**Comment by AlvaroVega** [comment]
I've being running your tests (with mongo 4.4.6, and orion and cygnus latests) and these are the results:
[rest_foo_000.txt](https://github.com/telefonicaid/fiware-cygnus/files/6546164/rest_foo_000.txt)
[rest_foo_001.txt](https://github.com/telefonicaid/fiware-cygnus/files/6546165/rest_foo_001.txt)
But i'm not sure how different data are for foo_000 and for foo_001

**Comment by sergiorb** [comment]
@AlvaroVega thank you for your quick response. 

If you look carefully, you will notice that in `rest_foo_000.txt` dataset, starting from `offset:41`, data is generated with different `min/max` values and a `samples` count of 7. I guess that you have executed `./run.sh` more than twice so that is the reason the test starts with such value. If you start from scratch and execute `./start.sh` you should observe that `min/max` values are the same **until** the second emulator start running. Furthermore, samples count should go from 1 to 2. 
After that, values are generated in the same way until the second emulator starts around `offset:47`. If you look now in the `rest_foo_001.txt` dataset, you will find that the values starts around the same `offset:47` and the samples number in every offset is increased by 1 (`7 -> 8`). In addition of that, the second dateset aggregates are generated only in  47, 49, 51 and 56 offsets, which seems weird.

I would expect aggregates to keep being generated apart from each other? Wouldn't I?

**Comment by sergiorb** [comment]
I think something is still wrong with your setup. If you check `end_foo_000.txt` dataset, samples increased to 48 (offset:34). May you check if you have running emulators in the background? If so, kill them and execute `./remove.sh` and then `./start.sh`. It will take some time and after it finish, you can check the mongodb data. I've updated the README file to clarify that.

**Comment by AlvaroVega** [comment]
Anyway , these are my new results:
Before execution
[init_foo_000.txt](https://github.com/telefonicaid/fiware-cygnus/files/6551674/init_foo_000.txt)
[init_foo_001.txt](https://github.com/telefonicaid/fiware-cygnus/files/6551672/init_foo_001.txt)

After execution:
[end_foo_000.txt](https://github.com/telefonicaid/fiware-cygnus/files/6551671/end_foo_000.txt)
[end_foo_001.txt](https://github.com/telefonicaid/fiware-cygnus/files/6551675/end_foo_001.txt)

**Comment by sergiorb** [comment]
Well, I see that you almost reproduced the conditions as the values are coincident at the beginning and mismatch when the second emulators starts. I don't know why your sample count starts in 5.

At any case, is the expected behavior to mix data between devices? If each emulator send a value each minute, I would expect no differences in min/max keys in each point offset, wouldn't I? In addition of that, I understand that aggregates generation for device "foo_000" should not stop as it does.

**Comment by AlvaroVega** [comment]
Did was the logs of cygnus during the test:
[log_cygnus.txt](https://github.com/telefonicaid/fiware-cygnus/files/6551934/log_cygnus.txt)
Do you recognize in that (searching by `foo_00`) where cygnys is inserting mixing data from foo_000 and foo_001?
It's difficult to me find that since data sent by foo_000 and foo_001 are quite similar, aren't they?

**Comment by sergiorb** [comment]
I've updated the emulators to work in different value ranges. I've uploaded a result example too:
- [foo_000](https://github.com/sergiorb/cygnus-issue-8f7f9e95359f/blob/main/docs/aggregates_example_foo_000.txt): 50 <-> 150
- [foo_001](https://github.com/sergiorb/cygnus-issue-8f7f9e95359f/blob/main/docs/aggregates_example_foo_001.txt): 4950 <-> 5050

**Comment by AlvaroVega** [comment]
excellent report! @sergiorb

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/2049

@sergiorb it would be great if you could test the fix (it should be available in `telefonicaiot/fiware-cygnus:latest` container at the present moment) and provide feedback about it in this issue, please.

**Comment by sergiorb** [comment]
@fgalan I've tested it with `telefonicaiot/fiware-cygnus:latest (bae6c3e7a6f5)` and seems to work correctly. :smile: 
[aggregates_example_foo_000.fixed.txt](https://github.com/telefonicaid/fiware-cygnus/files/6570074/aggregates_example_foo_000.fixed.txt)
[aggregates_example_foo_001.fixed.txt](https://github.com/telefonicaid/fiware-cygnus/files/6570076/aggregates_example_foo_001.fixed.txt)

**Comment by fgalan** [comment]
Thanks for the feedback!

Based on it, we are going to close the issue.
