### ISSUE TITLE
BUG Connection error in Cygnus CKAN when it's behind a proxy web serving the API in one uri

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-cygnus#2072]
BUG Connection error in Cygnus CKAN when it's behind a proxy web serving the API in one uri

Example CKAN https://myckan.org/data
Serving the API in https://myckan.org/data/api/...
curl https://myckan.org/data/api/rest/dataset

Then if:
```
cygnus-ngsi.sinks.myckan-sink-ckan.ckan_host = myckan.org/data
cygnus-ngsi.sinks.myckan-sink-ckan.ckan_port = 443
```

Fails because try to use: https://myckan.org/data:443/api/......

Then if:
```
cygnus-ngsi.sinks.myckan-sink-ckan.ckan_host = myckan.org/data
# cygnus-ngsi.sinks.myckan-sink-ckan.ckan_port = 443
```

Fails because try to use: https://myckan.org/data:80/api/......

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2073
