### ISSUE TITLE
upsert log error is not showing last sql error sentence 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2088]
it's just printing last sql right sentence

https://github.com/telefonicaid/fiware-cygnus/blob/da3ab734742437352d18781a1852e82e07b4400e/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/sql/SQLBackendImpl.java#L641-L661

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2089
