### ISSUE TITLE
New data models dm-by-entity-type-database and dm-by-entity-type-database-schema for PostgreSQL/Postgis

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#2142]
In the same way we have the data models dm-by-entity-database-schema and dm-by-entity-database, we need to have two new data models:
- dm-by-entity-type-database
- dm-by-entity-type-database-schema

**dm-by-entity-type-database**: 
- database: \<fiware-service\>
- schema: \<fiware-service\>
- table_name: \<fiware-servicePath\>_\<entityType\> 

**dm-by-entity-type-database-schema**: 
- database: \<fiware-service\>
- schema: \<fiware-servicePath\>
- table_name:  \<fiware-servicePath\>_\<entityType\>

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2143
