### ISSUE TITLE
MONGO sink is inserting without use config for create collection like expiration_date

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2156]
Since mongo is able to insert even if collection does not exist (then mongo creates it) create collecction methods of mongo sinks where expiration date and others are especified are not applying.

**Comment by AlvaroVega** [comment]
Mongo sink:

(https://github.com/telefonicaid/fiware-cygnus/blob/bb2b344b20b2b9dce7b76f254b76fad975bde783/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMongoSink.java#L288-L289)


STH sink
https://github.com/telefonicaid/fiware-cygnus/blob/bb2b344b20b2b9dce7b76f254b76fad975bde783/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSISTHSink.java#L375-L376


Since cygnus 2.10:
[cygnus-ngsi][MongoSink][STHSink] Try to not create database and collection in each insertion (https://github.com/telefonicaid/fiware-cygnus/issues/2019, https://github.com/telefonicaid/fiware-cygnus/issues/1975)

**Comment by AlvaroVega** [comment]
https://stackoverflow.com/questions/72056471/insert-with-error-on-non-existing-collection-semantics

**Comment by AlvaroVega** [comment]
My first approach to fix this issue would be delete first try-catch block
https://github.com/telefonicaid/fiware-cygnus/blob/bb2b344b20b2b9dce7b76f254b76fad975bde783/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIMongoSink.java#L287-L290

Since list collection introduces the same load which try create  collection each time.

**Comment by fgalan** [comment]
Fixed in PR #2157
