### ISSUE TITLE
wrong subservice in aggegation framework?

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2185]
Possible bug to analize:

Given a destination in some sinks (SQL, CKAN...)

https://github.com/telefonicaid/fiware-cygnus/blob/e42dd616a07bb6e7766266cf7dce0ba85109636e/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIPostgisSink.java#L373

but that subsservice could be different in each event of the same destination

**Comment by AlvaroVega** [comment]
With a name mapping like:

{
"originalService": "smartcity",
"newService": "newcity",
"servicePathMappings": [
   {
      "originalServicePath": "/gardens",
      "newServicePath": "/",
      "entityMappings": [
          {
             "originalEntityId": "(.+)",
             "newEntityId": "dumps",
             "originalEntityType": "Device",
             "newEntityType": "Device",
             "attributeMappings": []
          } 
      ]
   },
  {
      "originalServicePath": "/roads",
      "newServicePath": "/",
      "entityMappings": [
          {
             "originalEntityId": "(.+)",
             "newEntityId": "dumps",
             "originalEntityType": "Device",
             "newEntityType": "Device",
             "attributeMappings": []
          } 
      ]
   }
]
}

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2186

Should this issue be closed now that the PR has been merged?

**Comment by fgalan** [comment]
Cygnus 2.20.0 has been released. Closing issue.
