### ISSUE TITLE
new datamodel for postgresql

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2190]
tablename: id + type ( without subservice)

schema:   subservice 
  
dattabase: servoce

**Comment by mrutid** [comment]
It could be an evolution of DM_entity_type

tablename: id + type ( without subservice)
schema: subservice
dattabase: service
+ Grouping by Type.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2191
