### ISSUE TITLE
Create a new SQL Sinks for Oracle Databases (11.2.0.4.0)

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/fiware-cygnus#2195]
Create a new SQL Sink for Oracle Database AND Oracle Spatial

**Comment by AlvaroVega** [comment]
https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc6/11.2.0.4

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2207
