### ISSUE TITLE
DM -schema family use an ugly underscore in the schema name

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#2201]
(Comes from PR https://github.com/telefonicaid/fiware-cygnus/pull/2196)

For instance, if we have `fiware-servicepath: /watercycle` in a `-schema` style DM the name of the schema in DB will be `_watercycle` instead of `watercycle`.

This is consistent with this part of the code, pe:

https://github.com/telefonicaid/fiware-cygnus/blob/aae3eb8ca471f2c3b5aca424c8c9175983aa7fc9/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/utils/NGSIUtils.java#L62-L63

but probably is unwanted.

This issue is about analysing this and change it. It seems `-schema` DM has not been widely use, so this probably has passed unnoticed until now.

DM summary table in doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_postgresql_sink.md should be modified if this is eventually fixed.

**Comment by Kajal-NEC** [comment]
@fgalan I'm interested to work on this issue.

**Comment by fgalan** [comment]
Great! Thanks for your willingness to work on this issue :)

Please go ahead and create the pull request as contribution.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2210
