### ISSUE TITLE
CygnusPersistenceError related to error table and expirating records

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2222]
time=2023-03-07T08:01:16.657Z | lvl=WARN | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | op=persistError | comp=Cygnus | msg=com.telefonica.iot.cygnus.backends.sql.SQLBackendImpl[847] : POSTGRESQL failed to persist error on database/scheme sc_salamanca_error_log com.telefonica.iot.cygnus.errors.CygnusPersistenceError: CygnusPersistenceError (SQLException). POSTGRESQL Table creation error (ERROR: syntax error at or near "."
Position: 28).
time=2023-03-07T08:01:16.657Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | op=run | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.NGSISink$ExpirationTimeChecker[1012] : [postgis-type-database-sink] Error while expirating records. Details: CygnusExpiratingError (CygnusPersistenceError). Data expiration error (CygnusPersistenceError (SQLException). POSTGRESQL Querying error (ERROR: syntax error at or near "`"
Position: 15). ).

**Comment by AlvaroVega** [comment]
maybe related or fixed by https://github.com/telefonicaid/fiware-cygnus/pull/2211  ?

**Comment by fgalan** [comment]
> maybe related or fixed by #2211 ?

I don't think so... that PR modifies the MongoDB backend, but the above traces show errors in PG persistence. Or maybe I'm missing something :)

**Comment by AlvaroVega** [comment]
closed by duplicated issue https://github.com/telefonicaid/fiware-cygnus/issues/2242
