### ISSUE TITLE
LastData Sinks (SQLBackend) should remove deleted entities

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/fiware-cygnus#2231]
Maybe with a flag at LastData SINK config, provided the NGSIv2 sub gives information regarding Entity Deletion it should be propagated to SQL repositories so Entities and registers remain synchronized

**Comment by fgalan** [comment]
Useful refs:

* https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/orion-api.md#subscriptions-based-in-alteration-type
* https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/orion-api.md#builtin-attributes (`alterationType` builtin)

**Comment by AlvaroVega** [comment]
Last Data current feature: https://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/flume_extensions_catalogue/last_data_function.html

**Comment by AlvaroVega** [comment]
New Attr received in subscription should not be stored, just used by lastData sinks

**Comment by AlvaroVega** [comment]
Example of event received by cygnus with an entityDelete (after delete a entity in orion):

time=2023-05-09T07:57:19.210Z | lvl=INFO | corr=bd678eff-bd84-4bd4-aa24-f76ff9e35508; cbnotif=1 | trans=ac681c4d-943c-4e9c-b04f-c7ebcf92d0e4 | srv=smartcity | subsrv=/ | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[327] : [NGSIRestHandler] Received data ({"subscriptionId":"6458d7f796c36cf539052b5a","data":[{"id":"thing:dispAB","type":"thing","TimeInstant":{"type":"DateTime","value":"2023-05-09T07:56:48.640Z","metadata":{}},"a":{"type":"num","value":null,"metadata":{}},"alterationType":{"type":"Text","value":"entityDelete","metadata":{}}}]})

**Comment by fgalan** [comment]
Issue in Orion repo: https://github.com/telefonicaid/fiware-orion/issues/4325
