### ISSUE TITLE
Delete mode

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/fiware-cygnus#2232]
It would be nice to have a new mode in which cygnus would be able to delete a row/document in a database. It may be based on the alterationType delivered by the notification (entityDelete).

- [ ] Postgis sink
- [ ] Postgres sink
- [ ] MySQL
- [ ] Mongodb

**Comment by fgalan** [comment]
Maybe this issue overlaps with https://github.com/telefonicaid/fiware-cygnus/issues/2231? Is a duplicate?

**Comment by manucarrace** [comment]
Closed with reference to https://github.com/telefonicaid/fiware-cygnus/issues/2231
