### ISSUE TITLE
Postgis . Data expiration error 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2242]
time=2023-05-24T14:17:32.300Z | lvl=ERROR | corr= | trans= | srv= | subsrv= | comp= | op=run | msg=com.telefonica.iot.cygnus.sinks.NGSISink$ExpirationTimeChecker[1014] : [postgis-type-database-sink] Error while expirating records. Details: CygnusExpiratingError (CygnusPersistenceError). Data expiration error (CygnusPersistenceError (SQLException). POSTGRESQL Querying error (ERROR: syntax error at or near "`"

Which values for  `persistence_policy` in sink are involved?

**Comment by AlvaroVega** [comment]
I guess sink should be configured with something similar to: 

cygnus-ngsi.sinks.postgis-sink.backend.enable_cache = true
cygnus-ngsi.sinks.postgis-sink.persistence_policy.max_records = 1
cygnus-ngsi.sinks.postgis-sink.persistence_policy.expiration_time = 10
cygnus-ngsi.sinks.postgis-sink.persistence_policy.checking_time = 10

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2245
