### ISSUE TITLE
Broken link in index.md

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/fiware-cygnus#2247]
I have found broken link at:
https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/index.md?plain=1#L49

**Comment by Keshav-NEC** [comment]
Hi, I am working on it.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2249, now merged.

@pooja1pathak please close the issue if you think all the broken links are now fixed.
