### ISSUE TITLE
Link for maven and flume in install_from_sources.md are not working

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/fiware-cygnus#2250]
Links given in [install_from_sources.md](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/installation_and_administration_guide/install_from_sources.md) for [apache-maven](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/installation_and_administration_guide/install_from_sources.md?plain=1#L30) and [apache-flume](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/installation_and_administration_guide/install_from_sources.md?plain=1#LL66C54-L66C66) are not working.

As per my understanding, URLs are not available and moved to some other path, same needs to be updated in doc also.

**Comment by Keshav-NEC** [comment]
Hi, I am working on it

**Comment by fgalan** [comment]
@pooja1pathak does PR #2253 (already merged) solves this issue? Or is there anything pending?

In the former case, please close the issue.

**Comment by Keshav-NEC** [comment]
Sure I'll do that. Thanks for the reply

**Comment by pooja1pathak** [comment]
> > Hi @fgalan , I want to ask if we can upgrade version of APACHE MAVEN and update the link of APACHE MAVEN. What's your opinion on this?
> 
> No sure what do you mean by this... could you do a PR showing the change, please?

@fgalan can we consider updated version in separate issue?

**Comment by fgalan** [comment]
> > > Hi @fgalan , I want to ask if we can upgrade version of APACHE MAVEN and update the link of APACHE MAVEN. What's your opinion on this?
> > 
> > 
> > No sure what do you mean by this... could you do a PR showing the change, please?
> 
> @fgalan can we consider updated version in separate issue?

Ok with me. Please create that issue an include it's URL as comment in the present one. Thanks!

**Comment by Keshav-NEC** [comment]
Thanks @fgalan for the suggestion.

**Comment by Keshav-NEC** [comment]
Raised issue #2272, @pooja1pathak, we can close this issue.
