### ISSUE TITLE
Fiware-ServicePath is used without / in quick_start_guide.md

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/fiware-cygnus#2260]
Fiware-ServicePath is used without / in :
https://github.com/telefonicaid/fiware-cygnus/blob/328ad2222cc854a73d13fd12618fc30cef0b2fde/doc/cygnus-ngsi/quick_start_guide.md?plain=1#L72

It should be "Fiware-ServicePath: /testsink"

**Comment by Keshav-NEC** [comment]
Hi, I am working on it.

**Comment by Keshav-NEC** [comment]
Hi @fgalan , can you please review the PR #2263 ? Thanks.

**Comment by fgalan** [comment]
@pooja1pathak after merging PR #2263, is this issue completed? Or is there something pending?

**Comment by pooja1pathak** [comment]
yes it is completed.
