### ISSUE TITLE
error expirating records due to cross-database references

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2265]
time=2023-06-14T11:17:29.062Z | lvl=ERROR | corr= | trans= | srv= | subsrv= | comp= | op=run | msg=com.telefonica.iot.cygnus.sinks.NGSISink$ExpirationTimeChecker[1014] : [postgis-sink] Error while expirating records. Details: CygnusExpiratingError (CygnusPersistenceError). Data expiration error (CygnusPersistenceError (SQLException). POSTGRESQL Querying error (ERROR: cross-database references are not implemented: "XXX.YYYYY"

**Comment by fgalan** [comment]
After the merge of PR https://github.com/telefonicaid/fiware-cygnus/pull/2281 can this issue be closed? Or is something else pending?
