### ISSUE TITLE
Extra underscore (`_`) in schema when use dm-by-entity-type-database-schema

### ISSUE THREAD

**Issue by danielvillalbamota** [telefonicaid/fiware-cygnus#2270]
When configure a sink with data_model `dm-by-entity-type-database-schema` it tries to persist in a database within `_schema`.

Using a subs with a custom notif like:
```
{
  "url": "http://iot-cygnus:port/notify",
  "headers": {
    "fiware-service": "myservice",
    "fiware-servicepath": "/dumps"
  }
}
```

It tries to persist in the table `_dumps.dumps_entitytype`

This extra underscore is not expected from the documentation. It is expected to persist in `dumps.dumps_entitytype`

**Comment by AlvaroVega** [comment]
Maybe the but comes from: https://github.com/telefonicaid/fiware-cygnus/pull/2210

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2271
