### ISSUE TITLE
Update link for maven in install_from_sources.md

### ISSUE THREAD

**Issue by Keshav-NEC** [telefonicaid/fiware-cygnus#2272]
Update Link for [apache-maven](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/installation_and_administration_guide/install_from_sources.md?plain=1#L30) given in [install_from_sources.md](https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-common/installation_and_administration_guide/install_from_sources.md) .

**Comment by fgalan** [comment]
After merging PR https://github.com/telefonicaid/fiware-cygnus/pull/2274, should this issue be closed?

**Comment by Keshav-NEC** [comment]
> After merging PR #2274, should this issue be closed?

Yes, it is completed
