### ISSUE TITLE
SQL persistence policy is restarting cygnus

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2273]
A configuration like:

cygnus-ngsi.sinks.postgis-type-database-sink.persistence_policy.expiration_time = 7776000
cygnus-ngsi.sinks.postgis-type-database-sink.persistence_policy.checking_time = 3600

is causing problems and restarting cygnus each 1 hour. Maybe a uge among or resources are located when checking persistence_policy thread try to work with table which a high number of records

**Comment by AlvaroVega** [comment]
Maybe related https://github.com/telefonicaid/fiware-cygnus/issues/2265

**Comment by fgalan** [comment]
After the merge of PR https://github.com/telefonicaid/fiware-cygnus/pull/2281 can this issue be closed? Or is something else pending?
