### ISSUE TITLE
notification-json-simple.sh not working with parameter myservicepath

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/fiware-cygnus#2277]
notification-json-simple.sh not working with parameter myservicepath as given at:
https://github.com/telefonicaid/fiware-cygnus/blob/9d944bfa46981ab334f24d7e5d17081684f1bc8d/cygnus-ngsi/README.md?plain=1#L142

Error message: Error 400 Bad request from client. 'fiware-servicepath' header value must start with '/'.

Solution: Command should be updated as **./notification-json-simple.sh http://localhost:5050/notify myservice /myservicepath**

**Comment by fgalan** [comment]
@pooja1pathak Having merged PR https://github.com/telefonicaid/fiware-cygnus/pull/2278, should this issue be closed, please?

**Comment by pooja1pathak** [comment]
Yes, I am closing this issue.
