### ISSUE TITLE
fiware service path should be /4wheels

### ISSUE THREAD

**Issue by pooja1pathak** [telefonicaid/fiware-cygnus#2279]
fiware service path should be /4wheels at :
https://github.com/telefonicaid/fiware-cygnus/blob/9d944bfa46981ab334f24d7e5d17081684f1bc8d/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_kafka_sink.md?plain=1#L119

**Comment by Keshav-NEC** [comment]
Hi, I’m working on it.

**Comment by Keshav-NEC** [comment]
Gentle Reminder!

**Comment by fgalan** [comment]
@pooja1pathak having merged PR https://github.com/telefonicaid/fiware-cygnus/pull/2280 should this issue be closed, please?

**Comment by pooja1pathak** [comment]
Yes, I am closing this issue.
