### ISSUE TITLE
 Cannot invoke "java.util.ArrayList.size()" because the return value of "java.util.LinkedHashMap.get(Object)" is null Sink:

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2293]
time=2023-09-13T07:33:51.233Z | lvl=ERROR | corr=39c10d78-33e5-44ec-ae13-41e417489db4; cbnotif=9 | trans=3ce0fd39-8d40-4f60-8c19-564016b82e0d | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[614] : Cannot invoke "java.util.ArrayList.size()" because the return value of "java.util.LinkedHashMap.get(Object)" is null Sink: mysql-sink Destination: cb004041_/subser404_dev1_String Stack trace: [com.telefonica.iot.cygnus.aggregation.NGSIGenericColumnAggregator.aggregate(NGSIGenericColumnAggregator.java:101), com.telefonica.iot.cygnus.sinks.NGSIMySQLSink.persistBatch(NGSIMySQLSink.java:346), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:592), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:372), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145), java.base/java.lang.Thread.run(Thread.java:833)]

Running cygnus latest with follwing mysql sink configuration

# Mysql sink
cygnus-ngsi.sinks.mysql-sink.type = com.telefonica.iot.cygnus.sinks.NGSIMySQLSink
cygnus-ngsi.sinks.mysql-sink.channel = mysql-channel
cygnus-ngsi.sinks.mysql-sink.enable_grouping = false
cygnus-ngsi.sinks.mysql-sink.enable_name_mappings = true
cygnus-ngsi.sinks.mysql-sink.data_model = dm-by-entity
cygnus-ngsi.sinks.mysql-sink.mysql_host = iot-mysql
cygnus-ngsi.sinks.mysql-sink.mysql_port = 3306
cygnus-ngsi.sinks.mysql-sink.mysql_username = XX
cygnus-ngsi.sinks.mysql-sink.mysql_password = YY
cygnus-ngsi.sinks.mysql-sink.attr_persistence = column
cygnus-ngsi.sinks.mysql-sink.attr_native_types = true
cygnus-ngsi.sinks.mysql-sink.batch_size = 1
cygnus-ngsi.sinks.mysql-sink.batch_timeout = 10
cygnus-ngsi.sinks.mysql-sink.last_data_mode = insert
cygnus-ngsi.sinks.mysql-sink.last_data_table_suffix = _lastdata
cygnus-ngsi.sinks.mysql-sink.last_data_unique_key = entityId
cygnus-ngsi.sinks.mysql-sink.last_data_timestamp_key = recvTime
cygnus-ngsi.sinks.mysql-sink.last_data_sql_timestamp_format = YYYY-MM-DD HH24:MI:SS.MS

**Comment by AlvaroVega** [comment]
Maybe related with recent java upgrade (some new checks are performed)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2294
