### ISSUE TITLE
Java 16 and 17 tests errors

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2297]
Failed tests:   testLoadNameMappingsError(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc

Tests in error: 
  testGetEventsMultiValuedServicePathNgsiv2(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest)
  testGetEventsMultiValuedServicePath(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGenerateUniqueIdSameCorrAndTransIds(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testConfigureDefaultServicePathStartsWithSlash(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testConfigureDefaultServicePathIsLegal(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGetEventsSingleEvent(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGetEventsContentTypeHeaderFormat(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testWrongServiceHeaderLength(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGetEventsNullEventsUponInvalidConfiguration(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGenerateUniqueIdTransIdGenerated(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testConfigureNotificationTargerStartsWithSlash(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testWrongServicePathHeaderLength(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testConfigureNotMandatoryParameters(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGetEventsHeadersInFlumeEvent(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testConfigureDefaultServiceIsLegal(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGenerateUniqueIdCorrIdGenerated(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testWrongServicePathHeaderInitialCharacter(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGetEventsContentTypeHeader(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testWrongContentType(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testGenerateUniqueIdCorrIdReused(com.telefonica.iot.cygnus.handlers.NGSIRestHandlerTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testNameMappingsSuccessfullyParsed(com.telefonica.iot.cygnus.containers.NameMappingsTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testNameMappingsPatternsCompiled(com.telefonica.iot.cygnus.containers.NameMappingsTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testDoMapConfig(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testDoMapConfig2(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testDoMapConfig3(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testDoMapConfig4(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testDoMapRegex(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testGetBodyInNGSIEvent(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testDoMap(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testGetContextElementsInNGSIEvent(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @774b63bc
  testPersistBatchWithOneAttributeColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithoutData[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyRow[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyColumn[0](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithoutData[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyRow[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyColumn[1](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithoutData[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyRow[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyColumn[2](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneAttributeRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithOneNullAttributeIgnoreWhiteSpacesRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithThreeAttributesWithMetadataRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithoutData[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoNullAttributesIgnoreWhiteSpacesRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesWithEmptyRow[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testPersistBatchWithTwoAttributesIgnoreEmptyColumn[3](com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$PersistBatchTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testStartAndStopInternalWithCache(com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$StartAndStopInternalTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testStartAndStopInternalWithoutCache(com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSinkTest$StartAndStopInternalTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testCreateUpdateEntityEncoding(com.telefonica.iot.cygnus.sinks.NGSIOrionBaseSinkTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  testInsertFeature(com.telefonica.iot.cygnus.sinks.NGSIArcGisSinkTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
  pointToFeatureAttr(com.telefonica.iot.cygnus.sinks.NGSIArcGisSinkTest): Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3

**Comment by AlvaroVega** [comment]
Mockito dep (1.9.5 version) should be upgraded

**Comment by AlvaroVega** [comment]
Failed tests:   testLoadNameMappingsError(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe

Tests in error: 
  testNameMappingsSuccessfullyParsed(com.telefonica.iot.cygnus.containers.NameMappingsTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testNameMappingsPatternsCompiled(com.telefonica.iot.cygnus.containers.NameMappingsTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testDoMapConfig(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testDoMapConfig2(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testDoMapConfig3(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testDoMapConfig4(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testDoMapRegex(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testGetBodyInNGSIEvent(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testDoMap(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
  testGetContextElementsInNGSIEvent(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest): Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe

Tests run: 807, Failures: 1, Errors: 10, Skipped: 0

**Comment by AlvaroVega** [comment]
Tests run: 12, Failures: 1, Errors: 8, Skipped: 0, Time elapsed: 0.044 sec <<< FAILURE!
testDoMapConfig(com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.regex.Pattern.pattern accessible: module java.base does not "opens java.util.regex" to unnamed module @7cb756fe
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:153)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:96)
	at com.google.gson.Gson.getAdapter(Gson.java:416)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:135)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:104)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:96)
	at com.google.gson.Gson.getAdapter(Gson.java:416)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:53)
	at com.google.gson.Gson.getAdapter(Gson.java:416)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:135)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:105)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:104)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:160)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:96)
	at com.google.gson.Gson.getAdapter(Gson.java:416)
	at com.google.gson.Gson.fromJson(Gson.java:878)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at com.google.gson.Gson.fromJson(Gson.java:765)
	at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor.loadNameMappings(NGSINameMappingsInterceptor.java:278)
	at com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptorTest.testDoMapConfig(NGSINameMappingsInterceptorTest.java:501)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

**Comment by AlvaroVega** [comment]
This is a JDK bug https://bugs.openjdk.org/browse/JDK-8256358

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2343
