### ISSUE TITLE
Runtime error (Failed making field 'java.util.regex.Pattern#pattern' accessible; (JDK17)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2304]
time=2023-09-18T04:32:49.247Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=loadNameMappings | msg=com.telefonica.iot.cygnus.interceptors.NGSINameMappingsInterceptor[281] : [nmi] Runtime error (Failed making field 'java.util.regex.Pattern#pattern' accessible; either change its visibility or write a custom TypeAdapter for its declaring type)

just with openjdk-17

**Comment by fgalan** [comment]
Fixed by https://github.com/telefonicaid/fiware-cygnus/pull/2343
