### ISSUE TITLE
Support for MongoDB 6.0 and 7.0

### ISSUE THREAD

**Issue by ctc-watanabe** [telefonicaid/fiware-cygnus#2309]
Hello.
Currently Cygnus supports MongoDB 3.4, 3.6 and 4.2 according to the following document, but is there any plan to support 6.0 or 7.0 or later?
https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_mongo_sink.md
https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_sth_sink.md

I didn't see it mentioned in Roadmap.md, so it would be appreciated if you could let me know.

Thank you in advance.

**Comment by AlvaroVega** [comment]
Cygnus currently uses 3.12 driver:
According with mongo driver java compatibility: https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/
Cygnus is compatible with 100% features of mongo 4.4, and is compabile with mongo 5,6,7 but not with all new features

**Comment by ctc-watanabe** [comment]
Thank you for your reply.
I have understood.
