### ISSUE TITLE
Arcgis sink. Wrong objectid in UpdateFeatures

### ISSUE THREAD

**Issue by danielvillalbamota** [telefonicaid/fiware-cygnus#2313]
## Context

When the sink check that a feature already exist by finding the `uniquefield` in the Feature Layer, it prepares the request to updateFeatures on that objectId, but instead of using the received objectId is using `-1`:

```
---BODY: features=%5B%7B%22geometry%22%3A%7B%22x%22%3A0.0%2C%22y%22%3A0.0%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D%2C%22attributes%22%3A%7B%22OBJECTID%22%3A-1%2C%22...%7D%7D%5D&f=json
```

## Problem

I guess the following code block is not finding any key as "OBJECTID_FIELDNAME" as long as the key is in fact "objectid" and "OBJECTID_FIELDNAME" is defined as `private static final String OBJECTID_FIELDNAME = "OBJECTID";`

https://github.com/telefonicaid/fiware-cygnus/blob/9d18551b4e774d587b03bef8e4a7c754cfd27a2c/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/arcgis/model/Feature.java#L227-L241

So, one possible solution is to check the key using `equalsIgnoreCase` method.

**Comment by AlvaroVega** [comment]
another similar usage of setObjectId (https://github.com/telefonicaid/fiware-cygnus/blob/9d18551b4e774d587b03bef8e4a7c754cfd27a2c/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/arcgis/model/Feature.java#L255) pero no tengo claro para qué se usa

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2315

**Comment by fgalan** [comment]
PR merged. Let's keep this issue opened, while @danielvillalbamota can confirm it is solved.

**Comment by danielvillalbamota** [comment]
It works, now is able to update features. I close the issue
