### ISSUE TITLE
Typo on image provided with README.md

### ISSUE THREAD

**Issue by Skorpinakos** [telefonicaid/fiware-cygnus#2332]
In this [file]( https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/cygnus-ngsi/README.md), in the postgres port line there is a missing quote.

**Comment by fgalan** [comment]
Maybe you could do a PR to fix it? :)

**Comment by Skorpinakos** [comment]
@fgalan 

Done [here](https://github.com/telefonicaid/fiware-cygnus/pull/2333). ✌️

**Comment by fgalan** [comment]
Fixed by PR #2333. Closing.

@Skorpinakos thanks for the contribution!
