### ISSUE TITLE
Arcgis. esriFieldTypeSingle is not included in the cases of GisAttributeType

### ISSUE THREAD

**Issue by danielvillalbamota** [telefonicaid/fiware-cygnus#2334]
[esriFieldTypeSingle](https://developers.arcgis.com/enterprise-sdk/api-reference/java/com/esri/arcgis/geodatabase/esriFieldType.html#esriFieldTypeSingle) is not included as one of the cases in:

https://github.com/telefonicaid/fiware-cygnus/blob/8ab48cbe71ca7e914480aa70f30ff020c0027f9e/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/arcgis/model/GisAttributeType.java#L56-L81

esriFieldTypeSingle could return `GisAttributeType.NUMBER`.

Moreover, `esriFieldTypeNumber` defined in: https://github.com/telefonicaid/fiware-cygnus/blob/8ab48cbe71ca7e914480aa70f30ff020c0027f9e/cygnus-common/src/main/java/com/telefonica/iot/cygnus/backends/arcgis/model/GisAttributeType.java#L64 is not a ["esriFieldType"](https://developers.arcgis.com/enterprise-sdk/api-reference/java/com/esri/arcgis/geodatabase/esriFieldType.html). So another solution would be replace `case "Number":` by `case "Single":`

**Comment by fgalan** [comment]
PR #2335

**Comment by fgalan** [comment]
PR has been merged. @danielvillalbamota please close this issue if after testing the problem has been solved.
