### ISSUE TITLE
arcgis sink: transform vales for esriFieldTypeDate field automatically to timeinstamp from DateTime

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2339]

**Comment by danielvillalbamota** [comment]
According to [Arcgis documentation](https://doc.arcgis.com/en/data-pipelines/latest/process/output-feature-layer.htm) `esriFieldTypeDate` uses miliseconds to store timestamp from epoch.

**Comment by AlvaroVega** [comment]
Maybe similar to this kind of transformations:
https://github.com/telefonicaid/fiware-cygnus/blob/54df87a6f668c9ed4bb0088182ef231b1e1adeb3/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/aggregation/NGSIGenericColumnAggregator.java#L169-L203

**Comment by AlvaroVega** [comment]
Current `datetime` for attrType transformation is done by:

https://github.com/telefonicaid/fiware-cygnus/blob/54df87a6f668c9ed4bb0088182ef231b1e1adeb3/cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIArcgisFeatureTableSink.java#L615-L619

**Comment by AlvaroVega** [comment]
From cygnus documentation about arcgis sink: https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/cygnus-ngsi/flume_extensions_catalogue/ngsi_arcgis_featuretable_sink.md#about-arcgis-data-types


    esriFieldTypeDate

From https://doc.arcgis.com/en/data-pipelines/latest/process/output-feature-layer.htm

    ... Date fields are stored in feature layers using the format milliseconds from epoch and the coordinated universal time (UTC) time zone. The values will be displayed differently depending on where you are viewing the data. For example, querying the feature service REST end point will return values in milliseconds from epoch, such as 1667411518878....

So, to persist a esriFieldTypeDate field in the Feature Layer, cygnus has to receive an attribute "Number" from the CB with the milliseconds from epoch.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/2341

@danielvillalbamota please close this issue after successfully testing (or provide extra feedback in negative case)

**Comment by danielvillalbamota** [comment]
It works.
