### ISSUE TITLE
Arcgis. Error when change the unique field value after a working persistence

### ISSUE THREAD

**Issue by danielvillalbamota** [telefonicaid/fiware-cygnus#2347]
Cygnus version: 3.5.0

Having a subscription in CB for arcgis sink which is working and getting persistence, if I change the value of `type` (unique field) the sink is not able to prepare the query properly getting the following error:

```
time=2024-02-29T12:03:26.812Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getFeatureList | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestFeatureTable[216] : Response code: 200
	{"error":{"code":400,"message":"Unable to complete operation.","details":["Unable to perform query operation.","Invalid query"]}}
time=2024-02-29T12:03:26.813Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=checkHttpResponse | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestApi[374] : Response has erros, 500 Error checking single reponse, {"error":{"code":400,"message":"Unable to complete operation.","details":["Unable to perform query operation.","Invalid query"]}} - null
time=2024-02-29T12:03:26.813Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=checkResponse | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestFeatureTable[235] : Error: 500
Error checking single reponse, {"error":{"code":400,"message":"Unable to complete operation.","details":["Unable to perform query operation.","Invalid query"]}} - null
time=2024-02-29T12:03:26.813Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=queryFeatures | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[504] : Error: 500
Error checking single reponse, {"error":{"code":400,"message":"Unable to complete operation.","details":["Unable to perform query operation.","Invalid query"]}} - null
time=2024-02-29T12:03:26.813Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=setError | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[591] : Error Message: Error: 500
Error checking single reponse, {"error":{"code":400,"message":"Unable to complete operation.","details":["Unable to perform query operation.","Invalid query"]}} - null
time=2024-02-29T12:03:26.813Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=checkTimeouts | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[346] : [arcgis-sink-no-nm] No Feature table Timeouts found. Features in batch: 0
time=2024-02-29T12:03:26.813Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[518] : Batch accumulation time reached, the batch will be processed as it is
time=2024-02-29T12:03:26.813Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=checkTimeouts | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[346] : [arcgis-sink-no-nm] No Feature table Timeouts found. Features in batch: 0
time=2024-02-29T12:03:26.813Z | lvl=ERROR | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=run | msg=org.apache.flume.SinkRunner$PollingRunner[158] : Unable to deliver event. Exception follows.
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map.get(Object)" is null
	at com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable.splitFeatureListIfExists(ArcgisFeatureTable.java:384) ~[cygnus-ngsi-3.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable.addUpdateFeatures(ArcgisFeatureTable.java:267) ~[cygnus-ngsi-3.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable.flushBatch(ArcgisFeatureTable.java:216) ~[cygnus-ngsi-3.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.telefonica.iot.cygnus.backends.arcgis.NGSIArcgisFeatureTable.flushBatch(NGSIArcgisFeatureTable.java:83) ~[cygnus-ngsi-3.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.checkTimeouts(NGSIArcgisFeatureTableSink.java:342) ~[cygnus-ngsi-3.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.process(NGSIArcgisFeatureTableSink.java:322) ~[cygnus-ngsi-3.5.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39) ~[flume-ng-core-1.11.0.jar:1.11.0]
	at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145) ~[flume-ng-core-1.11.0.jar:1.11.0]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

How to reproduce the error:

Example working httpCustom in subs:
```
{
  "url": "http://host-cygnus/notify",
  "ngsi": {
    "type": "fiwareid"
  },
  "headers": {
    "fiware-service": "base",
    "fiware-servicepath": "/path/FeatureServer/0"
  }
}
```

After some notifications, change the type`s value by `name`
```
{
  "url": "http://host-cygnus/notify",
  "ngsi": {
    "type": "name"
  },
  "headers": {
    "fiware-service": "base",
    "fiware-servicepath": "/path/FeatureServer/0"
  }
}
```

The sink performs the following query:
```
time=2024-02-29T12:03:26.167Z | lvl=DEBUG | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=requestHTTP | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestApi[179] : requesting HTTP: https://arcgis-host/server/rest/services/base/path/FeatureServer/0/query?outSR=%7B%22wkid%22%3A4326%7D&outFields=*&resultOffset=0&where=fiwareid+IN+%28%29&token=aY2...jPSn&f=json---METHOD: GET---BODY: 
```

in which `where` param is using the original type's value and is not setting the entityId inside parenthesis.

**Comment by AlvaroVega** [comment]
I'm not able or reproduce it just with a poor sink pointed to nowhere


time=2024-02-29T14:05:01.423Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=base | subsrv=/path/FeatureServer/0 | comp=cygnus-ngsi | op=tryRegister | msg=org.eclipse.jetty.io.FillInterest[79] : interested FillInterest@41ce330e{AC.ReadCB@c4280a{HttpConnection@c4280a::SocketChannelEndPoint@4f3ed5a6{l=/172.17.0.11:5059,r=/172.17.0.16:47174,OPEN,fill=FI,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}->HttpConnection@c4280a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@310e0bf7{s=START}]=>HttpChannelOverHttp@41f92231{s=HttpChannelState@45c6bed6{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}}}
time=2024-02-29T14:05:01.423Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[378] : [arcgis-sink] persisting aggregation, 1 features.
time=2024-02-29T14:05:01.423Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[384] : [arcgis-sink] persistAggregation - Feature table: localhost/base/path/FeatureServer/0 is new: true
time=2024-02-29T14:05:01.423Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=base | subsrv=/path/FeatureServer/0 | comp=cygnus-ngsi | op=changeInterests | msg=org.eclipse.jetty.io.ChannelEndPoint[422] : changeInterests p=false 0->1 for SocketChannelEndPoint@4f3ed5a6{l=/172.17.0.11:5059,r=/172.17.0.16:47174,OPEN,fill=FI,flush=-,to=0/30000}{io=0/1,kio=0,kro=1}->HttpConnection@c4280a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@310e0bf7{s=START}]=>HttpChannelOverHttp@41f92231{s=HttpChannelState@45c6bed6{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}
time=2024-02-29T14:05:01.423Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getPersistenceBackend | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[172] : Creating new persistenceBackend for Feature table: localhost/base/path/FeatureServer/0
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getPersistenceBackend | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[173] : Token url: localhost
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=base | subsrv=/path/FeatureServer/0 | comp=cygnus-ngsi | op=submit | msg=org.eclipse.jetty.io.ManagedSelector[286] : Queued change lazy=false org.eclipse.jetty.io.ChannelEndPoint$$Lambda$222/0x00007f84ec21e420@60ebd745 on ManagedSelector@6771a5f4{STARTED} id=3 keys=1 selected=0 updates=0
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[91] : Arcgis constructor.. localhost/base/path/FeatureServer/0
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=base | subsrv=/path/FeatureServer/0 | comp=cygnus-ngsi | op=submit | msg=org.eclipse.jetty.io.ManagedSelector[304] : Wakeup on submit ManagedSelector@6771a5f4{STARTED} id=3 keys=1 selected=0 updates=1
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[93] : Arcgis url.. localhost/base/path/FeatureServer/0
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[94] : Arcgis tokenGenUrl.. localhost
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[95] : Arcgis readOnly.. false
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=base | subsrv=/path/FeatureServer/0 | comp=cygnus-ngsi | op=onFillable | msg=org.eclipse.jetty.server.HttpConnection[308] : HttpConnection@c4280a::SocketChannelEndPoint@4f3ed5a6{l=/172.17.0.11:5059,r=/172.17.0.16:47174,OPEN,fill=FI,flush=-,to=0/30000}{io=0/1,kio=0,kro=1}->HttpConnection@c4280a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@310e0bf7{s=START}]=>HttpChannelOverHttp@41f92231{s=HttpChannelState@45c6bed6{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0} onFillable exit HttpChannelState@45c6bed6{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0} null
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=select | msg=org.eclipse.jetty.io.ManagedSelector[194] : Selector sun.nio.ch.EPollSelectorImpl@66770429 woken with none selected
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=base | subsrv=/path/FeatureServer/0 | comp=cygnus-ngsi | op=run | msg=org.eclipse.jetty.util.thread.QueuedThreadPool$Runner[1038] : ran CEP:SocketChannelEndPoint@4f3ed5a6{l=/172.17.0.11:5059,r=/172.17.0.16:47174,OPEN,fill=FI,flush=-,to=0/30000}{io=0/1,kio=0,kro=1}->HttpConnection@c4280a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@310e0bf7{s=START}]=>HttpChannelOverHttp@41f92231{s=HttpChannelState@45c6bed6{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}:runFillable:BLOCKING in QueuedThreadPool[qtp1348099968]@505a5f80{STARTED,8<=12<=200,i=0,r=-1,q=0}[ReservedThreadExecutor@5fed33d3{s=1/16,p=0}]
time=2024-02-29T14:05:01.424Z | lvl=ERROR | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=<init> | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[105] : Argis error while connecting to Feature Table: (Can´t parse token generation url, MalformedURLException.)
	 URL: localhost/base/path/FeatureServer/0
	 tokenGenURL: localhost
time=2024-02-29T14:05:01.424Z | lvl=ERROR | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=setError | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[591] : Error Message: Can´t parse token generation url, MalformedURLException.
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=select | msg=org.eclipse.jetty.io.ManagedSelector$SelectorProducer[612] : Selector sun.nio.ch.EPollSelectorImpl@66770429 woken up from select, 0/0/1 selected
time=2024-02-29T14:05:01.424Z | lvl=ERROR | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getPersistenceBackend | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[181] : Error creating new persistence Backend. Can´t parse token generation url, MalformedURLException.    localhost/base/path/FeatureServer/0  -  localhost
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=select | msg=org.eclipse.jetty.io.ManagedSelector$SelectorProducer[628] : Selector sun.nio.ch.EPollSelectorImpl@66770429 processing 0 keys, 1 updates
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=processUpdates | msg=org.eclipse.jetty.io.ManagedSelector$SelectorProducer[558] : updateable 1
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=processUpdates | msg=org.eclipse.jetty.io.ManagedSelector$SelectorProducer[567] : update org.eclipse.jetty.io.ChannelEndPoint$$Lambda$222/0x00007f84ec21e420@60ebd745
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=updateKey | msg=org.eclipse.jetty.io.ChannelEndPoint[383] : Key interests updated 0 -> 1 on SocketChannelEndPoint@4f3ed5a6{l=/172.17.0.11:5059,r=/172.17.0.16:47174,OPEN,fill=FI,flush=-,to=0/30000}{io=1/1,kio=1,kro=1}->HttpConnection@c4280a[p=HttpParser{s=START,0 of -1},g=HttpGenerator@310e0bf7{s=START}]=>HttpChannelOverHttp@41f92231{s=HttpChannelState@45c6bed6{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}
time=2024-02-29T14:05:01.424Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=processUpdates | msg=org.eclipse.jetty.io.ManagedSelector$SelectorProducer[587] : updates 0
time=2024-02-29T14:05:01.425Z | lvl=ERROR | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getPersistenceBackend | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[191] : Error creating new persistence Backend. CygnusRuntimeError
time=2024-02-29T14:05:01.425Z | lvl=DEBUG | corr= | trans= | srv= | subsrv= | comp= | op=select | msg=org.eclipse.jetty.io.ManagedSelector$SelectorProducer[605] : Selector sun.nio.ch.EPollSelectorImpl@66770429 waiting with 1 keys
time=2024-02-29T14:05:01.425Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getPersistenceBackend | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[192] : com.telefonica.iot.cygnus.errors.CygnusRuntimeError: CygnusRuntimeError. [arcgis-sinkError creating Persistence backend: -1 - Can´t parse token generation url, MalformedURLException.    localhost/base/path/FeatureServer/0  -  localhost. 
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.getPersistenceBackend(NGSIArcgisFeatureTableSink.java:183)
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistAggregation(NGSIArcgisFeatureTableSink.java:386)
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistBatch(NGSIArcgisFeatureTableSink.java:305)
	at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:597)
	at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:372)
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.process(NGSIArcgisFeatureTableSink.java:325)
	at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39)
	at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145)
	at java.base/java.lang.Thread.run(Thread.java:840)

time=2024-02-29T14:05:01.425Z | lvl=DEBUG | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[402] :  PersistAggregation Error: com.telefonica.iot.cygnus.errors.CygnusRuntimeError: CygnusRuntimeError (com.telefonica.iot.cygnus.errors.CygnusRuntimeError). Error creating new persistence Backend.  (CygnusRuntimeError. [arcgis-sinkError creating Persistence backend: -1 - Can´t parse token generation url, MalformedURLException.    localhost/base/path/FeatureServer/0  -  localhost. ). 
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.getPersistenceBackend(NGSIArcgisFeatureTableSink.java:195)
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistAggregation(NGSIArcgisFeatureTableSink.java:386)
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistBatch(NGSIArcgisFeatureTableSink.java:305)
	at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:597)
	at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:372)
	at com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.process(NGSIArcgisFeatureTableSink.java:325)
	at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39)
	at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145)
	at java.base/java.lang.Thread.run(Thread.java:840)

time=2024-02-29T14:05:01.425Z | lvl=ERROR | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistBatch | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[310] : [arcgis-sink] Error persisting batch, CygnusRuntimeError.CygnusRuntimeError (com.telefonica.iot.cygnus.errors.CygnusRuntimeError). Error creating new persistence Backend.  (CygnusRuntimeError. [arcgis-sinkError creating Persistence backend: -1 - Can´t parse token generation url, MalformedURLException.    localhost/base/path/FeatureServer/0  -  localhost. ). 
time=2024-02-29T14:05:01.425Z | lvl=ERROR | corr=a44e5a54-da33-42a9-b957-f936fcd30331; cbnotif=1 | trans=f69ea31f-e027-4efa-a01d-af64bb98c3a3 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[610] : CygnusRuntimeError. CygnusRuntimeError (com.telefonica.iot.cygnus.errors.CygnusRuntimeError). Error creating new persistence Backend.  (CygnusRuntimeError. [arcgis-sinkError creating Persistence backend: -1 - Can´t parse token generation url, MalformedURLException.    localhost/base/path/FeatureServer/0  -  localhost. ). .  Sink: arcgis-sink Destination: base_/path/FeatureServer/0_Otracosa2_name Stack trace: [com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistBatch(NGSIArcgisFeatureTableSink.java:311), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:597), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:372), com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.process(NGSIArcgisFeatureTableSink.java:325), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145), java.base/java.lang.Thread.run(Thread.java:840)]

**Comment by AlvaroVega** [comment]
fixed by https://github.com/telefonicaid/fiware-cygnus/pull/2348
