### ISSUE TITLE
Arcgis Sink: Wrong Warning Level

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/fiware-cygnus#2407]
Cuestión de David Hervás

"Tras actualizar la versión del Cygnus, ya podemos enviar nulos a la API del GIS a través de suscripciones. Cada vez que se envía un valor nulo, el null llega al GIS sin problema, pero por el camino aparece una traza de WARN en Splunk como la siguiente:

time=2024-07-04T09:40:07.168Z | lvl=WARN | corr=62f5dffe-39e9-11ef-9af8-0a580a81031d; cbnotif=7 | trans=4ee0d729-b5df-48ed-8e5d-a1dedbfddbec | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=jsonElementToFeatureAttr | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[624] : [NGSIArcgisAggregator] Unquoted String attribute: presion_bar:null

¿Deberían de generarse este tipo de trazas a pesar de que un valor nulo también es correcto?"

Comentó Dani Villalba que "Es cierto que Arcgis acepta campos null y esa traza no debería ser un Warning y podría ser capturada como una traza de INFO."

A partir de aquí, ver como abordar esto

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2408
