### ISSUE TITLE
improve logs about NGSIRestHandler[231] : print full fiware service / service path

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2410]
time=2024-09-19T04:31:45.812Z | lvl=WARN | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=doPost | msg=org.apache.flume.source.http.HTTPSource$FlumeHTTPServlet[235] : Received bad request from client.
time=2024-09-19T04:31:45.811Z | lvl=WARN | corr=N/A | trans=N/A | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[231] : [NGSIRestHandler] Bad HTTP notification ('fiware-servicepath' header value length greater than 50)

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2411
