### ISSUE TITLE
arcgis errors:  "serverFeatures" is null

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2413]
time=2024-09-24T09:53:27.462Z | lvl=ERROR | corr=902fb74b-423a-4bf2-9eed-716f89134dc1; cbnotif=1 | trans=d7a203bb-4754-401c-a9ae-389a46d29b3f | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[610] : CygnusRuntimeError. CygnusRuntimeError. Cannot invoke "java.util.List.size()" because "serverFeatures" is null. . Sink: sink-arcgis_XXXX Destination: AAA/BBB//FeatureServer/CCC Stack trace: [com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistBatch(NGSIArcgisFeatureTableSink.java:311), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:597), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:372), com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.process(NGSIArcgisFeatureTableSink.java:325), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145), java.base/java.lang.Thread.run(Thread.java:840)]

time=2024-09-24T09:53:27.462Z | lvl=ERROR | corr=902fb74b-423a-4bf2-9eed-716f89134dc1; cbnotif=1 | trans=d7a203bb-4754-401c-a9ae-389a46d29b3f | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistBatch | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[310] : [sink-arcgis_XXXXXX] Error persisting batch, CygnusRuntimeError.CygnusRuntimeError. Cannot invoke "java.util.List.size()" because "serverFeatures" is null.

time=2024-09-24T09:53:27.462Z | lvl=ERROR | corr=902fb74b-423a-4bf2-9eed-716f89134dc1; cbnotif=1 | trans=d7a203bb-4754-401c-a9ae-389a46d29b3f | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[403] : [sink-arcgis_XXXXXXX] Error persisting batch, NullPointerException - Cannot invoke "java.util.List.size()" because "serverFeatures" is null

**Comment by AlvaroVega** [comment]
estaria bien tener el ejemplo en json del  PolyLine que se esta usando.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/2414
