### ISSUE TITLE
toString of complex geometries are not returning equivalent input (arcgis)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2418]
Running test from: https://github.com/telefonicaid/fiware-cygnus/tree/master/cygnus-common/src/test/java/com/telefonica/iot/cygnus/backends/arcgis

[INFO] Running com.telefonica.iot.cygnus.backends.arcgis.FeatureTest
----------------  getNewPolygonFeature
POLYGON: { "rings": [ [[ -97.06138, 32.837, 35.1, 4.8, ], [[ -97.06133, 32.836, 35.2, 4.1, ], [[ -97.06124, 32.834, 35.3, 4.2, ], [[ -97.06138, 32.837, 35.1, 4.8, ], [[ -97.06326, 32.759, 35.4, ], [[ -97.06298, 32.755, 35.5, ], [[ -97.06153, 32.749, 35.6, ], [[ -97.06326, 32.759, 35.4,  ]}
feature with polygon -  {"geometry":{"rings":"{ \"rings\": [ [[ -97.06138, 32.837, 35.1, 4.8, ], [[ -97.06133, 32.836, 35.2, 4.1, ], [[ -97.06124, 32.834, 35.3, 4.2, ], [[ -97.06138, 32.837, 35.1, 4.8, ], [[ -97.06326, 32.759, 35.4, ], [[ -97.06298, 32.755, 35.5, ], [[ -97.06153, 32.749, 35.6, ], [[ -97.06326, 32.759, 35.4,  ]}","spatialReference":{"wkid":4326}},"attributes":{"IDEXTERNO":33,"DESCRIPCION":"Mi Polygon","RAZONSOCIAL":"Razon social","NUMEROPOSTAL":null,"TIPOOCUPACION":0,"FINI":1727260534714,"UNIDADMEDIDA":null,"EXCSABDOM":0,"EXCFESTIVOS":0,"PRESENCIAPOLICIAL":0,"REVISADO":0,"IDACTIVIDAD":0,"ACTIVIDAD":"actividad","IDCLASE":0,"CLASE":"clase","IDESTADO":0,"ESTADO":"estado","CALLE":"calle","FFIN":"09/25/2024 12:35:34","CANTIDADOCUPADA":null}}
----------------  getNewPolyLineFeature
POLYLINE: { "paths": [ [[ -97.06138, 32.837, ], [[ -97.06133, 33.836, ], [[ -98.2, 34.834, ], [[ -97.0, 40.0,  ]}
Feature createPolyLineFeature: { "paths": [ [ [-97.06138, 32.837], [-97.06133, 33.836], [-98.2, 34.834], [-97, 40] ] ] }
feature with polyline -  {"geometry":{"paths":"{ \"paths\": [ [[ -97.06138, 32.837, ], [[ -97.06133, 33.836, ], [[ -98.2, 34.834, ], [[ -97.0, 40.0,  ]}","spatialReference":{"wkid":4326}},"attributes":{"IDEXTERNO":33,"DESCRIPCION":"Mi PolyLine","RAZONSOCIAL":"Razon social","NUMEROPOSTAL":null,"TIPOOCUPACION":0,"FINI":1727260534717,"UNIDADMEDIDA":null,"EXCSABDOM":0,"EXCFESTIVOS":0,"PRESENCIAPOLICIAL":0,"REVISADO":0,"IDACTIVIDAD":0,"ACTIVIDAD":"actividad","IDCLASE":0,"CLASE":"clase","IDESTADO":0,"ESTADO":"estado","CALLE":"calle","FFIN":"09/25/2024 12:35:34","CANTIDADOCUPADA":null}}
----------------  createInstanceFromJson2
----------------  getNewMultiPointFeature
MULTIPOINT: { "points": [[ -97.06138, 32.83 ],[ -97.06133, 33.83 ],[ -98.2, 34.83 ],[ -97.0, 40.  ]}
feature with multipoint -  {"geometry":{"points":"{ \"points\": [[ -97.06138, 32.83 ],[ -97.06133, 33.83 ],[ -98.2, 34.83 ],[ -97.0, 40.  ]}","spatialReference":{"wkid":4326}},"attributes":{"IDEXTERNO":33,"DESCRIPCION":"Mi MultiPoint","RAZONSOCIAL":"Razon social","NUMEROPOSTAL":null,"TIPOOCUPACION":0,"FINI":1727260534724,"UNIDADMEDIDA":null,"EXCSABDOM":0,"EXCFESTIVOS":0,"PRESENCIAPOLICIAL":0,"REVISADO":0,"IDACTIVIDAD":0,"ACTIVIDAD":"actividad","IDCLASE":0,"CLASE":"clase","IDESTADO":0,"ESTADO":"estado","CALLE":"calle","FFIN":"09/25/2024 12:35:34","CANTIDADOCUPADA":null}}
----------------  createInstanceFromJson
createInstanceFromJson jsonGeometryElement: {"x":-3.0,"y":43.0,"spatialReference":{"wkid":4326}}
Success -  {"geometry":{"x":-3.0,"y":43.0,"spatialReference":{"wkid":4326}},"attributes":{"OBJECTID":2,"IDEXTERNO":null,"RAZONSOCIAL":"Razon social updated","NUMEROPOSTAL":null,"TIPOOCUPACION":1,"FINI":-2209161600000,"UNIDADMEDIDA":null,"EXCSABDOM":1,"EXCFESTIVOS":1,"PRESENCIAPOLICIAL":1,"REVISADO":0,"IDACTIVIDAD":0,"ACTIVIDAD":"actividad updated","IDCLASE":0,"CLASE":"clase","IDESTADO":0,"ESTADO":"updated","CALLE":"calle","FFIN":-2209161600000,"CANTIDADOCUPADA":null,"DESCRIPCION":"Pruebadescripcion"}}

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/fiware-cygnus/pull/2417
