### ISSUE TITLE
Arcgis: Response has erros, 400 Response Error 400  Unable to complete operation.

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2424]
time=2024-10-03T11:46:51.839Z | lvl=DEBUG | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=requestHTTP | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestApi[179] : requesting HTTP: https://URL/server/rest/services/OCI/OCI_BBBBBBFeatureServer/NNN/updateFeatures?outSR=%7B%22wkid%22%3A4326%7D&token=TTTTTTTTTTTT&rollbackOnFailure=true---METHOD: POST---BODY: features=%5B%7B%22attributes%22%3A%7B%22OBJECTID%22%3A-1%2C%22estado%22%3A4%2C%22denominacion%22%3A%22AV.+CATALU%C3%91A+DE+EEEEE+2%22%2C%22fiwareid%22%3A%22EstadoRRRRRR_1%22%7D%7D%5D&f=json
time=2024-10-03T11:46:51.987Z | lvl=DEBUG | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=requestHTTP | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestApi[263] : Disposing connection objects

time=2024-10-03T11:46:51.988Z | lvl=DEBUG | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=sendFeatureList | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestFeatureTable[269] : Response code: 200
time=2024-10-03T11:46:51.988Z | lvl=DEBUG | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=checkHttpResponse | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestApi[374] : Response has erros, 400 Response Error 400  Unable to complete operation.
time=2024-10-03T11:46:51.988Z | lvl=ERROR | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=checkResponse | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.RestFeatureTable[235] : Error: 400
time=2024-10-03T11:46:51.988Z | lvl=ERROR | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=commitFeatures | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[552] : Error: 400
time=2024-10-03T11:46:51.988Z | lvl=ERROR | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=setError | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[602] : Error Message: Error: 400
time=2024-10-03T11:46:51.988Z | lvl=DEBUG | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=commitFeatures | msg=com.telefonica.iot.cygnus.backends.arcgis.restutils.ArcgisFeatureTable[556] : pendingFeatures.commitFeatures adding listener to commitFeatureFuture: 1
time=2024-10-03T11:46:51.988Z | lvl=ERROR | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistAggregation | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[405] : [arcgis-sink-no-nm] Error persisting batch, ArcgisException - Error: 400
time=2024-10-03T11:46:51.989Z | lvl=ERROR | corr=9556ca96-2e00-41c1-967d-8453225b97b9; cbnotif=1 | trans=78fd3936-b26a-42e3-8aa6-ccdaa88bb073 | srv=N/A | subsrv=N/A | comp=cygnus-ngsi | op=persistBatch | msg=com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink[312] : [arcgis-sink-no-nm] Error persisting batch, CygnusRuntimeError.CygnusRuntimeError. Error: 400
FIDs must not be negative. .  Sink: arcgis-sink-no-nm Destination: OCI_/OCI_Plataforma_vlci/FeatureServer/162_EstadoTrafico_1_fiwareid Stack trace: [com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.persistBatch(NGSIArcgisFeatureTableSink.java:313), com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:597), com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:372), com.telefonica.iot.cygnus.sinks.NGSIArcgisFeatureTableSink.process(NGSIArcgisFeatureTableSink.java:327), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:39), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145), java.base/java.lang.Thread.run(Thread.java:840)]

**Comment by AlvaroVega** [comment]
This body: 

features=%5B%7B%22attributes%22%3A%7B%22OBJECTID%22%3A-1%2C%22estado%22%3A4%2C%22denominacion%22%3A%22AV.+CATALU%C3%91A+DE+EEEEE+2%22%2C%22fiwareid%22%3A%22EstadoRRRRRR_1%22%7D%7D%5D&f=json


is decoded as: 

features=[{"attributes":{"OBJECTID":-1,"estado":4,"denominacion":"AV.+CATALUÑA+DE+EEEEE+2","fiwareid":"EstadoRRRRRR_1"}}]&f=json

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-cygnus/pull/2425

**Comment by fgalan** [comment]
Pending to test if it works before closing the isssue.

**Comment by AlvaroVega** [comment]
Tested and works
