### ISSUE TITLE
custom config for arcgis connection timeout (default are infinite) 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-cygnus#2440]
default values for java.net.HttpURLConnection timeout are infinite.
It would be great to be configurable by sink

connection.setConnectTimeout(X);
connection.setReadTimeout(Y); 

https://docs.oracle.com/javase/8/docs/api/index.html?java/net/URLConnection.html

**Comment by fgalan** [comment]
PR #2441

Should this issue be closed now that PR is merged?
