### ISSUE TITLE
Hive queries to Cosmos from WireCloud

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#25]
Raised in Seville workshop in March 2014:

It would be great to been able to perform the Hive query from a WirecCloud widget. Need to be explored.

**Comment by frbattid** [comment]
This has been added to [fiware-cosmos](https://github.com/telefonicaid/fiware-cosmos)'s backlog: https://github.com/telefonicaid/fiware-cosmos/issues/116
