### ISSUE TITLE
Rename Java packages to com.telefonica.iot....

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#294]
Instead of current est.tid.fiware....

Do not change until release/iot-platform-v1.1 is closed.

<b>Effort: 1 man day</b>

**Comment by fgalan** [comment]
Small comment: release/iot-platform-v1.1 actually is release/0.6.0 ;)

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/358
