### ISSUE TITLE
Use library-based APIs instead of RESTful APIs

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#301]
Instead of using RESTful APIs, library-based APIs could be used to increase the performance. At least, that could be the case of HDFS, i.e. use the [Hadoop API](http://hadoop.apache.org/docs/r2.6.0/api/index.html) instead of [WebHDFS](http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html).

In the case of MySQL, the mysqlconnector seems to be the only option... at least, calls will be made localy instead of remotely. The question is... is there a CKAN API? 

The idea behind this proposal is to move Cygnus deployment from Orion side to the storage side, avoiding HTTP-based communications.

**Comment by fgalan** [comment]
There is document named "The CKAN API" (note the "The" :) at http://docs.ckan.org/en/ckan-2.2/api.html, but it seems that is REST API, so it is not the API kind you are looking for.

CKAN relies in Postgres storate. If the way in which CKAN stores information in that DB is documented, maybe a JDBC-like interface may be use (thus avoiding HTTP-based comunication and using a wiring protocol suposed to be efficient).

**Comment by frbattid** [comment]
Good point.

Anyway, this is only a proposal that would restrict the deployment of Cygnus, in the sense that would only work if, for instance, the MySQL database and the Namenode run in the same machine (asuming you want both types of persistence).

There are other ideas on the table, like moving from text protocols (HTTP) to a binary ones.

**Comment by frbattid** [comment]
Issue created regarding HDFS: https://github.com/telefonicaid/fiware-cygnus/issues/537

**Comment by frbattid** [comment]
Once this has been created for HDFS, it seems the issue can be close since:

* `OrionHDFSSink` has available both binary and REST backends.
* `OrionMySQLSink` is already based on JDBC driver, a binary approach.
* `OrionMongoSink` and `OrionSTHSink` are already based on Mongo driver, a binary approach.
* `OrionKafkaSink` is already based on a Java-based client, a binary approach.
* It seems there is no binary approach for `OrionCKANSink`.
* Future sinks such as `OrionPostgreSQLSink` and `OrionDynamoSink` will be based on binary approaches.
