### ISSUE TITLE
Cygnus must die if the configured HttpSource port is already in use

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#340]
Current behaviour is to continue starting Flume components such as the channels and the sinks, despite of without a source they don't make sense.

<b>Effort: 1 man day</b>

**Comment by fgalan** [comment]
Taking into account this is in "PR phase", I guess that this belongs to milestone 0.8.0

**Comment by frbattid** [comment]
I agree, thanks! :)

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/356

**Comment by gtorodelvalle** [comment]
Hey @frbattid , just to adhere to the correct workflow :) Is the person merging and deleting the branch the one who should also include the "Implemented in PR #XXX" comment in the issue and close it? Just to do it if I should :)

**Comment by frbattid** [comment]
Hi @gtorodelvalle , it is not necessary, as the PR creator I usually do that ;)
