### ISSUE TITLE
[configuration] Hide as many configuration parameters as possible, enforcing the usage of default values

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#365]
Currently, default values are defined for all the configuration parameters. Nevertheless, they are not used since the documentation encourages the user to give custom values to all of them.

Instead of that, explain the minimal set of parameters that are mandatory to be defined (in other case, the software will not work), and then explain the optional parameters.

**Comment by frbattid** [comment]
A very simple but effective way of implementing this is by commenting (both in the README and the configuration template) those lines having a default value.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/822

**Comment by frbattid** [comment]
Reopening since `attr_persistence` and `should_hash` parameters are not working with the default value (i.e. having these parameters commented in the agent configuration).

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/831
