### ISSUE TITLE
[grouping rules] Add a "null" or "empty" keyword to be used in pattern-based grouping rules

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#369]
Currently, there is no possibility of specifying an empry/null field in rules of the pattern-based grouping features.

<b>Effort: 1 man day</b>

**Comment by fgalan** [comment]
Tech debt issues should have an effort measurement ("Effort: X man day").

**Comment by frbattid** [comment]
After some tests, this could not be a good idea... A null/empty matching-rule-destination must be always avoided. A null/empty matching-rule-dataset (or new fiware-sericePath) may be only useful for MySQL (in the future Mongo and STH) because the fiware-servicePath is prefixed to the table name (collection name if using Mongo/STH); HDFS is unaffected, there is simply a subfolder less; nevertheless, CKAN cannot support null packages/datasets, whose name is build based on the fiware-servicePath or matching-rule-dataset.

**Comment by frbattid** [comment]
Closing since there is no special requirement form Product and it is not clear it is a good idea...
