### ISSUE TITLE
fiware-servicePath header within Flume events is not splited in the sinks

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#384]
The same than the `destination` header, which can be multi-valued if more than one context response is notified, the `fiware-servicePath` header may be multi-valued as well when the `DestinationExtractorInterceptor` is used (this feature can assign a different service path to all the context responses within a notification, different than the common notified service path).

**Comment by fgalan** [comment]
Do you mean that the HTTP header Fiware-ServicePath could be multivalued? This way:

```
Fiware-ServicePath: /Basuras/LasTablas, /Urbanismo
```

**Comment by frbattid** [comment]
Not the notified HTTP header, but the header within Flume events. Remember: a notified NGSI event is transformed into an internal Flume event that is composed of a body and a set of headers; most of the headers are copied from the HTTP notification, but many others are proprietary by Cygnus, and, even, others are altered from the origianl one (as is the case of fiware-servicePath).

**Comment by fgalan** [comment]
Ok, next question... :) In which scenario the flume-level fiware-servicePath header could end in a multivalued case?

**Comment by frbattid** [comment]
If you use the pattern-based grouping feature. Currently, you can define in the matching rules an alternative "destination" to the default `entityId_entityType` and an alternative "dataset" different than the notified fiware-servicePath.

For instance, a notification may contain two context responses; one of them is about a 'room.1' entity of type 'room', and the second one is about a 'room.special' room of type 'room' as well. Then, you can define a rule saying "all the numerical rooms will go to a destination/fiwareSerivicePath called 'dest1' under a dataset called 'numerical_rooms'", and another rule saying "all the special rooms will go to a destination called 'dest2' nder a dataset/fiwareServicePath called 'special_rooms'".

Anyway, this kind of extrange behaviour is dued to the notified events are not parsed at the begining of the data flow, i.e. at the sources, but at the sinks. In more details:

* The source receives a notification contaning multiple context responses. The XML/Json data is not parsed at this stage, but added to a Flume event body. Some headers are created for the Flume event.
* When the source tries to put the event into the channel, the interceptors run. This components add more headers (or totally discard the event) by analyzing the body. In this case, the multi-valued "destination" is added, one value per each context response, depending on the configured rules, and the multi-valued "fiware-servicePath" is modified, adding a specific dataset/servicePath for each context response, depending on the configured files.
* Then the event is put in the channel.
* And the sinks take them, by parsing the XML/Json data and persisting it.

I have an opened issue about changing this behaviour: https://github.com/telefonicaid/fiware-cygnus/issues/359. The idea is to move the parsing step from the sinks to the sources, creating multiple events for each notified context response and forgetting about multi-valued headers. In the meantime, we have to deal with this ugly thing :)

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/418
