### ISSUE TITLE
Use Json-like rules definition for pattern-based grouping

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#387]
Current rules are based on CSV-like strings, something ugly to see and use. This proposal is about moving to a Json representation.

In addition to the change of format, the Json rules could be stored in some lightweight NoSQL database (if such a thing exists) instead of a file (which is never properly configured by the users :)).

**Comment by fgalan** [comment]
A file is a kind of NoSQL database for JSON information ;)

**Comment by frbattid** [comment]
Right xD

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/409
