### ISSUE TITLE
[CYGNUS] Append in agent.conf.template the new sink names and channel names. 

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-cygnus#392]
Append in agent.conf.template the new sink names and channel names.
```
cygnusagent.sinks = hdfs-sink mysql-sink ckan-sink
cygnusagent.channels = hdfs-channel mysql-channel ckan-channel
....
cygnusagent.sources.http-source.channels = hdfs-channel mysql-channel ckan-channel
```
new sinks: mongo-sink  sth-sink 
new channels: mongo-channel sth-channel

**Comment by frbattid** [comment]
This is already done in develop (and thus, it will be present in 0.8.1 an so on), but 0.8.0 wont release anything related to `OrionMongoSink` nor `OrionSTHSink`.

**Comment by iariasleon** [comment]
It will be tested in 0.8.1
