### ISSUE TITLE
include polling-interval parameter in config files (instance.conf or agent.conf)

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-cygnus#438]
It is useful this parameter in config files.
https://github.com/telefonicaid/fiware-cygnus#section6.2 (-t parameter)

**Comment by frbattid** [comment]
This paramter is already incuded! Please, have a look on:

https://github.com/telefonicaid/fiware-cygnus/blob/master/conf/cygnus_instance.conf.template#L43

**Comment by iariasleon** [comment]
LGTM
