### ISSUE TITLE
error in rpm creation when using "-" char in the version

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-cygnus#439]
ex:
         error: line 19: Illegal char '-' in: Version:          0.8.1-SNAPSHOT

**Comment by frbattid** [comment]
As discussed offline, this is going to fixed by rolling back to '_' character.

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/477
