### ISSUE TITLE
MySQL timestamps cannot contain time zone information

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-cygnus#441]
WARN in case of recvTime will be timestamp:
```
time=2015-05-26T08:33:38.994CEST | lvl=WARN | trans=1432622013-408-0000000000 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[179] : Bad context data (Data truncation: Incorrect datetime value: '2015-05-26T06:33:38.753Z' for column 'recvTime' at row 1)
```

**Comment by frbattid** [comment]
I think this is more likely a bug. I mean, MySQL interprets all the Timestamp data as being in UTC. The time zone is an environment variable that can be changed. See: http://dev.mysql.com/doc/refman/5.6/en/time-zone-support.html

Thus, any Timestamp involved in OrionMySQLSink should avoid the time zone information; specifically, we must remove the 'Z' sufix recently added.

**Comment by iariasleon** [comment]
I agree

**Comment by gtorodelvalle** [comment]
Huh! Kind of weird... I mean, if the time zone is set to some value and changed afterwards, is MySQL so smart to make the conversion? :)

On the other hand, which is your approach, @frbattid ? Do you plan to get the timezone concrete value being used by MySQL (see http://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_time_zone) and convert the dates to it so it is stored accordingly? In fact, I just read this:
```
The current session time zone setting affects display and storage of time values that are zone-sensitive. This includes the values displayed by functions such as NOW() or CURTIME(), and values stored in and retrieved from TIMESTAMP columns. Values for TIMESTAMP columns are converted from the current time zone to UTC for storage, and from UTC to the current time zone for retrieval.
```
So I guess you have to do nothing, just instantiating Dates and pass them over to MySQL (with no time zone conversion), right? :)

**Comment by frbattid** [comment]
Yes, I should not do nothing with the date (if it is not in UTC format, it is automatically transformed), except to insert it into MySQL without the time zone character (typically 'Z').

**Comment by gtorodelvalle** [comment]
\o/

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/450

Waiting for @iariasleon LGTM allowing closing the issue.

**Comment by iariasleon** [comment]
LGTM
