### ISSUE TITLE
Wrong mysql connection from cygnus when service changes

### ISSUE THREAD

**Issue by mcarracedo** [telefonicaid/fiware-cygnus#445]
After persisting data into mysql for the first time after start-up, cygnus keep on using the same mysql connection, so that, if next request is from different service, there will be an error.

The following log have beenn extracted:

....
time=2015-05-28T19:12:27.639CEST | lvl=INFO | trans= | function=startAllComponents | comp=Cygnus | msg=org.apache.flume.node.Application[145] : Starting Channel mysql-channel
time=2015-05-28T19:12:27.639CEST | lvl=INFO | trans= | function=start | comp=Cygnus | msg=org.apache.flume.instrumentation.MonitoredCounterGroup[94] : Component type: CHANNEL, name: mysql-channel started
time=2015-05-28T19:12:27.639CEST | lvl=INFO | trans= | function=startAllComponents | comp=Cygnus | msg=org.apache.flume.node.Application[173] : Starting Sink mysql-sink
time=2015-05-28T19:12:27.639CEST | lvl=INFO | trans= | function=startAllComponents | comp=Cygnus | msg=org.apache.flume.node.Application[184] : Starting Source http-source
time=2015-05-28T19:12:27.639CEST | lvl=DEBUG | trans= | function=start | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[146] : [mysql-sink] MySQL persistence backend created
time=2015-05-28T19:12:27.640CEST | lvl=INFO | trans= | function=start | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[149] : [mysql-sink] Startup completed
time=2015-05-28T19:12:27.640CEST | lvl=DEBUG | trans= | function=initialize | comp=Cygnus | msg=com.telefonica.iot.cygnus.interceptors.GroupingInterceptor[92] : Grouping rules read:
time=2015-05-28T19:12:27.640CEST | lvl=DEBUG | trans= | function=run | comp=Cygnus | msg=org.apache.flume.SinkRunner$PollingRunner[143] : Polling sink runner starting
time=2015-05-28T19:12:27.640CEST | lvl=ERROR | trans= | function=parseGroupingRules | comp=Cygnus | msg=com.telefonica.iot.cygnus.interceptors.GroupingInterceptor[165] : Error while parsing the Json-based grouping rules file. Details=null
time=2015-05-28T19:12:27.640CEST | lvl=DEBUG | trans= | function=initialize | comp=Cygnus | msg=com.telefonica.iot.cygnus.interceptors.GroupingInterceptor[98] : Grouping rules syntax has errors
time=2015-05-28T19:12:27.641CEST | lvl=INFO | trans= | function=info | comp=Cygnus | msg=org.mortbay.log.Slf4jLog[67] : jetty-6.1.26
time=2015-05-28T19:12:27.642CEST | lvl=INFO | trans= | function=info | comp=Cygnus | msg=org.mortbay.log.Slf4jLog[67] : Started SocketConnector@0.0.0.0:5050
time=2015-05-28T19:12:27.642CEST | lvl=INFO | trans= | function=start | comp=Cygnus | msg=org.apache.flume.instrumentation.MonitoredCounterGroup[94] : Component type: SOURCE, name: http-source started
time=2015-05-28T19:12:57.640CEST | lvl=DEBUG | trans= | function=run | comp=Cygnus | msg=org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable[126] : Checking file:/usr/cygnus/conf/agent_mysql.conf for changes
time=2015-05-28T19:13:11.705CEST | lvl=INFO | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[150] : Starting transaction (1432833146-948-0000000000)
time=2015-05-28T19:13:11.707CEST | lvl=INFO | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[236] : Received data ({  "subscriptionId" : "55674ca7bb31a81984d9e8cd",  "originator" : "localhost",  "contextResponses" : [    {      "contextElement" : {        "type" : "AZUL",        "isPattern" : "false",        "id" : "FLOW0",        "attributes" : [          {            "name" : "temperature",            "type" : "centigrade",            "value" : "867",            "metadatas" : [              {                "name" : "MetaTest",                "type" : "TestType1",                "value" : "UPDATED"              }            ]          }        ]      },      "statusCode" : {        "code" : "200",        "reasonPhrase" : "OK"      }    }  ]})
time=2015-05-28T19:13:11.707CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[241] : Adding flume event header (name=content-type, value=application/json)
time=2015-05-28T19:13:11.707CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[244] : Adding flume event header (name=fiware-service, value=smartvalencia)
time=2015-05-28T19:13:11.708CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[247] : Adding flume event header (name=fiware-servicepath, value=electricidad)
time=2015-05-28T19:13:11.708CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[250] : Adding flume event header (name=transactionId, value=1432833146-948-0000000000)
time=2015-05-28T19:13:11.708CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[252] : Adding flume event header (name=ttl, value=10)
time=2015-05-28T19:13:11.709CEST | lvl=INFO | trans=1432833146-948-0000000000 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[258] : Event put in the channel (id=891984761, ttl=10)
time=2015-05-28T19:13:11.774CEST | lvl=INFO | trans=1432833146-948-0000000000 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[128] : Event got from the channel (id=891984761, headers={timestamp=1432833191709, content-type=application/json, transactionId=1432833146-948-0000000000, fiware-service=smartvalencia, fiware-servicepath=electricidad, ttl=10, destination=flow0_azul}, bodyLength=638)
time=2015-05-28T19:13:11.779CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=persist | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[182] : [mysql-sink] Processing context element (id=FLOW0, type= AZUL)
time=2015-05-28T19:13:11.779CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=persist | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[221] : [mysql-sink] Processing context attribute (name=temperature, type=centigrade)
time=2015-05-28T19:13:11.779CEST | lvl=INFO | trans=1432833146-948-0000000000 | function=persist | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[240] : [mysql-sink] Persisting data at OrionMySQLSink. Database: smartvalencia, Table: electricidad_flow0_azul, Timestamp: 2015-05-28T17:13:11.709Z, Data (attrs): {temperature=867}, (metadata): {temperature_md=[{"name":"MetaTest","type":"TestType1","value":"UPDATED"}]}
time=2015-05-28T19:13:11.811CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=getConnection | comp=Cygnus | msg=com.telefonica.iot.cygnus.backends.mysql.MySQLBackend[243] : Connecting to jdbc:mysql://10.0.0.30:3306/smartvalencia?user=cb&password=XXXXXXXXXX
time=2015-05-28T19:13:12.063CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=insertContextData | comp=Cygnus | msg=com.telefonica.iot.cygnus.backends.mysql.MySQLBackend[216] : Executing MySQL query 'insert into `electricidad_flow0_azul` (recvTime,temperature,temperature_md) values ('2015-05-28T17:13:11.709Z','867','[{"name":"MetaTest","type":"TestType1","value":"UPDATED"}]')'
time=2015-05-28T19:13:12.078CEST | lvl=DEBUG | trans=1432833146-948-0000000000 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[139] : [com.telefonica.iot.cygnus.backends.mysql.MySQLBackend.insertContextData(MySQLBackend.java:221), com.telefonica.iot.cygnus.sinks.OrionMySQLSink.persist(OrionMySQLSink.java:243), com.telefonica.iot.cygnus.sinks.OrionSink.persist(OrionSink.java:242), com.telefonica.iot.cygnus.sinks.OrionSink.process(OrionSink.java:133), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147), java.lang.Thread.run(Thread.java:745)]
time=2015-05-28T19:13:12.078CEST | lvl=WARN | trans=1432833146-948-0000000000 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[182] : Bad context data (Data truncation: Incorrect datetime value: '2015-05-28T17:13:11.709Z' for column 'recvTime' at row 1)
time=2015-05-28T19:13:12.078CEST | lvl=INFO | trans=1432833146-948-0000000000 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[193] : Finishing transaction (1432833146-948-0000000000)
time=2015-05-28T19:13:13.354CEST | lvl=INFO | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[150] : Starting transaction (1432833146-948-0000000001)
time=2015-05-28T19:13:13.357CEST | lvl=INFO | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[236] : Received data ({  "subscriptionId" : "55674ca9bb31a81984d9e8ce",  "originator" : "localhost",  "contextResponses" : [    {      "contextElement" : {        "type" : "VIOLETA",        "isPattern" : "false",        "id" : "FLOW3",        "attributes" : [          {            "name" : "temperature",            "type" : "centigrade",            "value" : "444",            "metadatas" : [              {                "name" : "MetaTest",                "type" : "TestType1",                "value" : "UPDATED"              }            ]          }        ]      },      "statusCode" : {        "code" : "200",        "reasonPhrase" : "OK"      }    }  ]})
time=2015-05-28T19:13:13.358CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[241] : Adding flume event header (name=content-type, value=application/json)
time=2015-05-28T19:13:13.358CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[244] : Adding flume event header (name=fiware-service, value=city011)
time=2015-05-28T19:13:13.358CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[247] : Adding flume event header (name=fiware-servicepath, value=electricidad)
time=2015-05-28T19:13:13.358CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[250] : Adding flume event header (name=transactionId, value=1432833146-948-0000000001)
time=2015-05-28T19:13:13.359CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[252] : Adding flume event header (name=ttl, value=10)
time=2015-05-28T19:13:13.359CEST | lvl=INFO | trans=1432833146-948-0000000001 | function=getEvents | comp=Cygnus | msg=com.telefonica.iot.cygnus.handlers.OrionRestHandler[258] : Event put in the channel (id=874329857, ttl=10)
time=2015-05-28T19:13:13.362CEST | lvl=INFO | trans=1432833146-948-0000000001 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[128] : Event got from the channel (id=874329857, headers={timestamp=1432833193359, content-type=application/json, transactionId=1432833146-948-0000000001, fiware-service=city011, fiware-servicepath=electricidad, ttl=10, destination=flow3_violeta}, bodyLength=641)
time=2015-05-28T19:13:13.365CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=persist | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[182] : [mysql-sink] Processing context element (id=FLOW3, type= VIOLETA)
time=2015-05-28T19:13:13.365CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=persist | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[221] : [mysql-sink] Processing context attribute (name=temperature, type=centigrade)
time=2015-05-28T19:13:13.365CEST | lvl=INFO | trans=1432833146-948-0000000001 | function=persist | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionMySQLSink[240] : [mysql-sink] Persisting data at OrionMySQLSink. Database: city011, Table: electricidad_flow3_violeta, Timestamp: 2015-05-28T17:13:13.359Z, Data (attrs): {temperature=444}, (metadata): {temperature_md=[{"name":"MetaTest","type":"TestType1","value":"UPDATED"}]}
time=2015-05-28T19:13:13.366CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=insertContextData | comp=Cygnus | msg=com.telefonica.iot.cygnus.backends.mysql.MySQLBackend[216] : Executing MySQL query 'insert into `electricidad_flow3_violeta` (recvTime,temperature,temperature_md) values ('2015-05-28T17:13:13.359Z','444','[{"name":"MetaTest","type":"TestType1","value":"UPDATED"}]')'
time=2015-05-28T19:13:13.368CEST | lvl=DEBUG | trans=1432833146-948-0000000001 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[139] : [com.telefonica.iot.cygnus.backends.mysql.MySQLBackend.insertContextData(MySQLBackend.java:221), com.telefonica.iot.cygnus.sinks.OrionMySQLSink.persist(OrionMySQLSink.java:243), com.telefonica.iot.cygnus.sinks.OrionSink.persist(OrionSink.java:242), com.telefonica.iot.cygnus.sinks.OrionSink.process(OrionSink.java:133), org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68), org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147), java.lang.Thread.run(Thread.java:745)]
time=2015-05-28T19:13:13.368CEST | lvl=WARN | trans=1432833146-948-0000000001 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[182] : Bad context data (Table 'smartvalencia.electricidad_flow3_violeta' doesn't exist)
time=2015-05-28T19:13:13.368CEST | lvl=INFO | trans=1432833146-948-0000000001 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[193] : Finishing transaction (1432833146-948-0000000001)
...

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/446

**Comment by frbattid** [comment]
Waiting for @mcarracedo LGTM allowing closing the issue.

**Comment by iariasleon** [comment]
LGTM by @mcarracedo see comment below:
https://github.com/telefonicaid/fiware-cygnus/pull/446#issuecomment-106760421
