### ISSUE TITLE
[all sinks] Remove XML notifications

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#448]
Start by removing from the documentation all references to XML-based notifications.

In future releases the XML parsing code will be definitely removed.

**Comment by frbattid** [comment]
This must be aligned with Orion. If Orion team doesn't deprecate XML in Orion's future release, then do not deprecate it in Cygnus.

**Comment by fgalan** [comment]
I'd say that XML removal in the doc can be done now, but that for removing XML functionality in the Cygnus should wait until XML is deprecated in Orion (months).

**Comment by frbattid** [comment]
This issue is related to https://github.com/telefonicaid/fiware-cygnus/issues/382

**Comment by frbattid** [comment]
As a reminder, this line in `OrionRESTHandler` must be removed as part of the process of removing XML:

    data = data.replaceAll(">[ ]*<", "><");

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/847
