### ISSUE TITLE
[releasing] Avoid recursivity when remove files (rm -rf ...) in package.sh

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-cygnus#474]
Or append control before in paths, to avoid empty path.

ex:
```
rm -rf ${RPM_SOURCE_DIR}/${FLUME_WO_TAR}
rm -rf ${FLUME_WO_TAR}/docs # erase flume documentation
rm ${FLUME_WO_TAR}/conf/flume-conf.properties.template # we will add our own templates
rm -rf ${RPM_PRODUCT_SOURCE_DIR}
mkdir -p ${RPM_PRODUCT_SOURCE_DIR}
cp -R ${FLUME_WO_TAR}/* ${RPM_PRODUCT_SOURCE_DIR}/
popd &> /dev/null
rm -rf ${TMP_DIR}
```

**Comment by mcarracedo** [comment]
how about if ${RPM_SOURCE_DIR} and ${FLUME_WO_TAR} are empty?

rm -rf ${RPM_SOURCE_DIR}/${FLUME_WO_TAR} --> rm -rf /

**Comment by vgarciag** [comment]
This bug has been closed because the variables are initialised at the beginning of the script and it never will be empty. 

@mcarracedo: the scripts checks that the execution user is not root, so `rm` commands are more "safely". This is a good practice in rpm generation.
