### ISSUE TITLE
[OrionHDFSSink] The CSV field separator character may be configurable

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#495]
When using `csv-row` and `csv-column`, the field separator character for CSV format is hardcoded to ','. This may lead to bad interpretation of the CSV y the saved entitie's value contains ','. Thus, in order to move the responsability to the user, the field separator character could be configurable.

**Comment by fgalan** [comment]
Would Cygnus implement separator character escaping (in this case, the character to scape would depend on the one chosen by the user)?

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/699
