### ISSUE TITLE
[OrionMySQLSink] Add some interesting fields both to row and column mode, including migration scripts

### ISSUE THREAD

**Issue by mecmTID** [telefonicaid/fiware-cygnus#501]
When using the MySQL connector it would be useful to be able to select entityId as one of the fields to be inserted in the database, particularly when using column mode, as this is an easy way to identify different entities in the data table.

**Comment by frbattid** [comment]
+1 to this issue, nevertheless, still thinking how to ensure backward compatibility. I mean, there are FIWARE users currently using `OrionMySQLSink` in column mode and their tables do not expect to receive any entityId as part of the data.

**Comment by frbattid** [comment]
This issue is going to evolve into a complex one. We are going to add the following fields, depending on the attr_persistence/mode:

* "row" mode: fiware-servicePath will be added.
* "column" mode: fiware-servicePath, entityId and entityType will be added.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/588
