### ISSUE TITLE
[OrionPostgreSQLSink] Create

### ISSUE THREAD

**Issue by c-castillo** [telefonicaid/fiware-cygnus#511]
We are currently using Orion + Cygnus components in one of our applications.
We are persisting data into a mysql database, using a django backend.
The optimal schema for multi-tenancy at app level is using postgresql schemas (ref: https://github.com/bernardopires/django-tenant-schemas), so it would be desirable to have a postgresql connector to implement the multi-tenancy approach at schema-level (instead of the  single-database-per-tenant approach)

**Comment by silva96** [comment]
:+1:

**Comment by dimh** [comment]
:+1:

**Comment by frbattid** [comment]
I've assigned the issue to @c-castillo since I've understood he is in charge of the development, while @hermanjunge is in charge of QA, right?

**Comment by hermanjunge** [comment]
Not quite right, as we are both developers, and we have a specific person to perform QA. But in the facts, for this issue, this is true.

**Comment by frbattid** [comment]
OK, understood :)

**Comment by nkittsteiner** [comment]
👍

**Comment by frbattid** [comment]
Moved to 0.12.0

FYI, there is a development team in Valencia that has created another version for this sink. It will ne merged for 0.12.0, in addition to the implementation the Chile team is creating.

**Comment by j99ht** [comment]
Hello, the implementation in Docker Hub, tidchile/cygnus-postgresql, can it already be used? Thanks

**Comment by silva96** [comment]
We are already using it but in order to be merged there are some tests to
write that we haven't. (We have been using it for 3 months and no problems
yet)

Best

**Comment by j99ht** [comment]
Thanks for your prompt reply.

Can you please copy the agent.conf file you are using?


2016-01-18 11:59 GMT+01:00 Benjamín Silva <notifications@github.com>:

> We are already using it but in order to be merged there are some tests to
> write that we haven't. (We have been using it for 3 months and no problems
> yet)
>
> Best

**Comment by frbattid** [comment]
As @silva96 says, this is currently under code review and some things must be still added (mainly documentation and tests). Thus @j99ht , keep this in mind when using it :)

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/683

**Comment by silva96** [comment]
Benjamin te recomienda usar Fintual
              
              
            
            
  
  
    Fintual es un asesor online que te ayuda a invertir tu dinero para que puedas usar tu tiempo en otras cosas. Es seguro y regulado por la CMF.
    Al crear tu cuenta, pon el código benjamins9 y premiaremos a Benjamin por hacerte esta recomendación tan buena.
    ACEPTAR LA INVITACIÓN
    Benjamin Silva
      Inversionista en Fintual hace 5 meses
  
  


            
              
              
                
                  fintual.cl

**Comment by nkittsteiner** [comment]
@silva96 malware?

**Comment by silva96** [comment]
No, un error capa 8. Invite a mis contactos de Gmail y por alguna razón, este isssue estaba dentro de mis contactos jaja

**Comment by hermanjunge** [comment]
Hola, vengo a flotar

**Comment by c-castillo** [comment]
🤔
