### ISSUE TITLE
[releasing] Create a docker container for Cygnus

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#536]
Guidelines: http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Docker

**Comment by hermanjunge** [comment]
To test the cygnus system, regardless the system you are, I'm working on this repository. Maybe it could be a good idea to include a _testing_ image and orchestrator besides the running one.

Also, TID Chile currently has a container to run Cygnus. We may take a look at it, and work from there.

**Comment by frbattid** [comment]
Go for it, Herman! :)

Just remember the mandatory guidelines we already discussed offline:

* A "docker" folder must exist within the root folder of fiware-cygnus.
* A README file must exist within fiware-cygnus/docker.
* A dockerfile in charge of installing Cygnus must exist within fiware-cygnus/docker.
* A .yml file in charge of installing the dependencies must exist within fiware-cygnus/docker.

**Comment by frbattid** [comment]
In addition, the image must be pushed into https://hub.docker.com/u/fiware/

**Comment by fgalan** [comment]
Maybe it could help to have a look how this has been implemented in Orion repository:

https://github.com/telefonicaid/fiware-orion/tree/develop/docker

**Comment by frbattid** [comment]
Yes, that's the reference we were discsussing ;)

**Comment by hermanjunge** [comment]
https://github.com/telefonicaid/fiware-cygnus/pull/545

**Comment by acs** [comment]
In the FIWARE devguide project we have created some months ago a Docker image for Cygnus.

https://github.com/Bitergia/fiware-chanchan-docker/tree/master/images/cygnus

It is available from Docker Hub for easy deployment:

https://hub.docker.com/r/bitergia/cygnus/

We have a docker-compose for Cygnus: 

https://github.com/Bitergia/fiware-chanchan-docker/blob/master/compose/cygnus.yml

and for cygnus working with IDAS also:

https://github.com/Bitergia/fiware-chanchan-docker/blob/master/compose/idas-cygnus.yml

If you find this work useful we can support you reusing anything you find valuable.

Cheers

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/545

**Comment by acs** [comment]
Francisco, are you going to publish the docker image in Docker hub? I am not sure that with the current build process from sources, the docker image could be built automatically in docker hub. But maybe you are going to publish just the binary version.

**Comment by frbattid** [comment]
As per:
https://github.com/Fiware/tutorials.TourGuide-App/issues/43

Cygnus docker image has flaws. This ticket requests a fix as per:
http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Docker

**Comment by hermanjunge** [comment]
OK. I'm taking over. Will output a `quick-start document for busy people` and a document to maintain the images in the docker hub, plus the required images of the latest versions.

**Comment by hermanjunge** [comment]
1st is 1st. Please, mr @frbattid, do merge [This PR](https://github.com/telefonicaid/fiware-cygnus/pull/884), where I tell everybody that I'm a *n00b* in the java world.

After that, the new versions are to be found in [the docker hub](https://hub.docker.com/r/fiware/cygnus/tags/). 

Where do I put the instructions `Run the following commands once you have a new release done, to put its respective image into the docker hub` ????

HJ.-

**ps**: Instructions will be like

> Everytime we do a new version, please run the following commands

```
    docker-compose -f ./docker/0.compose.jar-compiler.yml -p cygnus run --rm compiler
    docker build -f ./docker/Dockerfile -t fiware/cygnus:<release version> .
    docker tag fiware/cygnus:<release version> fiware/cygnus:latest
    docker login
    docker push
```

**Comment by frbattid** [comment]
Merged, @hermanjunge . Regarding the guidelines you mention, I think the Docker README is the proper location: https://github.com/telefonicaid/fiware-cygnus/blob/master/docker/README.md

Simply add a new section, something like "How to proceed upon new Cygnus version releasing" or somethinkg like that.

**Comment by hermanjunge** [comment]
OK @frbattid, done at https://github.com/telefonicaid/fiware-cygnus/pull/903
