### ISSUE TITLE
[OrionMongoSink] Add "column"-like support

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#548]
As requested by a FIWARE user:
http://stackoverflow.com/questions/32841308/persist-data-to-mongodb-in-columns-instead-of-rows

**Comment by xdelox** [comment]
As I wrote on StackOverflow, I have implemented the missing methods. If there are no impediments, I can push my code.

**Comment by frbattid** [comment]
That would be great! Please, have into account several mandatory guidelines when contributing to this repo:

* The PR will try to merge the code into the `develop` branch.
* The `CHANGES_NEXT_RELEASE` file must be edited detailing the feature and the issue number.
* You must follow the checkstyle guidelines within https://github.com/telefonicaid/fiware-cygnus/blob/master/telefonica_checkstyle.xml
* A header like the following one must appear in all the files:
```
/**
* Copyright 2015 Telefonica Investigación y Desarrollo, S.A.U
*
* This file is part of fiware-cygnus (FI-WARE project).
*
* fiware-cygnus is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
* General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
* option) any later version.
* fiware-cygnus is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
* implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
* for more details.
*
* You should have received a copy of the GNU Affero General Public License along with fiware-cygnus. If not, see
* http://www.gnu.org/licenses/.
*
* For those usages not covered by the GNU Affero General Public License please contact with iot_support at tid dot es
*/
```
* That means Telefonica owns the property of the. Nevertheless, you may appear as the author, of course.

Regarding the Contribution Policy, that's addressed to partners aiming to contribute to the repo in a continued fashion. Sporadic contributions must ignore it.

**Comment by frbattid** [comment]
Assignee to @xdelox

**Comment by frbattid** [comment]
Dued to release/0.10.0 (end of October)

**Comment by xdelox** [comment]
In order to create the PR, I created a local branch from remote *develop* one.

Now I should push my local branch, named *feature/548_mongo_sink_column_like*, to the corrispective remote branch, but Intellij Idea returns me the following error.

>Push failed
>Failed with error: fatal: unable to access 'https://github.com/telefonicaid/fiware-cygnus/': The >requested URL returned error: 403

I made a mistake or I'm not enabled to do this operation?

Thanks.

S.

**Comment by frbattid** [comment]
I guess you did the following:

* Clone the repo
* Create a local branch named feature/548_mongo_sink_column_like
* Try to push the local branch to remote

That will not work since you are not within any allowd team.

The way to proceed is the following one:

* Fork the repo into your Github user space
* Clone the forked repo
* Create the local branch
* Push the local branch to the forked remote
* Then, do the PR from you forked remote to fiware-cygnus develop.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/551
