### ISSUE TITLE
[doc] Add an explanation about the version of the hadoop-core dependency

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#559]
Specially useful after merging the PR https://github.com/telefonicaid/fiware-cygnus/pull/557, which requires the `hadoop-core` version matches the one used in the HDFS backend.

**Comment by hermanjunge** [comment]
Hi. Currently, to compile my current version of `develop` (`3366184c`), I need to switch the version to `1.2.1`.

What are the procedure you implement to be able to compile the code? So I can make the fix in my compiler helpers?

**Comment by frbattid** [comment]
I'm currently documenting this, once finished you will be able to fix your compile helpers :)

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/581
