### ISSUE TITLE
[doc] Small bug in install from sources documentation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/fiware-cygnus#596]
In https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/installation/src_install.md

```
$ git clone https://github.com/telefonicaid/fiware-cygnus.git
$ git checkout <branch>
$ cd fiware-cygnus
```

The cd command must be done before checkout.

I think I have seen this is a couple of places...

**Comment by fgalan** [comment]
In addition, check that the persmissons of the cygnus-flume-ng script are correct. Maybe a chmod a+x command is missing.

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/597
