### ISSUE TITLE
[cygnus-ngsi][doc] Add complex configuration examples

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#629]
Specifically, those detailed in the configuration part of the Installation and Administration Guide:
- Single source, single storage (basic configuration)
- Single source, multiple storages
- Single source, single storage, parallel sinking
- Single source, multiple storages, parallel sinking
- Multiple sources
- Using interceptors
- Using batching

<b>Effort: 2 man day</b>

**Comment by frbattid** [comment]
In order to satisfy the issue https://github.com/telefonicaid/fiware-cygnus/issues/566, the "Using batching" section must explain only a `FileChannel` can temporarily store the events while being accumulated.

**Comment by taliaga** [comment]
Hi @frbattid!
One quick question, is the support ready/have you tested the `FileChannel` on cygnus already? Making a simple test with a single NGSIEvent the MemoryChannel works fine, but with the FileChannel I've had some issues

**Comment by frbattid** [comment]
Hi @taliaga , could you elaborate a bit more? Could you share your configuration and errors/problems you experienced? Thanks!

**Comment by taliaga** [comment]
Sure! I wanted to quickly double-check if the support was ready before I kept on inspecting my error logs :p. I've created #1419 with details so as not to pollute this thread.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/1420
