### ISSUE TITLE
[doc] Update the needed dependencies when installing form sources

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#635]
* Check the dependencies already listed for HDFS, CKAN and MySQL. Is someone missing? Are the versions OK?
* Add the needed dependencies for the rest of sinks

In addition, libthrift 0.9.1 can be added to the pom.xml, doing unnecessary it is manually downloaded.

<b>Effort: 1 man day</b>

**Comment by frbattid** [comment]
List of dependencies:

* Cygnus
    * flume-ng-core-1.4.0.jar
    * flume-ng-node-1.4.0.jar
    * gson-2.2.4.jar
    * json-simple-1.1.jar
    * xml-apis-1.2.01.jar
    * log4j-1.2.17.jar
* OrionHDFSSink
    * hadoop-core-1.2.1.jar (or higher)
    * hive-exec-0.13.0.jar
    * hive-jdbc-0.13.0.jar
    * httpclient-4.3.1.jar
    * httpcore-4.3.1.jar
    * jetty-server-7.2.0.v20101020.jar
* OrionMySQLSink
    * mysql-connector-java-5.1.31-bin.jar
* OrionCKANSink
    * httpclient-4.3.1.jar
    * httpcore-4.3.1.jar
* OrionDynamoDBSink
    * httpclient-4.3.1.jar
    * httpcore-4.3.1.jar
    * aws-java-sdk-dynamodb-1.10.32
* OrionMongoSink
    * mongo-driver-3.0.0.jar
* OrionSTHSink
    * mongo-driver-3.0.0.jar
* OrionKafkaSink
    * kafka-clients-0.8.2.0.jar
    * zkclient-0.5.jar
    * kafka_2.11-0.8.2.1
* Tests
    * mockito-all-1.9.5.jar
    * junit-4.11.jar
    * curator-test-2.8.0.jar

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/698
