### ISSUE TITLE
[doc] Add the minimum HW requirements

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#640]
Values to be explained:

* RAM: 1 GB, specially if abusing of the batching mechanism.
* HDD: A few GB may be enough unless the channel types are configured as FileChannel type.

This must be added as a new section in the README, under the "Basic operation" section, before the "Installation" subsection.

The "Installation and Administration Guide" must contain this kind of info as well. Particularly, this must be a second bullet between the "Introduction" and the "Installation" sections.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in PR <https://github.com/telefonicaid/fiware-cygnus/pull/655>
