### ISSUE TITLE
[releasing] The sufix added to the RPM name avoids to install through "yum install cygnus"

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#652]
Current way of adding the "hadoop-core" sufix to the RPM name avoids installing Cygnus as:

    $ yum install cygnus

And this must be done:

    $ yum install cygnus_hadoopcore_1.2.1

Since this is the name the RPM gets at the `cygnus.spec` file. It does not work renaming it after creation.

Thus, there are two options:

* Change (again) the way the sufix is added. This is currently working for me: `cygnus-0.11.0-1.g2a9c87f.x86_64.hadoop-core-1.2.1.rpm`
* Change the documentation by updating the `yum install` command.

**Comment by vgarciag** [comment]
This issue will be solved in PR #710. The adopted solution is leave the package name as `cygnus` and the rpm file name as `cygnus_hadoopcore_x.y.z-ver-rel-x86_64.rpm`

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/711
