### ISSUE TITLE
[OrionMongoSink, OrionSTHSink] Add an interface and an implementation to MongoBackend

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#654]
This is about creating a `MongoBackend` Java interface and a `MongoBackendImpl` Java class.

Currently, there is a `MongoBackend` Java class that must be renamed as `MongoBackendIml`. Then, a `MongoBackend` Java interface can be added.

As a reference, have a look on HDFS, CKAN or DynamoDB backends.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/674
