### ISSUE TITLE
[OrionDynamoDBSink] Document the maximum accepted batch size is 25

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#672]
Reference: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html

> BatchWriteItem
> A single BatchWriteItem operation can contain up to 25 PutItem or DeleteItem requests. The total size of all the items written cannot exceed 16 MB.

Thus, the configuration section at https://github.com/telefonicaid/fiware-cygnus/blob/master/doc/flume_extensions_catalogue/orion_dynamodb_sink.md, `batch_size` parameter, must specify this limit of 25 events.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/674
