### ISSUE TITLE
[OrionSTHSink] Include the possibility to ignore processing attribute values to blank spaces

### ISSUE THREAD

**Issue by gtorodelvalle** [telefonicaid/fiware-cygnus#678]
The cygnus via its OrionSTHSink should make it possible to the user decide if attribute values to one or more blank spaces should be processed (as raw data and for the 'occur' aggregated computations) or just ignored. By default, these attribute values should be directly ignored.

The equivalent PR for the STH component is https://github.com/telefonicaid/fiware-sth-comet/pull/204

**Comment by frbattid** [comment]
Issue https://github.com/telefonicaid/fiware-cygnus/issues/547 must be implemented before this one.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/878
