### ISSUE TITLE
[OrionMySQLSink] Add support for other data_models different than dm-by-entity or dm-by-service-path

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#687]
<b>Effort: 1 man day</b>

**Comment by pmo-sdr** [comment]
More than "one man day" for us anyway. :stuck_out_tongue_winking_eye:

**Comment by fgalan** [comment]
@frbattid estimation maybe was too optimistic ;)

**Comment by fgalan** [comment]
Implemented in PR #1634
