### ISSUE TITLE
[log4j] Do logging of the notified service and service-path

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#707]
Current conversion pattern in logs is:

    time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | trans=%X{transactionId} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n

Now, it is necessary to add the notified service and service-path (also know as subservice) involved in the trace. This is the new format:

    time=%d{yyyy-MM-dd}T%d{HH:mm:ss.SSSzzz} | lvl=%p | trans=%X{transactionId} | srv=%X{service} | subsrv=%X{subservice} | function=%M | comp=Cygnus | msg=%C[%L] : %m%n

The way the service and service-path are "sent" to the log4j engine is by means of MDC (Mapped Diagnostic Context), as done with the transaction id.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/708
