### ISSUE TITLE
[OrionHDFSSink] grouping entities does not work

### ISSUE THREAD

**Issue by veonline** [telefonicaid/fiware-cygnus#735]
i'm struggling with the grouping feature with hdfs.
it does make the grouping but it still keep the original destination (used for the third level and the file name) with the entity id instead the custom destination specified in the ruleset.
i've triple checked everything, the configurations sounds good.

**Comment by frbattid** [comment]
Which version are you using?

**Comment by veonline** [comment]
the Apache Flume is 1.4.0
how do i see the exact version of cygnus?

**Comment by frbattid** [comment]
How did you installed it?

**Comment by veonline** [comment]
yum... it's cygnus-0.11.0-1.g2a9c87f.x86_64

**Comment by frbattid** [comment]
Are you using the batching mechanism? We detected a [bug](https://github.com/telefonicaid/fiware-cygnus/issues/675
) in the grouping rules when batching was enabled.

It has been fixed in the new release, [0.12.0](https://github.com/telefonicaid/fiware-cygnus/releases/tag/release-0.12.0)

**Comment by veonline** [comment]
i have specified no batching options on my agent config

**Comment by frbattid** [comment]
Can you post your configuration? And your grouping rules? Even, the relevant part of the logs where the error can be seen. Thanks!

**Comment by veonline** [comment]
agent config
`cygnusagent.sources = http-source
cygnusagent.sinks = waspmotes-sink
cygnusagent.channels = waspmotes-channel

cygnusagent.sources.http-source.channels = waspmotes-channel
cygnusagent.sources.http-source.type = org.apache.flume.source.http.HTTPSource
cygnusagent.sources.http-source.port = 5050
cygnusagent.sources.http-source.handler = com.telefonica.iot.cygnus.handlers.OrionRestHandler
cygnusagent.sources.http-source.handler.notification_target = /notify
cygnusagent.sources.http-source.handler.default_service = Agricolus
cygnusagent.sources.http-source.handler.default_service_path = WaspMotesDatas
cygnusagent.sources.http-source.handler.events_ttl = 2
cygnusagent.sources.http-source.interceptors = gi ts
cygnusagent.sources.http-source.interceptors.ts.type = timestamp
cygnusagent.sources.http-source.interceptors.gi.type = com.telefonica.iot.cygnus.interceptors.GroupingInterceptor$Builder
cygnusagent.sources.http-source.interceptors.gi.grouping_rules_conf_file = /usr/cygnus/conf/grouping_rules.conf

cygnusagent.channels.waspmotes-channel.type = memory
cygnusagent.channels.waspmotes-channel.capacity = 1000
cygnusagent.channels.waspmotes-channel.transactionCapacity = 100

cygnusagent.sinks.waspmotes-sink.channel = waspmotes-channel
cygnusagent.sinks.waspmotes-sink.type = com.telefonica.iot.cygnus.sinks.OrionHDFSSink

cygnusagent.sinks.waspmotes-sink.hdfs_host = 192.168.1.41
cygnusagent.sinks.waspmotes-sink.hdfs_port = 50070
cygnusagent.sinks.waspmotes-sink.hdfs_username = hduser
cygnusagent.sinks.waspmotes-sink.attr_persistence = row
cygnusagent.sinks.waspmotes-sink.file_format = json-row
cygnusagent.sinks.waspmotes-sink.enable_grouping = true
cygnusagent.sinks.waspmotes-sink.backend_impl = rest

cygnusagent.sinks.waspmotes-sink.hive = true
cygnusagent.sinks.waspmotes-sink.hive.server_version = 2
cygnusagent.sinks.waspmotes-sink.hive.host = localhost
cygnusagent.sinks.waspmotes-sink.hive.port = 10101`

grouping rules
`{
    "grouping_rules": [
        {
            "id": 1,
            "fields": [
                "entityType"
            ],
            "regex": "WaspMote",
            "destination": "AllWaspMotesDatas",
            "fiware_service_path": ""
        },
        {
            "id": 2,
            "fields": [
                "entityType"
            ],
            "regex": "WaspMote.*",
            "destination": "WaspMotesDataCollection",
            "fiware_service_path": "/waspmotedatacollectionservicepath"
        }
    ]
}
`
(first rule will not be applied 'cause of fiware_service_path is empty, right?)

there is no explicit errors in the log, i can only see the behaviour by the results (no waspmotesdatacollection.txt anyware in the hdfs).
anyway those are the part that seems most important
`03 Feb 2016 10:34:58,238 DEBUG [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.OrionSink.process:163)  - Event got from the channel (id=2069739836, headers={timestamp=1454492097340, content-type=application/json; charset=utf-8, transactionId=1454427955-967-0000000034, grouped-fiware-servicepaths=waspmotedatacollectionservicepath, grouped-destinations=waspmotesdatacollection, fiware-service=agricolus, default-fiware-servicepaths=waspmotesdatas, fiware-servicepath=waspmotesdatas, ttl=2, default-destinations=waspmote_test_2_waspmote}, bodyLength=1838)
`
`03 Feb 2016 10:34:58,403 INFO  [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.telefonica.iot.cygnus.sinks.OrionHDFSSink.persistAggregation:920)  - [waspmotes-sink] Persisting data at OrionHDFSSink. HDFS file (agricolus/waspmotedatacollectionservicepath/waspmote_test_2_waspmote/waspmote_test_2_waspmote.txt), Data`

**Comment by veonline** [comment]
the issue persist also with the latest version from git

**Comment by frbattid** [comment]
Thank! Having this information, I'll try to reproduce the error and I'll figure out what is happening.

**Comment by veonline** [comment]
i correct myself: it DOES work with the latest version from git, i did'n properly clear old jars

**Comment by frbattid** [comment]
Oh, that sounds good! Anyway, I would like to find out which is the problem regarding 0.11.0.

**Comment by frbattid** [comment]
This was related to https://github.com/telefonicaid/fiware-cygnus/issues/675, which is already fixed in newest versions of Cygnus.
