### ISSUE TITLE
[OrionKafkaSink] Replication factor and partitions for topics must be set in agent

### ISSUE THREAD

**Issue by pcoello25** [telefonicaid/fiware-cygnus#736]
Kafka allows us to set the `--replication-factor` and the number of `--partitions` when creating a topic:
```
> bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test
```
Our actual sink sets `--replication-factor` and `--partitions` to 1

It could be useful setting these parameters in the agent, by adding:
```
cygnusagent.sinks.kafka-sink.replication-factor = 3
cygnusagent.sinks.kafka-sink.partitions = 5
```
Both settings are important for fault tolerance; this give us safety and avoid posible failures reading of the information.

**Comment by frbattid** [comment]
+1, assigning it to you, @pcoello25 ;)

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/753
