### ISSUE TITLE
[OrionSink] replace Accumulator.getAccumulatorForRollback() with Accumulator.clone()

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#746]
Current way of obtaining a clone for a `Accumulator` object is by invoking the `getAccumulatorForRollback` method. This could be replaced by the built-in Java method `clone()`.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/755
