### ISSUE TITLE
[all sinks] Check for input parameters validity

### ISSUE THREAD

**Issue by pcoello25** [telefonicaid/fiware-cygnus#752]
For instance:

* Derived from #718: All sinks must stop when getting an inexistent data_model. The check must be done at the `configure` method of `OrionSink`.
* hive.server_version` can only take `1` or `2`.
* `attr_persistence` can only take `row` or `column`
* etc.

<b>Effort: 1 man day</b>

**Comment by frbattid** [comment]
This issue could be made more ambitious and become an issue about checking the validity of all the configuration parameters.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/786
