### ISSUE TITLE
[configuration] Wrong data_model configured in agent.conf.template

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#774]
As experienced by a user in https://github.com/telefonicaid/fiware-cygnus/issues/760.

Currently:

    cygnusagent.sinks.postgresql-sink.data_model = by-service-path

Must be:

    cygnusagent.sinks.postgresql-sink.data_model = dm-by-service-path

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/776
