### ISSUE TITLE
[tests] Deploy an environment for e2e tests shared by all the team

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#777]
Current e2e tests are done against private storages deployed in our laptops of working machines.

A shared environment among all the members of the Cygnus development team must be created containing at least:

* MySQL
* PostgreSQL
* MongoDB / STH
* Kafka

If could be useful having a private CKAN instance as well, but in the meantime `demo.ckan.org` can be used as usual.

Regarding DynamoDB, this is an Amazon cloud-based service that cannot be instantiated by a user.

Regargind Cosmos/Hadoop, we can continue using the FIWARE Lab's global instance as usual.

**Comment by frbattid** [comment]
As derived from an internal request, this server could also be opened to other developers, members of FIWARE, for integration purposes (e.g. SpagoBI).

**Comment by frbattid** [comment]
Thinking on a way of documenting this, I've come uo with the following: all the e2e VM stuff can be documented in a private Google doc, only accessible to certain persons (dev team, authorized testers, etc). Authorization in Google docs is done per email account. Then, a public document can be created in this repo, linking to the private Google doc and a little remark about its purpose.

Within this repo, such a document may be under `test/e2e/`.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/832
