### ISSUE TITLE
[api] Add /v1/subscriptions route

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#808]
Operations to implement:

- [x] `POST /v1/subscriptions?ngsi_version=1|2` (creates a new subscription)
- [x]  |____ TESTS 
- [x] `DELETE /v1/subscriptions?ngsi_version=1|2&subscription_id=<id>` (deletes a subscription given its ID)
- [x] |____ TESTS 
- [x] `GET /v1/subscriptions?ngsi_version=1|2` (gets all the subscriptions fot the authenticated user)
- [x] |____ TESTS
- [x] `GET /v1/subscriptions?ngsi_version=1|2&subscription_id=<id>` (gets a subscription given its ID)
- [x] |____ TESTS

**Comment by pcoello25** [comment]
Same to do subscriptions, a user can ask for latest subscriptions or unsubscribe. 
Next steps could be:
  * GET /v1/subscriptions
  * POST /v1/unsubscribe

**Comment by frbattid** [comment]
I like the idea, specially unsubscribe.

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/879 (GET `/v1/subscriptions`)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/956 (`DELETE /v1/subscriptions?ngsi_version=1|2&subscription_id=<id>`)

**Comment by pcoello25** [comment]
Update documentation (.apib & .md) in https://github.com/telefonicaid/fiware-cygnus/pull/1000

**Comment by pcoello25** [comment]
Added test for POST subscriptions -> https://github.com/telefonicaid/fiware-cygnus/pull/1039

**Comment by pcoello25** [comment]
Added test for DELETE subscriptions -> https://github.com/telefonicaid/fiware-cygnus/pull/1041

**Comment by pcoello25** [comment]
Added tests for GET subscriptions -> https://github.com/telefonicaid/fiware-cygnus/pull/1046

**Comment by pcoello25** [comment]
Added GET method for retrieve all subscriptions https://github.com/telefonicaid/fiware-cygnus/pull/1060

**Comment by pcoello25** [comment]
Added tests for GET all subscriptions -> #1062

**Comment by pcoello25** [comment]
Added documentation for GET all subscriptions -> https://github.com/telefonicaid/fiware-cygnus/pull/1065
