### ISSUE TITLE
[releasing] Missing build on Docker hub

### ISSUE THREAD

**Issue by web-bert** [telefonicaid/fiware-cygnus#810]
There isn't a build on [docker hub](https://hub.docker.com/r/fiware/cygnus/) as mentioned in the readme?

**Comment by frbattid** [comment]
Ping to @hermanjunge ;)

**Comment by hermanjunge** [comment]
Not yet. Need to coordinate one. I'm skypying you @frbattid

**Comment by frbattid** [comment]
Waiting for the FIWARE credentials in dockerhub.

**Comment by hermanjunge** [comment]
Ok, [is done!](https://hub.docker.com/r/fiware/cygnus/tags/)
