### ISSUE TITLE
[utils] Add an efficient function for converting ArrayLists to String

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#841]
Add a new static method `String Utils.toString(ArrayList)`.

Use the method proposed at http://stackoverflow.com/questions/599161/best-way-to-convert-an-arraylist-to-a-string

This utility function must replace current way of creating String from ArrayLists, such as: the following code wihtin `GroupingInterceptor.intercept()`:

```
headers.put(Constants.FLUME_HEADER_NOTIFIED_ENTITIES,
                defaultDestinations.toString().replaceAll("\\[", "").replaceAll("\\]", "").replaceAll(" ", ""));
```

<b>Effort: 1 man day</b>

**Comment by frbattid** [comment]
Of course, once added the utility function it must be used in all the code instead of current converting methods (typically, doing `toString().replaceAll("\\[", "").replaceAll("\\]", "").replaceAll(" ", "")`).

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/845
