### ISSUE TITLE
Question for INFO logs release/0.11.0 and higher

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-cygnus#848]
With cygnus logs at level INFO (very useful logs, more than WARN), we see many repeated logs at time as:
```
time=2016-03-04T13:40:13.556CET | lvl=INFO | trans= | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[246] : Batch accumulation time reached, the batch will be processed as it is
time=2016-03-04T13:40:13.556CET | lvl=INFO | trans= | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[295] : Finishing transaction ()
time=2016-03-04T13:40:13.747CET | lvl=INFO | trans=1457030172-356-0000000007 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[246] : Batch accumulation time reached, the batch will be processed as it is
time=2016-03-04T13:40:13.748CET | lvl=INFO | trans=1457030172-356-0000000007 | function=process | comp=Cygnus | msg=com.telefonica.iot.cygnus.sinks.OrionSink[295] : Finishing transaction ()
```
But for the level info seems too repetitive information, with high io/cpu use.
You could write this information at a lower level, or otherwise?
Regards

**Comment by frbattid** [comment]
Hi @cesarjorgemartinez , such a verbosity when working with `INFO` level is a requirement from our commercial units. It cannot be changed.

**Comment by frbattid** [comment]
Hi @cesarjorgemartinez , please have a look on the following issues:

* https://github.com/telefonicaid/fiware-cygnus/issues/881
* https://github.com/telefonicaid/fiware-cygnus/issues/882

They should highly reduce the number of logs, at least those regarding third party dependencies used by Cygnus.
