### ISSUE TITLE
[OrionSTHSink] Wrong class name in configuration section of OrionSTHSink.md 

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#852]
Currently, it is written:

    com.telefonica.iot.cygnus.sinks.OrionMongoSink

It must be:

    com.telefonica.iot.cygnus.sinks.OrionSTHSink

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/853
