### ISSUE TITLE
[grouping rules] Parse the grouping rules by means of Gson

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#854]
Currently, the rules parsing is done by means on `JSONParser`. Using Gson is a more elegant and clean way of doing it, through the definition of container classes. As a reference, `NofifyContextRequest` is a container for the notifications parsing.

<b>Effort: 2 man day</b>

**Comment by pcoello25** [comment]
I've tested the way of using this method but it's worst than the actual method (as @frbattid and me have seen today).

Use `GSON` is useful when a `JSON` only contains Strings. Our case has both  strings and arraylist, so we would implement a test for each arraylist (case of 'CygnusSubscriptions' we need 5 tests for know if we have a valid JSON for that purpose).

If you see it right then closes the issue @frbattid :)

**Comment by frbattid** [comment]
Closing since Grouping Rules will be deprecated once version 1.6.0 is released (at the moment of closing this, working on such a release).
