### ISSUE TITLE
[repo] Refactor the repo in a per agent fashion

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#864]
The repo must be refactored in a per agent fashion. Current existing development will considered the NGSI agent, and will be re-located under `ngsi/` containing its own `doc/`, `conf/`, `test/` and `src/`. Then other agents could be addded by internal/external contributors.

- fiware-cygnus/
    - common/
        - doc/
        - conf/
        - test/
        - src/
    - ngsi/
        - doc/
        - conf/
        - test/
        - src/
    - utool/
        - doc/
        - conf/
        - test/
        - src/
    - other

Still thinking how to proceed (in the long term) with the releasing mechanisms, i.e. `docker/` and `neore/` folders. In the short/mid term, the NGSI agent will still handling its own specific stuff.

**Comment by frbattid** [comment]
Regarding the common folder, this should include the following code:

* Backends, which must be as generic purpose as possible, in order to serve all the different agent sinks.
* Cygnus channels allowing for statistics retrieving.
* Errors classes.
* Logging facilities.

**Comment by javipalanca** [comment]
Great. Waiting for this refactor to include our agent. Btw, since our agent is a generic agent to retrieve tweets, maybe "utool" is not an appropriate name. I suggest "twitter" or "sna" (for social network analysis).

**Comment by frbattid** [comment]
This must imply the creation of tags per agent. Then, each issue may be labeded.

**Comment by frbattid** [comment]
Another advantage of this refactor is new agents can be created as context adapters.

**Comment by frbattid** [comment]
Partially implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/941 (folder refactoring)
