### ISSUE TITLE
[OrionMongoSink, OrionSTHSink] No date conversion when a year, due to ISO 8601 UTC conversion, must be decreased

### ISSUE THREAD

**Issue by XavierVal** [telefonicaid/fiware-cygnus#873]
Release tag v0.13.0

When sending metadata updates to OrionMongoSink (or OrionSTHSink) the conversion to ISO 8601 UTC is not working appropiately when it implies a change of year.

Sending this kind of metadata to CB should be imply a notification for storing in STH the TimeInstant instead of the reception time in ISO 8601 format (UTC means -2 hours in the testing machine):

```
		"attributes": [{
			"type": "centigrade",
			"name": "temperature",
			"value": "999",
			"metadatas": [{
				"type": "recvTime",
				"name": "TimeInstant",
				"value": "2029-09-09T09:09:09.990Z"
				}] 

```
| TARGET | Notified TimeInstant (SQL timestamp)       | Expected datetime in STH (UTC)          | Persisted datetime in STH (UTC) | Result | 
| ----------------- |:-----------------:| -----------------:| -----------------:| -----------:|
| DAY -- |2015-09-02 01:10:10   | 2015-09-01T23:10:10.000Z | 2015-09-01T23:10:10.000Z | OK|
| MONTH -- | 2016-10-01 01:22:10 | 2016-09-30T23:22:10.000Z | 2016-09-30T23:22:10.000Z |OK|
| YEAR -- | 2017-01-01 00:00:02 | 2016-12-31T23:00:02.000Z | 2016-03-14T15:39:02.417Z (current) | FAIL|
| || | |

**Comment by XavierVal** [comment]
Updated metadata date value

**Comment by frbattid** [comment]
This is because the pattern matchers are written as `yyyy-MM-dd hh:mm:ss.SSS` instead of `yyyy-MM-dd HH:mm:ss.SSS`.

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/908 (`release/0.13.0` branch)
