### ISSUE TITLE
[all sinks] Improve the different elements naming when notified/default service path is /

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#877]
Current behaviour:

* OrionHDFSSink: `/user/myuser/myservice//myentityId_myentityType/myentityId_myentityType.txt`
* OrionMySQLSink: database `myservice`, table `_myentityId_myentityType`
* OrionCKANSink: orgName `myservice`, pkgName `myservice`, resName `myentityId_myentityType`
* OrionSTHSink/OrionMongoSink: database `sth_myservice`, collection `sth_/_myentityId_myentityType`
* OrionKafkaSink: <b>error</b> --> "Path must not end with / character" !!!
* OrionDynamoDBSink: `myservice__myentityId_myentityType`
* OrionPostgreSQLSink: schema `myservice`, table `_myentityId_myentityType`

In addition, `subsvc` field in log4j logs is empty when `/` is notified (or configured as default).

Do we accept this default behaviour? Alternatives?

My proposal:

* OrionHDFSSink --> `/` instead of `//`
* OrionMySQLSink --> remove the initial `_`
* OrionCKANSink --> it's OK
* OrionMongoSink/OrionSTHSink --> they are OK
* OrionKafkaSink --> must be fixed
* OrionDynamoDBSink --> `_` instead of `__`
* OrionPostgreSQLSink --> remove the initial `_`

**Comment by frbattid** [comment]
This must be applied both to release/0.13.0 and release/0.14.0

**Comment by manucarrace** [comment]
LGTM

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/883 (develop branch)
