### ISSUE TITLE
[OrionKafkaSink] Expand topic name

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#880]
Currently:

* If `data_model=dm-by-service` then `topic_name=<service>`.
* If `data_model=dm-by-service-path` then `topic_name=<service-path>`.
* If `data_model=dm-by-entity` then `topic_name=<entity>`.
* If `data_model=dm-by-attribute` then `topic_name=<attribute>`.

This should be instead ("normal" service-path starting with `/' ):

* If `data_model=dm-by-service` then `topic_name=<service>`.
* If `data_model=dm-by-service-path` then `topic_name=<service>_<service-path_without_slash>`.
* If `data_model=dm-by-entity` then `topic_name=<service>_<service-path_without_slash>_<entityId>_<entityType>`.
* If `data_model=dm-by-attribute` then `topic_name=<service>_<service-path_without_slash>_<entityId>_<entityType>_<attrName>_<attrType>`.

When the service-path is `/`:

* If `data_model=dm-by-service` then `topic_name=<service>`.
* If `data_model=dm-by-service-path` then `topic_name=<service>`.
* If `data_model=dm-by-entity` then `topic_name=<service>_<entityId>_<entityType>`.
* If `data_model=dm-by-attribute` then `topic_name=<service>_<entityId>_<entityType>_<attrName>_<attrType>`.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Some tests are going to be implemented with the PR:

Getting `service-path` starts with '/' :
- [ ] If `data_model = dm-by-service` then `topic_name = <service>`
- [ ] If `data_model = dm-by-service-path` then `topic_name = <service>_<service-path_without_slash>`
- [ ] If `data_model=dm-by-entity` then `topic_name=<service>_<service-path_without_slash>_<entityId>_<entityType>`.
- [ ] If `data_model=dm-by-attribute` then `topic_name=<service>_<service-path_without_slash>_<entityId>_<entityType>_<attrName>_<attrType>`.

Getting `service-path = '/'` :
- [ ] If `data_model=dm-by-service` then `topic_name=<service>`.
- [ ] If `data_model=dm-by-service-path` then `topic_name=<service>`.
- [ ] If `data_model=dm-by-entity` then `topic_name=<service>_<entityId>_<entityType>`.
- [ ] If `data_model=dm-by-attribute` then `topic_name=<service>_<entityId>_<entityType>_<attrName>_<attrType>`.

**Comment by pcoello25** [comment]
After reviews with this PR we are going to need 3 differents fixes now:
- [ ] PR for the create the correct topic name
- [ ] PR for refactor the code in order to create the tests 
- [ ] PR for add the tests

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/905

**Comment by pcoello25** [comment]
Current tests deleted in https://github.com/telefonicaid/fiware-cygnus/pull/915

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/926

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/929

**Comment by pcoello25** [comment]
Implemented in #915 , #926, and #929
