### ISSUE TITLE
[doc] Several wrong links

### ISSUE THREAD

**Issue by miguelbemartin** [telefonicaid/fiware-cygnus#885]
Error link in documentation
https://github.com/telefonicaid/fiware-cygnus#section2.3 > 
https://github.com/telefonicaid/fiware-cygnus/blob/master/installation_and_administration_guide/introduction.md

**Comment by frbattid** [comment]
It is curious: the "configuration" section of the README works properly when browsing from https://github.com/telefonicaid/fiware-cygnus/blob/master/README.md, but it does not work when browsing from the root of the repo.

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-cygnus/pull/889
