### ISSUE TITLE
[doc] Use Apiary for documenting the Management Interface API

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#892]
https://apiary.io/

Actual API file: https://github.com/telefonicaid/fiware-cygnus/blob/develop/cygnus-ngsi/doc/installation_and_administration_guide/management_interface.md

**Comment by pcoello25** [comment]
First version is now online. 

http://telefonicaid.github.io/fiware-cygnus/cygnus-ngsi/doc/apiary/v1/fiware-cygnus-cookbook.html

I'm testing differents ways of write the information. @frbattid suggested to divide the doc in 4 categories:
* Version API
* Grouping Rules API
* Subscriptions API
* Admin API

Changes are being implemented :)

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/952 (Part 1 -> gh-pages branch)

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/962

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/989
