### ISSUE TITLE
[api] Add /admin/configuration/instance/path/to/instance.conf route

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#894]
- [x] GET `/admin/configuration/instance/path/to/instance.conf` (gets all the parameters)
- [x] GET `/admin/configuration/instance/path/to/instance.conf?param=<param_name>`
- [x] Document GET method.
- [x] Test for GET all parameters
- [x] Test for GET a single parameter  
|_____METHODS + DOCUMENTATION in PR #1087  
|_____TEST in PR #1095 
- [x] POST `/admin/configuration/instance/path/to/instance.conf?param=<param_name>&value=<param_value>`
- [x] Document POST method.
- [x] Test for POST a single parameter  
|_____METHODS + DOCUMENTATION in PR #1089  
|_____TEST in PRhttps://github.com/telefonicaid/fiware-cygnus/pull/1097
- [x] PUT `/admin/configuration/instance/path/to/instance.conf?param=<param_name>&value=<param_value>`
- [x] Document PUT method.
- [x] Test fot PUT a single parameter  
|_____METHODS + DOCUMENTATION in PR #1088  
|_____TEST in PR #1096
- [x] DELETE `/admin/configuration/instance/path/to/instance.conf?param=<param_name>`
- [x] Document DELETE method
- [x] Test for DELETE a single parameter  
|_____METHODS + DOCUMENTATION in PR #1094  
|_____ TEST in PR https://github.com/telefonicaid/fiware-cygnus/pull/1099

**Comment by pcoello25** [comment]
Partially implemented in #1087 (GET all & GET single parameter + documentation)

**Comment by pcoello25** [comment]
Partially implemented in #1089 (POST a single parameter + documentation)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1088 (PUT a single parameter + documentation)

**Comment by pcoello25** [comment]
Partially implemented in #1094 (DELETE a single parameter + documentation)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1095 (Tests for GET method)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1096 (Tests for PUT method)

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1097 (Tests for POST method)

**Comment by pcoello25** [comment]
Fixed in #1098 (Some mocked methods was disabled in order to make a revision)

**Comment by pcoello25** [comment]
Partiall implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1099 (Test for DELETE method)
