### ISSUE TITLE
[OrionKafkaSink] Create a KafkaBackend

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#912]
Currently, there is a mix in `OrionKafkaSink`:

* There is a legacy `persistenceBackend` based on KafkaProducer.
* There is a `TopicAPI` private class implementing certain backend functions.

Both of them must be joined in a `KafkaBackend/KafkaBackendImpl` with, at least, the following 3 methods:

* `boolean topicExists(ZkClient zookeeperClient, String topic)`
* `void createTopic(ZkClient zookeeperClient, String topic, int partitions, int replicationFactor, Properties props)`
* `send(ProducerRecord<String, String> record)`

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Partially implemented in https://github.com/telefonicaid/fiware-cygnus/pull/914 (KafkaBackEndImpl + The backend sends a message to Kafka).
