### ISSUE TITLE
[grouping rules] Precompile the regexes once read

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#928]
Currently, the grouping rules regexes are not precompiled but compiled each time they want to be used:

```
GroupingRule.java:

    /**
     * Gets the compiled pattern.
     * @return The compiled pattern
     */
    public Pattern getPattern() {
        return Pattern.compile((String) jsonRule.get("regex"));
    } // getPattern
```

The patterns must be precompiled on the constructor and stored as a class attribute for future retrieving.

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/934
