### ISSUE TITLE
[ManagementInterface] Add the Fiware-Correlator header to the response Http messages

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#932]
Requests to Management Interface/API must return a correlator ID in the responses, as a http header.

Such a correlator ID must be reused if present in the API request as a header. If not, it must be generated by the API (there already exist a utility function for this).

Either sent or generated, this ID must be traced the same way incoming notifications are traced, i.e. as the `corr` field in the log4j layout.

In addition, an internal transaction ID must be generated at the same time the correlator ID is reused/generated. In this case, it is always generated, and its value must be the same to the correlator ID when both of them have to be created. Such an internal transaction ID is not sent back in the response, but traced as the `trans` field in the log4j layout.

<b>Effort: 3 man day</b>

**Comment by frbattid** [comment]
Assigning to @pcoello25 regarding the Management Interface part of the issue.

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/1008
