### ISSUE TITLE
[api] Update version of api method from v1 to v2 (create subscriptions)

### ISSUE THREAD

**Issue by pcoello25** [telefonicaid/fiware-cygnus#957]
Create subscriptions with API uses /v1/subscribeContext from Orion. Actually we need to use /v2/subscribeContext and this method needs to be fixed.

**Comment by frbattid** [comment]
Closing since issue https://github.com/telefonicaid/fiware-cygnus/issues/808 will be supporting both NGSI v1 and v2.
