### ISSUE TITLE
[OrionCKANSink] Document how to create a CKAN resource/datastore for the column mode

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#971]
Affected document: https://github.com/telefonicaid/fiware-cygnus/blob/develop/doc/cygnus-ngsi/flume_extensions_catalogue/orion_ckan_sink.md

Add a final "Annexes" section, and a "Provisioning a CKAN resource for the column mode" subsection. This subsection must be referenced from the already existent "About the persistence mode" subsection, something like "Please check the Annexes in order to know how to provision a CKAN resource for the column mode".

Regarding the content, use the answer given in this SOF question:

http://stackoverflow.com/questions/36770274/how-to-provision-a-datastore-in-ckan-for-connecting-cygnus-in-column-persistance

<b>Effort: 1 man day</b>

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/972
