### ISSUE TITLE
[releasing] Automate the creation of the Docker image in Docker Hub

### ISSUE THREAD

**Issue by dmabtrg** [telefonicaid/fiware-cygnus#974]
The current process for building the docker image is convoluted.  This involves building a docker image to create a container that will compile the jar and place it on a volume mapped to the host, then create a new image that copies the jar from the host to the image.  This building process will not allow the automation of the image in Docker Hub.  The [FIWARE Docker guidelines](http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Docker) says:

> A GEi's Docker MUST be published at least under the 'fiware' account on DockerHub (if possible, please avoid the term 'fiware' in your repository name, as the username already contains it). The GEi owner will be responsible for publication and maintenance operations. **The publication method will be through the 'Automatic Build Procedure'** which allows to link a Github repository to a Dockerhub one (and keep them in sync). In order to get access to that account and proceed with the publication, please get in touch with José Manuel Cantera.

(emphasis mine).

You can take a look at https://github.com/telefonicaid/fiware-orion/tree/develop/docker and https://github.com/Bitergia/fiware-chanchan-docker/tree/master/images/cygnus/develop to see examples of how to create a docker image that compiles the application when building the image (instead of using another image) and that can be automated in Docker Hub.

Thanks.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-cygnus/pull/993
