### ISSUE TITLE
[cygnus-ngsi][NGSIMongoSink,NGSISTHSink] Uniformize parameters and conventions in STH and Cygnus

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-cygnus#976]

**Comment by frbattid** [comment]
@cesarjorgemartinez , can you detail this issue, please?

**Comment by frbattid** [comment]
After an offline discussion, this is mainly about uniformizing the parameters used in STH and Cygnus (with regards to STH).

One of the hot parameters is `data_model`,  which takes values of the form `dm-by-something` in Cygnus, but values of the form `collections-per-something` in STH. Nevertheless, as already discussed, the `data_model` parameter has been generalized to all Cygnus, thus it cannot be changed. In this case, STH should be the one adapting to the conventions of Cygnus.

**Comment by frbattid** [comment]
Closing since the needed changes must be done in STH.
