### ISSUE TITLE
[doc] Fix the grouping rules configuration in the QSG

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-cygnus#983]
Reference: http://stackoverflow.com/questions/36914589/how-to-combine-multiple-orion-entities-to-one-ckan-dataset-using-cygnus/37003783?noredirect=1#comment61568354_37003783

**Comment by pcoello25** [comment]
Implemented in https://github.com/telefonicaid/fiware-cygnus/pull/986
